/* Dehesa Index — Catálogo de datos: explorador del manifiesto (js/series-store.js). ES5. */
(function () {
  'use strict';
  var T = {
    es: { title: 'Catálogo de datos', sub: 'Todas las series de país en un catálogo común. Cada una se descarga como un fichero pequeño y solo cuando la abres: nunca hace falta bajar un dataset enorme.',
      cc: 'País', metric: 'Métrica', prod: 'Producto', q: 'Buscar', all: 'Todos', series: 'series', countries: 'países', aggr: 'agregados', regs: 'regiones', files: 'ficheros de datos', shown: 'Mostrando', of: 'de', more: 'Ver más', unit: 'Unidad', freq: 'Frecuencia', last: 'Último dato', period: 'Periodo', pts: 'Puntos', tier: 'Fuente', open: 'Abrir en la página del país', file: 'Fichero de datos', dl: 'Descargado hasta ahora', size: 'KB', none: 'Sin resultados.', loading: 'Cargando…',
      how: 'Cómo funciona: la búsqueda usa un índice compacto, troceado por país (solo etiqueta, país, unidad, frecuencia, último periodo y estado de frescura). El catálogo del país y el fichero con los puntos solo se descargan cuando abres una serie.', tags: 'Los productos son etiquetas por palabras clave de la etiqueta de la serie (heurística), no una clasificación oficial.',
      tiers: { 1: 'Organismo nacional', 2: 'Eurostat', 3: 'Organización internacional', 4: 'Secundaria' }, mm: { product: 'Precios de producto', production: 'Producción', crops: 'Cultivos', livestock: 'Ganado', trade: 'Comercio', quotes: 'Cotizaciones', prices: 'Precios', prices_paid: 'Precios pagados', milk: 'Leche', milk_regions: 'Leche por región', crops_regions: 'Cultivos por región', prices_lv: 'Precios ganado', meat_regions: 'Carne por región', prices_fv: 'Fruta y hortaliza', inputs: 'Insumos', inputs_f: 'Fertilizantes', inputs_a: 'Piensos', idx_perc: 'Índices percibidos', idx_pag: 'Índices pagados', costs: 'Costes', environment: 'Medio ambiente', organic: 'Ecológico', stocks: 'Existencias', income: 'Renta', partners: 'Socios comerciales', rates: 'Tipos de interés' } },
    en: { title: 'Data catalogue', sub: 'Every country series in one common catalogue. Each one downloads as a small file and only when you open it: no huge dataset is ever needed.',
      cc: 'Country', metric: 'Metric', prod: 'Product', q: 'Search', all: 'All', series: 'series', countries: 'countries', aggr: 'aggregates', regs: 'regions', files: 'data files', shown: 'Showing', of: 'of', more: 'Show more', unit: 'Unit', freq: 'Frequency', last: 'Latest', period: 'Period', pts: 'Points', tier: 'Source', open: 'Open on the country page', file: 'Data file', dl: 'Downloaded so far', size: 'KB', none: 'No results.', loading: 'Loading…',
      how: 'How it works: search uses a compact index split by country (label, country, unit, frequency, latest period and freshness state only). The country catalogue and the points file are downloaded only when you open a series.', tags: 'Products are keyword tags derived from the series label (heuristic), not an official classification.',
      tiers: { 1: 'National body', 2: 'Eurostat', 3: 'International organisation', 4: 'Secondary' }, mm: { product: 'Product prices', production: 'Production', crops: 'Crops', livestock: 'Livestock', trade: 'Trade', quotes: 'Quotes', prices: 'Prices', prices_paid: 'Prices paid', milk: 'Milk', milk_regions: 'Milk by region', crops_regions: 'Crops by region', prices_lv: 'Livestock prices', meat_regions: 'Meat by region', prices_fv: 'Fruit and vegetables', inputs: 'Inputs', inputs_f: 'Fertilisers', inputs_a: 'Feed', idx_perc: 'Output indices', idx_pag: 'Input indices', costs: 'Costs', environment: 'Environment', organic: 'Organic', stocks: 'Stocks', income: 'Income', partners: 'Trade partners', rates: 'Interest rates' } },
    fr: { title: 'Catalogue de données', sub: 'Toutes les séries de pays dans un catalogue commun. Chacune se télécharge comme un petit fichier, seulement quand vous l’ouvrez : jamais besoin d’un énorme jeu de données.',
      cc: 'Pays', metric: 'Indicateur', prod: 'Produit', q: 'Rechercher', all: 'Tous', series: 'séries', countries: 'pays', aggr: 'agrégats', regs: 'régions', files: 'fichiers de données', shown: 'Affichage', of: 'sur', more: 'Voir plus', unit: 'Unité', freq: 'Fréquence', last: 'Dernière donnée', period: 'Période', pts: 'Points', tier: 'Source', open: 'Ouvrir sur la page du pays', file: 'Fichier de données', dl: 'Téléchargé jusqu’ici', size: 'Ko', none: 'Aucun résultat.', loading: 'Chargement…',
      how: 'Fonctionnement : la recherche utilise un index compact découpé par pays (libellé, pays, unité, fréquence, dernière période et état de fraîcheur). Le catalogue du pays et le fichier des points ne sont téléchargés qu’à l’ouverture d’une série.', tags: 'Les produits sont des étiquettes par mots-clés du libellé de la série (heuristique), pas une classification officielle.',
      tiers: { 1: 'Organisme national', 2: 'Eurostat', 3: 'Organisation internationale', 4: 'Secondaire' }, mm: {} },
    it: { title: 'Catalogo dei dati', sub: 'Tutte le serie dei paesi in un catalogo comune. Ognuna si scarica come un piccolo file e solo quando la apri: mai un dataset enorme.',
      cc: 'Paese', metric: 'Metrica', prod: 'Prodotto', q: 'Cerca', all: 'Tutti', series: 'serie', countries: 'paesi', aggr: 'aggregati', regs: 'regioni', files: 'file di dati', shown: 'Mostro', of: 'di', more: 'Mostra altro', unit: 'Unità', freq: 'Frequenza', last: 'Ultimo dato', period: 'Periodo', pts: 'Punti', tier: 'Fonte', open: 'Apri nella pagina del paese', file: 'File di dati', dl: 'Scaricato finora', size: 'KB', none: 'Nessun risultato.', loading: 'Caricamento…',
      how: 'Come funziona: la ricerca usa un indice compatto suddiviso per paese (etichetta, paese, unità, frequenza, ultimo periodo e stato di freschezza). Il catalogo del paese e il file dei punti si scaricano solo quando apri una serie.', tags: 'I prodotti sono etichette per parole chiave dell’etichetta della serie (euristica), non una classificazione ufficiale.',
      tiers: { 1: 'Ente nazionale', 2: 'Eurostat', 3: 'Organizzazione internazionale', 4: 'Secondaria' }, mm: {} }
  };
  var X = { es: { fresh: 'Frescura', fsAll: 'Todas', fsActive: 'Activas (sin históricas)', na: 'sin dato' }, en: { fresh: 'Freshness', fsAll: 'All', fsActive: 'Active (no historical)', na: 'n/a' }, fr: { fresh: 'Fraîcheur', fsAll: 'Toutes', fsActive: 'Actives (hors historiques)', na: 'n.d.' }, it: { fresh: 'Freschezza', fsAll: 'Tutte', fsActive: 'Attive (senza storiche)', na: 'n.d.' } };
  function xx() { return X[lang()] || X.es; }
  function fsLab(st) { var L = window.DIFreshness && DIFreshness.label[st]; return L ? (L[lang()] || L.en) : st; }
  function fsB(st) { return '<span class="pt-badge pt-fs-' + esc(st) + '">' + esc(fsLab(st)) + '</span>'; }
  var ST = { cc: '', g: '', tag: '', q: '', fs: '', lim: 40, sel: null }, M = null, ROWS = [], TOTAL = 0, OPEN = null;
  function lang() { return window.DehesaShared && window.DehesaShared.getLang ? window.DehesaShared.getLang() : 'es'; }
  function tt() { return T[lang()] || T.es; }
  function esc(s) { return String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;'); }
  function nf(v) { if (typeof v !== 'number') return esc(v == null ? '–' : v); var d = Math.abs(v) >= 1000 ? 0 : Math.abs(v) >= 10 ? 1 : 2; try { return v.toLocaleString(lang(), { maximumFractionDigits: d }); } catch (e) { return String(v); } }
  function cname(c, d) { var ag = window.DIAgg && DIAgg.label(c, lang()); if (ag) return ag; try { var n = new Intl.DisplayNames([lang()], { type: 'region' }).of(c === 'EL' ? 'GR' : c); return n && n !== c ? n : d; } catch (e) { return d; } }
  // Etiquetas de interfaz traducidas (auditoria 8-oct-2026): nada de «climate» o «wheat» en la vista española; el codigo sigue en el valor del filtro
  var PRODL = { barley: ['Cebada', 'Barley', 'Orge', 'Orzo'], butter: ['Mantequilla', 'Butter', 'Beurre', 'Burro'], cattle: ['Vacuno', 'Cattle', 'Bovins', 'Bovini'], cheese: ['Queso', 'Cheese', 'Fromage', 'Formaggio'], eggs: ['Huevos', 'Eggs', 'Œufs', 'Uova'], energy: ['Energía', 'Energy', 'Énergie', 'Energia'], fertilizer: ['Fertilizantes', 'Fertilizer', 'Engrais', 'Fertilizzanti'], fruit: ['Fruta y hortaliza', 'Fruit and vegetables', 'Fruits et légumes', 'Frutta e verdura'], maize: ['Maíz', 'Maize', 'Maïs', 'Mais'], milk: ['Leche', 'Milk', 'Lait', 'Latte'], oats: ['Avena', 'Oats', 'Avoine', 'Avena'], olive: ['Aceite de oliva', 'Olive oil', 'Huile d’olive', 'Olio d’oliva'], pigs: ['Porcino', 'Pigs', 'Porcs', 'Suini'], potato: ['Patata', 'Potato', 'Pomme de terre', 'Patata'], poultry: ['Aves', 'Poultry', 'Volailles', 'Pollame'], rapeseed: ['Colza', 'Rapeseed', 'Colza', 'Colza'], rice: ['Arroz', 'Rice', 'Riz', 'Riso'], rye: ['Centeno', 'Rye', 'Seigle', 'Segale'], sheep: ['Ovino', 'Sheep', 'Ovins', 'Ovini'], soy: ['Soja', 'Soy', 'Soja', 'Soia'], sugar: ['Azúcar', 'Sugar', 'Sucre', 'Zucchero'], wheat: ['Trigo', 'Wheat', 'Blé', 'Grano'], wine: ['Vino', 'Wine', 'Vin', 'Vino'] };
  var EUFAM = { aceite: ['aceite', 'olive oil', 'huile', 'olio'], arroz: ['arroz', 'rice', 'riz', 'riso'], azucar: ['azúcar', 'sugar', 'sucre', 'zucchero'], cerdo: ['cerdo', 'pigmeat', 'porc', 'suino'], cereales: ['cereales', 'cereals', 'céréales', 'cereali'], fertilizantes: ['fertilizantes', 'fertilisers', 'engrais', 'fertilizzanti'], fruta: ['fruta y hortaliza', 'fruit and vegetables', 'fruits et légumes', 'frutta e verdura'], huevos: ['huevos', 'eggs', 'œufs', 'uova'], lacteos: ['lácteos', 'dairy', 'produits laitiers', 'lattiero-caseari'], leche: ['leche cruda', 'raw milk', 'lait cru', 'latte crudo'], oleaginosas: ['oleaginosas', 'oilseeds', 'oléagineux', 'semi oleosi'], ovino: ['ovino', 'sheep meat', 'ovins', 'ovini'], pollo: ['pollo', 'poultry', 'volaille', 'pollame'], vacuno: ['vacuno', 'beef', 'bovins', 'bovini'], vino: ['vino', 'wine', 'vin', 'vino'] };
  var GEXTRA = { climate: ['Clima', 'Weather', 'Météo', 'Meteo'] };
  function li4() { var i = ['es', 'en', 'fr', 'it'].indexOf(lang()); return i < 0 ? 0 : i; }
  function slab(l) { return window.DILabelTl && window.DILabelTl.ready(lang()) ? window.DILabelTl.tl(l, lang()) : l; }   // etiqueta original en el detalle tecnico, traducida en la lista
  function plab(p) { return PRODL[p] ? PRODL[p][li4()] : p; }
  function mlab(g) { var t = tt(); if (/^eu_/.test(g)) { var k = g.slice(3); return ({ es: 'UE · Comisión', en: 'EU · Commission', fr: 'UE · Commission', it: 'UE · Commissione' })[lang()] + ': ' + (EUFAM[k] ? EUFAM[k][li4()] : k); } return (t.mm && t.mm[g]) || (GEXTRA[g] && GEXTRA[g][li4()]) || T.en.mm[g] || g; }
  function flag(cc) { var f = window.DIProfile && window.DIProfile.flag ? window.DIProfile.flag(cc) : ''; return f || (window.DIAgg ? DIAgg.flag(cc) : ''); }
  function ts(p) { var y = +p.slice(0, 4), m = p.length >= 7 ? +p.slice(5, 7) - 1 : 0, d = p.length >= 10 ? +p.slice(8, 10) : 1; if (/Q/.test(p)) { m = (+p.split('Q')[1] - 1) * 3; } return Date.UTC(y, m || 0, d || 1); }
  function sel(id, label, inner) { return '<label style="font-size:13px;flex:1;min-width:150px">' + esc(label) + '<br><select id="' + id + '" class="di-compare-select">' + inner + '</select></label>'; }
  function browsing() { return !ST.cc && !ST.g && !ST.tag && !ST.fs && !(ST.q || '').trim(); }
  // sin filtros solo se bajan los trozos del indice necesarios para la primera pagina; con filtros, los que pueden coincidir
  function filterRows() { if (browsing()) return DISeries.browse(ST.lim).then(function (r) { ROWS = r.rows; TOTAL = r.total; }); return DISeries.find({ cc: ST.cc || null, group: ST.g || null, tag: ST.tag || null, q: ST.q, fs: ST.fs || null }).then(function (r) { ROWS = r; TOTAL = r.length; }); }
  function ents(M, t) { var e = M.entities || {}; if (!e.country) return Object.keys(M.countries).length + ' ' + esc(t.countries); return e.country + ' ' + esc(t.countries) + (e.aggregate ? ' · ' + e.aggregate + ' ' + esc(t.aggr) : '') + (e.region ? ' · ' + e.region + ' ' + esc(t.regs) : ''); }
  function shell() {
    var root = document.getElementById('cat-body'), t = tt(); if (!root || !M) return;
    var h1 = document.getElementById('ct-h1'), sb = document.getElementById('ct-sub'); if (h1) h1.textContent = t.title; if (sb) sb.textContent = t.sub; document.title = t.title + ' | Dehesa Index';
    var nfiles = 0; Object.keys(M.countries).forEach(function (c) { Object.keys(M.countries[c].metrics).forEach(function (g) { nfiles += M.countries[c].metrics[g].files.length; }); });
    var cOpt = '<option value="">' + esc(t.all) + '</option>' + Object.keys(M.countries).map(function (c) { return '<option value="' + c + '"' + (c === ST.cc ? ' selected' : '') + '>' + flag(c) + ' ' + esc(cname(c, M.countries[c].name)) + ' (' + M.countries[c].n + ')</option>'; }).join('');
    var gs = {}; Object.keys(M.countries).forEach(function (c) { if (ST.cc && c !== ST.cc) return; Object.keys(M.countries[c].metrics).forEach(function (g) { gs[g] = (gs[g] || 0) + M.countries[c].metrics[g].n; }); });
    var gOpt = '<option value="">' + esc(t.all) + '</option>' + Object.keys(gs).sort().map(function (g) { return '<option value="' + g + '"' + (g === ST.g ? ' selected' : '') + '>' + esc(mlab(g)) + ' (' + gs[g] + ')</option>'; }).join('');
    var pOpt = '<option value="">' + esc(t.all) + '</option>' + Object.keys(M.products).sort(function (a, b) { return plab(a).localeCompare(plab(b), lang()); }).map(function (p) { return '<option value="' + p + '"' + (p === ST.tag ? ' selected' : '') + '>' + esc(plab(p)) + '</option>'; }).join('');
    root.innerHTML = '<p class="di-movers-hint" style="margin:0 0 12px"><strong>' + M.seriesTotal.toLocaleString(lang()) + '</strong> ' + esc(t.series) + ' · ' + ents(M, t) + ' · ' + nfiles + ' ' + esc(t.files) + '</p>' +
      '<div class="di-card" style="padding:14px 16px;margin-bottom:14px"><div style="display:flex;gap:12px;flex-wrap:wrap;margin-bottom:10px">' + sel('ct-c', t.cc, cOpt) + sel('ct-g', t.metric, gOpt) + sel('ct-p', t.prod, pOpt) + sel('ct-f', xx().fresh, ['', 'active', 'LIVE', 'FRESH', 'EXPECTED_DELAY', 'DELAYED', 'STALE', 'HISTORICAL', 'DISCONTINUED'].map(function (v) { return '<option value="' + v + '"' + (v === ST.fs ? ' selected' : '') + '>' + esc(v === '' ? xx().fsAll : v === 'active' ? xx().fsActive : fsLab(v)) + '</option>'; }).join('')) + '<label style="font-size:13px;flex:2;min-width:180px">' + esc(t.q) + '<br><input id="ct-q" type="search" value="' + esc(ST.q) + '" style="width:100%;box-sizing:border-box;font:inherit;padding:7px 10px;border:1px solid var(--border);border-radius:8px;background:var(--surface,#fff);color:inherit"></label></div><div class="di-movers-hint" style="margin:0">' + esc(t.how) + '</div></div>' +
      '<div id="ct-detail"></div><div id="ct-list"></div><p id="ct-foot" class="di-movers-hint"></p>';
    document.getElementById('ct-c').onchange = function (e) { ST.cc = e.target.value; ST.g = ''; ST.lim = 40; shell(); refresh(); };
    document.getElementById('ct-g').onchange = function (e) { ST.g = e.target.value; ST.lim = 40; refresh(); };
    document.getElementById('ct-f').onchange = function (e) { ST.fs = e.target.value; ST.lim = 40; refresh(); };
    document.getElementById('ct-p').onchange = function (e) { ST.tag = e.target.value; ST.lim = 40; refresh(); };
    var qt; document.getElementById('ct-q').oninput = function (e) { ST.q = e.target.value; ST.lim = 40; clearTimeout(qt); qt = setTimeout(refresh, 200); };
  }
  function refresh() { var list = document.getElementById('ct-list'); if (list) list.innerHTML = '<p class="di-movers-hint">' + esc(tt().loading) + '</p>'; filterRows().then(renderList).catch(function () { if (list) list.innerHTML = '<p class="di-movers-hint">' + esc(tt().none) + '</p>'; }); }
  var SRCH = { es: 'Fuente', en: 'Source', fr: 'Source', it: 'Fonte' };
  function renderList() {
    var t = tt(), list = document.getElementById('ct-list'); if (!list) return;
    if (!ROWS.length) { list.innerHTML = '<p class="di-movers-hint">' + esc(t.none) + '</p>'; foot(); return; }
    var shown = ROWS.slice(0, ST.lim), th = function (x) { return '<th scope="col" style="text-align:left;font-size:11px;color:var(--text-faint);padding:4px 8px;border-bottom:1px solid var(--border)">' + esc(x) + '</th>'; };
    list.innerHTML = '<div class="di-card" style="padding:8px 12px"><div class="di-table-wrap"><table style="width:100%;border-collapse:collapse;font-size:13px"><thead><tr>' + th(t.cc) + th(t.metric) + th(t.series) + th(t.unit) + th(t.period) + th(xx().fresh) + th(SRCH[lang()] || SRCH.es) + '</tr></thead><tbody>' +
      shown.map(function (r, i) { var s = r.s; return '<tr style="cursor:pointer" tabindex="0" data-i="' + i + '"><td data-label="' + esc(t.cc) + '">' + flag(r.cc) + ' ' + esc(r.cc) + '</td><td data-label="' + esc(t.metric) + '">' + esc(mlab(s.group)) + '</td><th scope="row" style="text-align:left;font-weight:500" data-label="' + esc(t.series) + '">' + esc(slab(s.label)) + '</th><td data-label="' + esc(t.unit) + '"><span style="color:var(--text-faint);font-size:12px">' + esc(s.unit) + '</span></td><td data-label="' + esc(t.period) + '">' + esc(s.latestPeriod || xx().na) + '</td><td data-label="' + esc(xx().fresh) + '">' + fsB(s.fs) + '</td><td data-label="' + esc(SRCH[lang()] || SRCH.es) + '">' + ((window.DICite && s.sourceId && window.DICite.html(s.sourceId, { period: s.latestPeriod })) || '') + '</td></tr>'; }).join('') + '</tbody></table></div>' +
      (TOTAL > ST.lim ? '<button type="button" id="ct-more" style="margin:8px 0;font:inherit;padding:4px 14px;border:1px solid var(--border);border-radius:999px;background:transparent;color:inherit;cursor:pointer">' + esc(t.more) + '</button>' : '') + '</div>';
    Array.prototype.forEach.call(list.querySelectorAll('tr[data-i]'), function (tr) { var go = function () { openSeries(shown[+tr.getAttribute('data-i')]); }; tr.onclick = go; tr.onkeydown = function (e) { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); go(); } }; });
    var mb = document.getElementById('ct-more'); if (mb) mb.onclick = function () { ST.lim += 60; if (browsing() && ROWS.length < Math.min(ST.lim, TOTAL)) refresh(); else renderList(); };
    foot();
  }
  function foot() { var t = tt(), f = document.getElementById('ct-foot'); if (!f) return; var s = DISeries.stats(); f.textContent = t.shown + ' ' + Math.min(ST.lim, ROWS.length) + ' ' + t.of + ' ' + TOTAL + ' ' + t.series + ' · ' + t.dl + ': ' + s.files + ' ' + t.files + (s.bytes ? ' (' + Math.round(s.bytes / 1024) + ' ' + t.size + ')' : '') + '. ' + t.tags; }
  function openSeries(r) {
    var t = tt(), box = document.getElementById('ct-detail'); if (!box) return; box.innerHTML = '<div class="di-card" style="padding:14px 16px;margin-bottom:14px"><p class="di-movers-hint">' + esc(t.loading) + '</p></div>';
    DISeries.series(r.cc, r.s.id).then(function (s) {
      var pts = s.points.map(function (p) { return { x: ts(String(p[0])), y: p[1], l: String(p[0]) }; }), m = s.meta;
      var chart = window.DehesaChart ? window.DehesaChart.render({ series: [{ name: s.label, color: '#2f6b4a', pts: pts }], xMode: 'time', yTitle: s.unit, noLegend: true, aria: s.label + ' (' + s.unit + ')' }) : '';
      box.innerHTML = '<div class="di-card" style="padding:14px 16px;margin-bottom:14px"><div style="font-size:12px;font-weight:700;letter-spacing:.4px;color:var(--text-faint)">' + flag(r.cc) + ' ' + esc(r.cc) + ' · ' + esc(mlab(m.group).toUpperCase()) + '</div><h2 style="margin:2px 0 8px;font-size:17px">' + esc(slab(s.label)) + ' <span style="font-weight:400;color:var(--text-faint);font-size:13px">(' + esc(s.unit) + ' · ' + esc(s.frequency) + ')</span></h2>' + chart +
        '<div class="di-movers-hint" style="margin-top:8px">' + esc(t.tier) + ': ' + esc((t.tiers || {})[m.tier] || '–') + ' · ' + esc(t.file) + ': <a href="data/' + esc(m.file) + '" style="color:inherit">data/' + esc(m.file) + '</a> ' + (m.format === 'eu-regions' || m.group === 'product' ? '' : ' · <a href="paises.html?c=' + encodeURIComponent(r.cc) + '&g=' + encodeURIComponent(m.group) + '&s=' + encodeURIComponent(s.id) + '" style="color:inherit">' + esc(t.open) + ' →</a>') + '</div></div>';
      foot(); if (box.scrollIntoView) box.scrollIntoView({ block: 'nearest' });
    }).catch(function () { box.innerHTML = ''; });
  }
  window.DehesaShared.init('informacion');
  var prev = window.DehesaShared.onLangChange;
  window.DehesaShared.onLangChange = function () { if (prev) prev.apply(this, arguments); shell(); renderList(); };
  var q = new URLSearchParams(location.search); if (q.get('c')) ST.cc = q.get('c').toUpperCase(); if (q.get('g')) ST.g = q.get('g'); if (q.get('p')) ST.tag = q.get('p'); if (q.get('q')) ST.q = q.get('q'); if (q.get('f')) ST.fs = q.get('f');
  // Sin filtros en la URL: empieza por el pais de Mi mercado si el usuario lo eligio (auditoria 8-oct-2026)
  if (!location.search) { try { var mm = JSON.parse(window.localStorage.getItem('di-mi-mercado-v1') || 'null'); if (mm && /^[A-Z]{2}$/.test(mm.c || '')) ST.cc = mm.c; } catch (e) {} }
  (window.DICite ? window.DICite.load() : Promise.resolve()).catch(function () {}).then(function () { return DISeries.manifest(); }).then(function (m) { M = m; if (ST.cc && !M.countries[ST.cc]) ST.cc = ''; shell(); refresh(); }).catch(function () { var r = document.getElementById('cat-body'); if (r) r.innerHTML = '<p class="di-movers-hint">' + tt().none + '</p>'; });
})();
