/* Suiza: cadena de valor y prima bio (FOAG). Carga perezosa desde perfil-pais.js solo en la ficha de CH. ES5. */
(function () {

  var CHT = { es: { h: 'Cadena de valor y prima bio (Suiza)', hint: 'Evolución de cada etapa en índice base 100 (primer mes común) y prima ecológica sobre convencional. Es descriptivo: no resta etapas ni calcula márgenes.', st: { producer: 'Productor', processor: 'Transformación', processor2: 'Harina', consumer: 'Consumo' }, i: 'Índice', c: 'Var. 12 m', base: 'Base 100', prem: 'Prima ecológica', vat: 'IVA', cav: 'Cada etapa conserva su unidad y base de IVA (productor y consumo con IVA, transformación sin IVA). Los productos de cada etapa no son idénticos: se compara la evolución, no el nivel. La prima compara las especificaciones publicadas por la OFAG.', ch: { 'milk-butter': 'Leche → mantequilla', 'milk-uht': 'Leche → leche UHT', 'milk-powder': 'Leche → leche desnatada en polvo → leche UHT', eggs: 'Huevos', 'wheat-flour': 'Trigo → molino → harina (medias anuales)' }, pr: { 'milk-producer': 'Leche: productor, ecológica vs. convencional', 'eggs-producer-barn': 'Huevos: productor, ecológico vs. suelo', 'eggs-producer-freerange': 'Huevos: productor, ecológico vs. campero', 'eggs-retail-barn': 'Huevos: consumo, ecológico vs. suelo', 'eggs-retail-freerange': 'Huevos: consumo, ecológico vs. campero', 'wheat-producer': 'Trigo: productor, ecológico vs. convencional', 'wheat-mill': 'Trigo: franco molino, ecológico vs. convencional', 'rapeseed-producer': 'Colza: productor, ecológica vs. convencional' } },
    en: { h: 'Value chain and organic premium (Switzerland)', hint: 'Each stage as an index (base 100 = first common period) and the organic premium over conventional. Descriptive only: no stage is subtracted and no margin is calculated.', st: { producer: 'Producer', processor: 'Processing', processor2: 'Flour', consumer: 'Retail' }, i: 'Index', c: '12-m chg', base: 'Base 100', prem: 'Organic premium', vat: 'VAT', cav: 'Each stage keeps its own unit and VAT basis (producer and retail incl. VAT, processing excl. VAT). Products at each stage are not identical: the evolution is compared, not the level. The premium compares the specifications published by FOAG.', ch: { 'milk-butter': 'Milk → butter', 'milk-uht': 'Milk → UHT milk', 'milk-powder': 'Milk → skimmed milk powder → UHT milk', eggs: 'Eggs', 'wheat-flour': 'Wheat → mill → flour (annual means)' }, pr: { 'milk-producer': 'Milk: producer, organic vs. conventional', 'eggs-producer-barn': 'Eggs: producer, organic vs. barn', 'eggs-producer-freerange': 'Eggs: producer, organic vs. free range', 'eggs-retail-barn': 'Eggs: retail, organic vs. barn', 'eggs-retail-freerange': 'Eggs: retail, organic vs. free range', 'wheat-producer': 'Wheat: producer, organic vs. conventional', 'wheat-mill': 'Wheat: franco mill, organic vs. conventional', 'rapeseed-producer': 'Rapeseed: producer, organic vs. conventional' } },
    fr: { h: 'Chaîne de valeur et prime bio (Suisse)', hint: 'Chaque étape en indice base 100 (premier mois commun) et prime bio par rapport au conventionnel. Descriptif : aucune étape n’est soustraite, aucune marge n’est calculée.', st: { producer: 'Producteur', processor: 'Transformation', processor2: 'Farine', consumer: 'Consommation' }, i: 'Indice', c: 'Var. 12 m', base: 'Base 100', prem: 'Prime bio', vat: 'TVA', cav: 'Chaque étape garde son unité et sa base de TVA (producteur et consommation TTC, transformation HT). Les produits de chaque étape ne sont pas identiques : on compare l’évolution, pas le niveau. La prime compare les spécifications publiées par l’OFAG.', ch: { 'milk-butter': 'Lait → beurre', 'milk-uht': 'Lait → lait UHT', 'milk-powder': 'Lait → lait écrémé en poudre → lait UHT', eggs: 'Œufs', 'wheat-flour': 'Blé → moulin → farine (moyennes annuelles)' }, pr: { 'milk-producer': 'Lait : producteur, bio vs. conventionnel', 'eggs-producer-barn': 'Œufs : producteur, bio vs. sol', 'eggs-producer-freerange': 'Œufs : producteur, bio vs. plein air', 'eggs-retail-barn': 'Œufs : consommation, bio vs. sol', 'eggs-retail-freerange': 'Œufs : consommation, bio vs. plein air', 'wheat-producer': 'Blé : producteur, bio vs. conventionnel', 'wheat-mill': 'Blé : franco moulin, bio vs. conventionnel', 'rapeseed-producer': 'Colza : producteur, bio vs. conventionnel' } },
    it: { h: 'Filiera e premio bio (Svizzera)', hint: 'Ogni fase come indice base 100 (primo mese comune) e premio biologico rispetto al convenzionale. Solo descrittivo: nessuna fase viene sottratta e nessun margine è calcolato.', st: { producer: 'Produttore', processor: 'Trasformazione', processor2: 'Farina', consumer: 'Consumo' }, i: 'Indice', c: 'Var. 12 m', base: 'Base 100', prem: 'Premio bio', vat: 'IVA', cav: 'Ogni fase mantiene la propria unità e base IVA (produttore e consumo con IVA, trasformazione senza IVA). I prodotti di ogni fase non sono identici: si confronta l’evoluzione, non il livello. Il premio confronta le specifiche pubblicate dall’UFAG.', ch: { 'milk-butter': 'Latte → burro', 'milk-uht': 'Latte → latte UHT', 'milk-powder': 'Latte → latte scremato in polvere → latte UHT', eggs: 'Uova', 'wheat-flour': 'Frumento → mulino → farina (medie annuali)' }, pr: { 'milk-producer': 'Latte: produttore, bio vs. convenzionale', 'eggs-producer-barn': 'Uova: produttore, bio vs. a terra', 'eggs-producer-freerange': 'Uova: produttore, bio vs. all’aperto', 'eggs-retail-barn': 'Uova: consumo, bio vs. a terra', 'eggs-retail-freerange': 'Uova: consumo, bio vs. all’aperto', 'wheat-producer': 'Frumento: produttore, bio vs. convenzionale', 'wheat-mill': 'Frumento: franco mulino, bio vs. convenzionale', 'rapeseed-producer': 'Colza: produttore, bio vs. convenzionale' } } };
  function box(x) {
    var T = CHT[x.lang] || CHT.en, esc = x.esc, tries = 0;
    function put(d) {
      var el = document.getElementById('ch-chain-box'); if (!el) { if (tries++ < 30) setTimeout(function () { put(d); }, 150); return; }
      var h = '<h2 id="ch-chain" class="pp-anchor" style="margin:6px 0 4px;font-size:19px">' + esc(T.h) + '</h2><div class="di-movers-hint" style="margin:0 0 8px">' + esc(T.hint) + '</div><div class="di-card" style="padding:10px 16px;margin-bottom:10px;overflow-x:auto">';
      d.chains.forEach(function (c) {
        h += '<div style="margin:8px 0 12px"><div style="font-size:13.5px;font-weight:700">' + esc(T.ch[c.id] || c.name) + ' <span style="font-weight:400;color:var(--text-faint);font-size:12px">· ' + esc(T.base) + ' = ' + esc(c.basePeriod) + '</span></div><table style="width:100%;border-collapse:collapse;font-size:12.5px"><tbody>';
        c.stages.forEach(function (st) {
          var ch = c.change12m && c.change12m[st.stage]; var v = c.latest[st.stage];
          h += '<tr style="border-top:1px solid var(--border)"><td style="padding:4px 6px 4px 0">' + esc(T.st[st.stage] || st.stage) + ' <span style="color:var(--text-faint);font-size:11px">(' + esc(st.unit) + ', ' + esc(T.vat) + ': ' + esc(st.vat) + ')</span></td><td style="text-align:right;font-variant-numeric:tabular-nums;white-space:nowrap">' + esc(T.i) + ' <b>' + x.nf(v, 1) + '</b> <span style="color:var(--text-faint)">' + esc(c.latestPeriod) + '</span></td><td style="text-align:right;font-variant-numeric:tabular-nums;white-space:nowrap;padding-left:10px">' + (ch == null ? '' : esc(T.c) + ' <b>' + (ch > 0 ? '+' : '') + x.nf(ch, 1) + ' %</b>') + '</td></tr>';
        });
        h += '</tbody></table></div>';
      });
      h += '</div><div class="di-card" style="padding:10px 16px;margin-bottom:10px;overflow-x:auto"><div style="font-size:13.5px;font-weight:700;margin-bottom:4px">' + esc(T.prem) + '</div><table style="width:100%;border-collapse:collapse;font-size:12.5px"><tbody>';
      d.premiums.forEach(function (p) {
        h += '<tr style="border-top:1px solid var(--border)"><td style="padding:4px 6px 4px 0">' + esc(T.pr[p.id] || p.name) + ' <span style="color:var(--text-faint);font-size:11px">(' + esc(p.unit) + ')</span></td><td style="text-align:right;font-variant-numeric:tabular-nums;white-space:nowrap"><b>' + (p.latestPremiumPct > 0 ? '+' : '') + x.nf(p.latestPremiumPct, 1) + ' %</b> <span style="color:var(--text-faint)">' + esc(p.latestPeriod) + '</span></td></tr>';
      });
      h += '</tbody></table></div><div style="font-size:12px;color:var(--text-muted);margin-bottom:6px">' + esc(T.cav) + '</div>' + (window.DICite ? window.DICite.html('foag_ch', { period: d.chains[0] ? d.chains[0].latestPeriod : '' }) : '') + '<div style="height:14px"></div>';
      el.innerHTML = h;
    }
    try { Promise.all([fetch('data/ch-chain.json').then(function (r) { return r.ok ? r.json() : null; }), window.DICite && window.DICite.load ? window.DICite.load().catch(function () {}) : null]).then(function (a) { var d = a[0]; if (d && (d.chains || []).length) put(d); }).catch(function () {}); } catch (e) {}
  }
  window.DIChChain = { box: box };
})();
