/* Dehesa Index — Costes, renta y deuda de las explotaciones de Canadá (Statistics Canada). Pestaña «Canadá» de costes.html sobre js/ca-series.js. ES5. */
(function () {
  'use strict';
  var T = {
    es: { tabUS: 'EE. UU.', tabCA: 'Canadá', title: 'Costes de producción, renta y deuda de las explotaciones de Canadá', sub: 'Gastos de explotación por partida y provincia, ingresos en caja, renta neta, capital y deuda agraria. Datos de Statistics Canada, tal como se publican.',
      latest: 'Último dato', vsPrev: 'frente al periodo anterior', vsYear: 'frente al mismo periodo del año anterior', change: 'Variación', period: 'Periodo', series: 'Serie', range: 'Periodo mostrado', years: 'años', all: 'Todo', date: 'Fecha', noData: 'Sin datos disponibles.',
      note: 'Son cifras agregadas de todo el sector (millones de dólares canadienses), no el coste de una explotación concreta ni un punto de equilibrio por cultivo. Los gastos de explotación se publican para Canadá y cinco provincias (Saskatchewan, Alberta, Manitoba, Ontario y Quebec); por provincia solo cinco partidas: total, fertilizantes y cal, piensos, combustible de maquinaria e intereses. StatCan puede revisar los años recientes. Un hueco es un hueco, nunca cero.', src: 'Fuente: Statistics Canada, tablas 32-10-0049, 32-10-0045, 32-10-0046, 32-10-0052, 32-10-0050 y 32-10-0051 (Open Government Licence – Canada).' },
    en: { tabUS: 'United States', tabCA: 'Canada', title: 'Canadian farm production costs, income and debt', sub: 'Operating expenses by item and province, cash receipts, net income, farm capital and debt. Statistics Canada data as published.',
      latest: 'Latest', vsPrev: 'vs. previous period', vsYear: 'vs. same period last year', change: 'Change', period: 'Period', series: 'Series', range: 'Period shown', years: 'years', all: 'All', date: 'Date', noData: 'No data available.',
      note: 'These are sector-wide aggregates (millions of Canadian dollars), not the cost of a particular farm or a break-even per crop. Operating expenses are published for Canada and five provinces (Saskatchewan, Alberta, Manitoba, Ontario and Quebec); by province only five items: total, fertilizer and lime, feed, machinery fuel and interest. Statistics Canada may revise recent years. A gap is a gap, never zero.', src: 'Source: Statistics Canada, tables 32-10-0049, 32-10-0045, 32-10-0046, 32-10-0052, 32-10-0050 and 32-10-0051 (Open Government Licence – Canada).' },
    fr: { tabUS: 'États-Unis', tabCA: 'Canada', title: 'Coûts de production, revenu et dette des exploitations du Canada', sub: 'Dépenses d’exploitation par poste et par province, recettes monétaires, revenu net, capital et dette agricoles. Données de Statistique Canada telles que publiées.',
      latest: 'Dernière donnée', vsPrev: 'par rapport à la période précédente', vsYear: 'par rapport à la même période l’an dernier', change: 'Variation', period: 'Période', series: 'Série', range: 'Période affichée', years: 'ans', all: 'Tout', date: 'Date', noData: 'Aucune donnée disponible.',
      note: 'Ce sont des agrégats de tout le secteur (millions de dollars canadiens), pas le coût d’une exploitation précise ni un seuil de rentabilité par culture. Les dépenses d’exploitation sont publiées pour le Canada et cinq provinces (Saskatchewan, Alberta, Manitoba, Ontario et Québec) ; par province, seulement cinq postes : total, engrais et chaux, aliments du bétail, carburant des machines et intérêts. Statistique Canada peut réviser les années récentes. Un manque est un manque, jamais zéro.', src: 'Source : Statistique Canada, tableaux 32-10-0049, 32-10-0045, 32-10-0046, 32-10-0052, 32-10-0050 et 32-10-0051 (Licence du gouvernement ouvert – Canada).' },
    it: { tabUS: 'Stati Uniti', tabCA: 'Canada', title: 'Costi di produzione, reddito e debito delle aziende del Canada', sub: 'Spese di esercizio per voce e provincia, entrate monetarie, reddito netto, capitale e debito agricoli. Dati di Statistics Canada come pubblicati.',
      latest: 'Ultimo dato', vsPrev: 'rispetto al periodo precedente', vsYear: 'rispetto allo stesso periodo dell’anno scorso', change: 'Variazione', period: 'Periodo', series: 'Serie', range: 'Periodo mostrato', years: 'anni', all: 'Tutto', date: 'Data', noData: 'Nessun dato disponibile.',
      note: 'Sono aggregati dell’intero settore (milioni di dollari canadesi), non il costo di una singola azienda né un punto di pareggio per coltura. Le spese di esercizio sono pubblicate per il Canada e cinque province (Saskatchewan, Alberta, Manitoba, Ontario e Québec); per provincia solo cinque voci: totale, fertilizzanti e calce, mangimi, carburante per macchine e interessi. Statistics Canada può rivedere gli anni recenti. Un vuoto è un vuoto, mai zero.', src: 'Fonte: Statistics Canada, tabelle 32-10-0049, 32-10-0045, 32-10-0046, 32-10-0052, 32-10-0050 e 32-10-0051 (Open Government Licence – Canada).' }
  };
  window.CSCanada = window.CASeries.create({
    id: 'cs-ca', usBody: 'cs-body', usExtra: '#eucs', texts: T, defaultGroup: 'exp', cite: 'statcan',
    groups: [
      { id: 'exp', label: ['Gastos de explotación (Canadá)', 'Operating expenses (Canada)', 'Dépenses d’exploitation (Canada)', 'Spese di esercizio (Canada)'], pick: function (s) { return /^ca-exp-canada-/.test(s.id); } },
      { id: 'prov', label: ['Gastos por provincia', 'Expenses by province', 'Dépenses par province', 'Spese per provincia'], pick: function (s) { return /^ca-exp-(?!canada-)/.test(s.id); } },
      { id: 'income', label: ['Ingresos y renta', 'Receipts and income', 'Recettes et revenu', 'Entrate e reddito'], pick: function (s) { return /^ca-(nfi|recA)-/.test(s.id); } },
      { id: 'recq', label: ['Ingresos en caja (trimestral)', 'Cash receipts (quarterly)', 'Recettes monétaires (trimestriel)', 'Entrate monetarie (trimestrale)'], pick: function (s) { return /^ca-recQ-/.test(s.id); } },
      { id: 'bal', label: ['Capital y deuda', 'Capital and debt', 'Capital et dette', 'Capitale e debito'], pick: function (s) { return /^ca-(cap|debt)-/.test(s.id); } }
    ],
    usRender: function () { if (window.__csUsRender) window.__csUsRender(); }
  });
})();
