/* Dinamarca, Países Bajos y Francia en profundidad: cosecha, ganado, precios, PAC y agua (Statistics Denmark, Retsinformation, CBS, RVO, VigiEau, Céré'Obs).
   Datos: data/denmark-depth.json, data/cap/dk/*.json, data/netherlands-farm.json, data/netherlands-markets.json, data/france-vigieau.json, data/france-cereobs.json.
   ES5, sin librerías. Uso: EUDepth.mount(contenedor, modulo, lang); js/paises.js pinta la cabecera desplegable y solo descarga este modulo al abrirla. Nada se estima:
   rendimiento y variaciones se calculan aqui a partir de las cifras publicadas y se rotulan. Textos: 'es|en|fr|it'. */
(function () {
  'use strict';
  var LI = { es: 0, en: 1, fr: 2, it: 3 }, ML = {};
  var X = {
    loading: 'Cargando…|Loading…|Chargement…|Caricamento…', err: 'No se han podido cargar los datos.|The data could not be loaded.|Impossible de charger les données.|Impossibile caricare i dati.',
    crop: 'Cultivo|Crop|Culture|Coltura', meas: 'Medida|Measure|Mesure|Misura', yld: 'Rendimiento|Yield|Rendement|Resa', prod: 'Producción|Production|Production|Produzione', area: 'Superficie|Area|Surface|Superficie',
    reg: 'Región|Region|Région|Regione', last: 'Último año|Latest year|Dernière année|Ultimo anno', vsPrev: 'Vs. año anterior|Vs. prior year|Vs. année préc.|Vs. anno prec.', vs5: 'Vs. media 5 años|Vs. 5-year average|Vs. moyenne 5 ans|Vs. media 5 anni',
    upd: 'Datos hasta|Data until|Données jusqu\'à|Dati fino a', checked: 'Última comprobación|Last checked|Dernière vérification|Ultima verifica', prov: 'Provisional|Provisional|Provisoire|Provvisorio',
    th: 't/ha|t/ha|t/ha|t/ha', ha: 'ha|ha|ha|ha', kt: 'mil t|kt|kt|kt', t: 't|t|t|t', none: 'Sin datos para esta selección.|No data for this selection.|Aucune donnée pour cette sélection.|Nessun dato per questa selezione.',
    yNote: 'El rendimiento viene tal como lo publica la fuente; las variaciones las calcula Dehesa Index.|Yield is as published by the source; changes are calculated by Dehesa Index.|Le rendement est celui publié par la source ; les variations sont calculées par Dehesa Index.|La resa è quella pubblicata dalla fonte; le variazioni le calcola Dehesa Index.',
    brk: 'Desde 2025 Statistics Denmark publica este cultivo con otra clasificación (trigo de invierno y espelta, etc.); la serie nacional continúa, pero conviene comparar con cautela entre 2024 y 2025.|From 2025 Statistics Denmark publishes this crop under a new classification (e.g. winter wheat and spelt); the national series continues, but compare 2024 with 2025 with care.|Depuis 2025, Statistics Denmark publie cette culture sous une nouvelle classification (ex. blé d\'hiver et épeautre) ; la série nationale continue, mais comparez 2024 et 2025 avec prudence.|Dal 2025 Statistics Denmark pubblica questa coltura con una nuova classificazione (es. frumento tenero invernale e farro); la serie nazionale prosegue, ma confronta 2024 e 2025 con cautela.',
    view: 'Vista|View|Vue|Vista', sl: 'Sacrificios|Slaughter|Abattages|Macellazioni', milk: 'Leche|Milk|Lait|Latte', herd: 'Censos|Herd counts|Cheptel|Consistenze', sub: 'Subvenciones|Subsidies|Subventions|Sovvenzioni',
    sp: 'Especie|Species|Espèce|Specie', cat: 'Categoría|Category|Catégorie|Categoria', heads: 'Cabezas (miles)|Head (thousand)|Têtes (milliers)|Capi (migliaia)', wt: 'Producción de carne (millones de kg)|Meat production (million kg)|Production de viande (millions de kg)|Produzione di carne (milioni di kg)',
    price: 'Precio (øre DKK/kg)|Price (DKK øre/kg)|Prix (øre DKK/kg)|Prezzo (øre DKK/kg)', month: 'Último mes|Latest month|Dernier mois|Ultimo mese', sameM: 'Mismo mes del año anterior|Same month a year earlier|Même mois un an plus tôt|Stesso mese dell\'anno prima',
    mkTot: 'Leche recogida (millones de kg)|Milk collected (million kg)|Lait collecté (millions de kg)|Latte raccolto (milioni di kg)', pigsT: 'Cerdos (miles)|Pigs (thousand)|Porcs (milliers)|Suini (migliaia)',
    cattT: 'Bovino (cabezas)|Cattle (head)|Bovins (têtes)|Bovini (capi)', mDKK: 'millones DKK|million DKK|millions DKK|milioni DKK', slNote: 'El último año es provisional. Sacrificio en mataderos daneses; «producción» es peso de canal con subproductos comestibles.|The latest year is provisional. Slaughter in Danish slaughterhouses; "production" is carcass weight including edible by-products.|La dernière année est provisoire. Abattage dans les abattoirs danois ; la « production » est le poids de carcasse avec les sous-produits comestibles.|L\'ultimo anno è provvisorio. Macellazione nei macelli danesi; la «produzione» è il peso della carcassa con i sottoprodotti commestibili.',
    subNote: 'Pagos a explotaciones agrarias danesas por ejes de la PAC, millones de DKK, tal como los publica Statistics Denmark.|Payments to Danish farms by CAP strand, million DKK, as published by Statistics Denmark.|Paiements aux exploitations danoises par volet de la PAC, millions de DKK, tels que publiés par Statistics Denmark.|Pagamenti alle aziende agricole danesi per intervento PAC, milioni di DKK, come pubblicati da Statistics Denmark.',
    capT: 'Importes de 2026|2026 amounts|Montants 2026|Importi 2026', capTh: 'Umbrales y requisitos|Thresholds and requirements|Seuils et exigences|Soglie e requisiti', capDoc: 'Decretos de origen|Source orders|Arrêtés sources|Decreti di origine',
    scheme: 'Régimen|Scheme|Régime|Regime', amt: 'Importe|Amount|Montant|Importo', par: 'Artículo|Section|Article|Articolo', ver: 'versión|version|version|versione', amend: 'modificaciones|amendments|modifications|modifiche', max: 'máximo|maximum|maximum|massimo',
    capWarn: 'Atención: algún decreto ha cambiado desde la última revisión de los importes; las cifras pueden estar desfasadas hasta que se revisen.|Attention: an order has changed since the amounts were last reviewed; the figures may be out of date until reviewed.|Attention : un arrêté a changé depuis la dernière révision des montants ; les chiffres peuvent être périmés jusqu\'à leur révision.|Attenzione: un decreto è cambiato dopo l\'ultima revisione degli importi; le cifre possono essere superate finché non vengono riviste.',
    capNote: 'Extractos de los decretos daneses 1363 y 1381 de 2025 (Retsinformation), con sus modificaciones; no son el texto auténtico ni el importe final pagado: el pago real depende de la solicitud, la reducción por exceso o defecto de solicitudes y del tipo de cambio. Verificados|Extracts from Danish orders 1363 and 1381 of 2025 (Retsinformation), with their amendments; not the authentic text nor the final amount paid: actual payment depends on the application, scaling for under or over-application, and the exchange rate. Verified|Extraits des arrêtés danois 1363 et 1381 de 2025 (Retsinformation), avec leurs modifications ; ce n\'est ni le texte authentique ni le montant final versé : le paiement réel dépend de la demande, de l\'ajustement en cas de sous- ou sur-demande et du taux de change. Vérifiés|Estratti dei decreti danesi 1363 e 1381 del 2025 (Retsinformation), con le modifiche; non sono il testo autentico né l\'importo finale pagato: il pagamento effettivo dipende dalla domanda, dalla riduzione per sotto o sovra-domanda e dal cambio. Verificati',
    farms: 'Explotaciones y animales|Farms and animals|Exploitations et animaux|Aziende e animali', metric: 'Indicador|Indicator|Indicateur|Indicatore', ch5: 'Vs. 5 años antes|Vs. 5 years earlier|Vs. 5 ans plus tôt|Vs. 5 anni prima', yr: 'Año|Year|Année|Anno',
    cbsNote: 'Cifras del CBS tal como las publica (superficie en ha; rendimiento en t/ha; producción en toneladas). Las cifras del año en curso son provisionales. Algunas regiones tienen pequeñas discrepancias propias entre rendimiento y producción/superficie.|CBS figures as published (area in ha; yield in t/ha; production in tonnes). Current-year figures are provisional. Some regions show small CBS discrepancies between yield and production/area.|Chiffres du CBS tels que publiés (surface en ha ; rendement en t/ha ; production en tonnes). Les chiffres de l\'année en cours sont provisoires. Certaines régions présentent de petits écarts propres au CBS entre rendement et production/surface.|Cifre del CBS come pubblicate (superficie in ha; resa in t/ha; produzione in tonnellate). Le cifre dell\'anno in corso sono provvisorie. Alcune regioni mostrano piccole discrepanze del CBS tra resa e produzione/superficie.',
    farmNote: 'Censo de explotaciones y animales del CBS a 1 de enero/mayo según el indicador; la superficie se convierte de áreas a ha (÷100, exacto).|CBS farm and animal census; area converted from ares to ha (÷100, exact).|Recensement des exploitations et des animaux du CBS ; surface convertie d\'ares en ha (÷100, exact).|Censimento CBS di aziende e animali; superficie convertita da are a ha (÷100, esatto).',
    mk: 'Mercado|Market|Marché|Mercato', pig: 'Cerdo de cebo (clase E, EUR/100 kg)|Fattening pig (class E, EUR/100 kg)|Porc charcutier (classe E, EUR/100 kg)|Suino da ingrasso (classe E, EUR/100 kg)', pgl: 'Lechón (EUR/animal)|Piglet (EUR/head)|Porcelet (EUR/tête)|Suinetto (EUR/capo)',
    cattleP: 'Vacuno (EUR/kg canal)|Cattle (EUR/kg carcass)|Bovins (EUR/kg carcasse)|Bovini (EUR/kg carcassa)', slW: 'Sacrificio semanal de cerdos|Weekly pig slaughter|Abattage hebdomadaire de porcs|Macellazione settimanale di suini', lean: '% de carne magra|Lean meat %|% de viande maigre|% di carne magra',
    cbsSl: 'Sacrificios mensuales (CBS)|Monthly slaughter (CBS)|Abattages mensuels (CBS)|Macellazioni mensili (CBS)', pidx: 'Índice de precios agrarios (2020=100)|Farm price index (2020=100)|Indice des prix agricoles (2020=100)|Indice dei prezzi agricoli (2020=100)',
    wk: 'Semana|Week|Semaine|Settimana', vsW: 'Vs. semana anterior|Vs. prior week|Vs. semaine préc.|Vs. settimana prec.', vsY: 'Vs. misma semana del año anterior|Vs. same week last year|Vs. même semaine l\'an dernier|Vs. stessa settimana dell\'anno scorso',
    atyp: 'Semanas atípicas publicadas por RVO (precio inferior a la mitad de las semanas vecinas); se muestran tal cual|Atypical weeks as published by RVO (price below half of neighbouring weeks); shown as published|Semaines atypiques publiées par RVO (prix inférieur à la moitié des semaines voisines) ; affichées telles quelles|Settimane atipiche pubblicate da RVO (prezzo sotto la metà delle settimane vicine); mostrate così come sono',
    rvoNote: 'Precios sin IVA y sacrificios de los Excel semanales de estadísticas de mercado de RVO.|Prices excluding VAT and slaughter from RVO\'s weekly market statistics workbooks.|Prix hors TVA et abattages issus des classeurs hebdomadaires de statistiques de marché de RVO.|Prezzi IVA esclusa e macellazioni dalle cartelle settimanali delle statistiche di mercato di RVO.',
    wLevels: 'Departamentos por nivel de restricción|Departments by restriction level|Départements par niveau de restriction|Dipartimenti per livello di restrizione', lv0: 'Sin restricciones|No restrictions|Sans restriction|Nessuna restrizione', lv1: 'Vigilancia|Vigilance|Vigilance|Vigilanza', lv2: 'Alerta|Alert|Alerte|Allerta', lv3: 'Alerta reforzada|Enhanced alert|Alerte renforcée|Allerta rafforzata', lv4: 'Crisis|Crisis|Crise|Crisi',
    dep: 'Departamento|Department|Département|Dipartimento', sup: 'Aguas superficiales|Surface water|Eaux superficielles|Acque superficiali', sou: 'Aguas subterráneas|Groundwater|Eaux souterraines|Acque sotterranee', aep: 'Agua potable|Drinking water|Eau potable|Acqua potabile', all: 'Todos|All|Tous|Tutti', worst: 'Nivel máximo|Maximum level|Niveau maximal|Livello massimo',
    hist: 'Historial propio de recuentos (departamentos en crisis)|Own history of counts (departments in crisis)|Historique propre des comptages (départements en crise)|Storico proprio dei conteggi (dipartimenti in crisi)', histNote: 'La API solo publica el estado vigente; este historial empieza el día en que arrancó la tuberia y no se reconstruye.|The API only publishes the current state; this history starts the day the pipeline began and is not reconstructed.|L\'API ne publie que l\'état actuel ; cet historique commence le jour du démarrage de la chaîne et n\'est pas reconstitué.|L\'API pubblica solo lo stato attuale; questo storico parte dal giorno di avvio della pipeline e non viene ricostruito.',
    wNote: 'Nivel máximo vigente en las zonas de restricción de cada departamento, a título indicativo; solo los decretos prefectorales son auténticos. Fuente: VigiEau, Ministerio de la Transición Ecológica de Francia (Licence Ouverte 2.0).|Maximum level in force across each department\'s restriction zones, indicative only; only the prefectural orders are authentic. Source: VigiEau, French Ministry of Ecological Transition (Licence Ouverte 2.0).|Niveau maximal en vigueur dans les zones de restriction de chaque département, à titre indicatif ; seuls les arrêtés préfectoraux font foi. Source : VigiEau, ministère de la Transition écologique (Licence Ouverte 2.0).|Livello massimo in vigore nelle zone di restrizione di ciascun dipartimento, a titolo indicativo; fanno fede solo i decreti prefettizi. Fonte: VigiEau, ministero della Transizione ecologica francese (Licence Ouverte 2.0).',
    season: 'Campaña|Season|Campagne|Campagna', compare: 'Comparar con|Compare with|Comparer avec|Confronta con', nat: 'Francia|France|France|Francia', st: 'Etapa|Stage|Étape|Fase', cond: 'Estado del cultivo|Crop condition|État des cultures|Stato della coltura',
    sw: 'Siembra|Sowing|Semis|Semina', em: 'Emergencia|Emergence|Levée|Emergenza', lf: '6-8 hojas|6-8 leaves|6-8 feuilles|6-8 foglie', fl: 'Floración femenina|Female flowering|Floraison femelle|Fioritura femminile', mo: 'Humedad del grano 50 %|Grain moisture 50%|Humidité du grain 50 %|Umidità della granella 50%', hv: 'Cosecha|Harvest|Récolte|Raccolta',
    c12: 'Muy malo + malo|Very poor + poor|Très mauvais + mauvais|Molto scarso + scarso', c3: 'Medio|Fair|Moyen|Medio', c45: 'Bueno + muy bueno|Good + very good|Bon + très bon|Buono + molto buono', pcA: '% de la superficie|% of area|% de la surface|% della superficie', wkN: 'Semana|Week|Semaine|Settimana',
    mNote: 'Seguimiento semanal de técnicos de campo en el programa Céré\'Obs de FranceAgriMer (maíz grano): % de la superficie en cada etapa y por clase de estado. El Excel declara «todos los derechos reservados» mientras data.gouv.fr indica Licence Ouverte 2.0: la licencia se está aclarando con FranceAgriMer.|Weekly field-technician tracking in FranceAgriMer\'s Céré\'Obs programme (grain maize): % of area at each stage and by condition class. The workbook says "all rights reserved" while data.gouv.fr lists Licence Ouverte 2.0: the licence is being clarified with FranceAgriMer.|Suivi hebdomadaire des techniciens de terrain du programme Céré\'Obs de FranceAgriMer (maïs grain) : % de la surface à chaque étape et par classe d\'état. Le classeur indique « tous droits réservés » alors que data.gouv.fr indique la Licence Ouverte 2.0 : la licence est en cours de clarification avec FranceAgriMer.|Monitoraggio settimanale dei tecnici di campo nel programma Céré\'Obs di FranceAgriMer (mais da granella): % della superficie in ogni fase e per classe di stato. Il file dichiara «tutti i diritti riservati» mentre data.gouv.fr indica la Licence Ouverte 2.0: la licenza è in corso di chiarimento con FranceAgriMer.'
  };
  var CROPS = { cereals: 'Cereales|Cereals|Céréales|Cereali', wheat_winter: 'Trigo de invierno|Winter wheat|Blé d\'hiver|Frumento invernale', wheat_spring: 'Trigo de primavera|Spring wheat|Blé de printemps|Frumento primaverile', rye: 'Centeno|Rye|Seigle|Segale', triticale: 'Triticale|Triticale|Triticale|Triticale',
    barley_winter: 'Cebada de invierno|Winter barley|Orge d\'hiver|Orzo invernale', barley_spring: 'Cebada de primavera|Spring barley|Orge de printemps|Orzo primaverile', oats_other: 'Avena y otros cereales|Oats and other cereals|Avoine et autres céréales|Avena e altri cereali', oats: 'Avena|Oats|Avoine|Avena', cereal_mix: 'Mezcla de cereales|Cereal mix|Mélange de céréales|Miscuglio di cereali', other_cereals: 'Otros cereales|Other cereals|Autres céréales|Altri cereali',
    maize_grain: 'Maíz grano|Grain maize|Maïs grain|Mais da granella', rapeseed: 'Colza|Rapeseed|Colza|Colza', pulses: 'Leguminosas grano|Pulses|Légumineuses|Leguminose', peas: 'Guisantes|Peas|Pois|Piselli', beans: 'Habas|Field beans|Fèves|Fave', lupins: 'Altramuces|Lupins|Lupins|Lupini', potato_seed: 'Patata de siembra|Seed potatoes|Pommes de terre de plantation|Patate da semina', potato_starch: 'Patata para almidón|Starch potatoes|Pommes de terre féculières|Patate da fecola', potato_food: 'Patata de consumo|Ware potatoes|Pommes de terre de consommation|Patate da consumo', sugarbeet: 'Remolacha azucarera|Sugar beet|Betterave sucrière|Barbabietola da zucchero', fodder_beet: 'Remolacha forrajera|Fodder beet|Betterave fourragère|Barbabietola da foraggio',
    A042170: 'Trigo (total)|Wheat (total)|Blé (total)|Frumento (totale)', A042171: 'Trigo de invierno|Winter wheat|Blé d\'hiver|Frumento invernale', A042172: 'Trigo de primavera|Spring wheat|Blé de printemps|Frumento primaverile', A042160: 'Cebada (total)|Barley (total)|Orge (total)|Orzo (totale)', A042161: 'Cebada de invierno|Winter barley|Orge d\'hiver|Orzo invernale', A042162: 'Cebada de primavera|Spring barley|Orge de printemps|Orzo primaverile',
    A042169: 'Centeno|Rye|Seigle|Segale', A042164: 'Avena|Oats|Avoine|Avena', A042173: 'Triticale|Triticale|Triticale|Triticale', A042167: 'Maíz grano|Grain maize|Maïs grain|Mais da granella', A042168: 'Maíz forrajero|Silage maize|Maïs fourrage|Mais da foraggio', A042166: 'Maíz «corn cob mix»|Corn cob mix|Corn cob mix|Corn cob mix', A042191: 'Alubias pintas|Brown beans|Haricots bruns|Fagioli bruni', A042180: 'Colza y nabina|Rapeseed|Colza et navette|Colza e ravizzone',
    A042187: 'Lino textil|Fibre flax|Lin textile|Lino da fibra', A042177: 'Achicoria|Chicory|Chicorée|Cicoria', A042178: 'Cáñamo|Hemp|Chanvre|Canapa', A042355: 'Patata (total)|Potatoes (total)|Pommes de terre (total)|Patate (totale)', A042356: 'Patata de consumo|Ware potatoes|Pommes de terre de consommation|Patate da consumo', A042359: 'Patata de siembra|Seed potatoes|Pommes de terre de plantation|Patate da semina', A042362: 'Patata para almidón|Starch potatoes|Pommes de terre féculières|Patate da fecola',
    A042194: 'Remolacha azucarera|Sugar beet|Betterave sucrière|Barbabietola da zucchero', A042320: 'Cebolla de siembra (total)|Onions, sown (total)|Oignons de semis (total)|Cipolle da semina (totale)', A050907: 'Cebolla amarilla|Yellow onions|Oignons jaunes|Cipolle gialle', A050908: 'Cebolla roja|Red onions|Oignons rouges|Cipolle rosse', A049495: 'Cebolla de plantación (2.º año)|Planting onions (2nd year)|Oignons à planter (2e année)|Cipolle da trapianto (2º anno)' };
  var SPN = { cattle: 'Bovino (total)|Cattle (total)|Bovins (total)|Bovini (totale)', adult_cattle: 'Bovino adulto|Adult cattle|Gros bovins|Bovini adulti', calves: 'Terneros|Calves|Veaux|Vitelli', cows: 'Vacas|Cows|Vaches|Vacche', young_bulls: 'Toretes|Young bulls|Jeunes taureaux|Giovani tori', heifers: 'Novillas|Heifers|Génisses|Giovenche', bulls: 'Toros|Bulls|Taureaux|Tori', pigs: 'Porcino (total)|Pigs (total)|Porcins (total)|Suini (totale)', fatteners: 'Cerdos de cebo|Fattening pigs|Porcs à l\'engrais|Suini da ingrasso', sows: 'Cerdas|Sows|Truies|Scrofe', sheep: 'Ovino|Sheep|Ovins|Ovini', goats: 'Caprino|Goats|Caprins|Caprini', chickens: 'Gallinas y pollos|Chickens|Poulets|Polli' };
  var FM = { farms: 'Explotaciones|Farms|Exploitations|Aziende', agri_land: 'Superficie agraria (ha)|Agricultural land (ha)|Surface agricole (ha)|Superficie agricola (ha)', arable: 'Tierras de cultivo (ha)|Arable land (ha)|Terres arables (ha)|Seminativi (ha)', horticulture: 'Horticultura al aire libre (ha)|Open-field horticulture (ha)|Horticulture de plein champ (ha)|Orticoltura in pieno campo (ha)', greenhouse: 'Invernaderos (ha)|Greenhouse horticulture (ha)|Serres (ha)|Serre (ha)', grass: 'Pastos y forrajes verdes (ha)|Grass and green fodder (ha)|Herbages et fourrages verts (ha)|Prati e foraggere verdi (ha)',
    cattle: 'Bovino (cabezas)|Cattle (head)|Bovins (têtes)|Bovini (capi)', dairy_cows: 'Vacas lecheras (cabezas)|Dairy cows (head)|Vaches laitières (têtes)|Vacche da latte (capi)', beef_cows: 'Vacas nodrizas (cabezas)|Suckler cows (head)|Vaches allaitantes (têtes)|Vacche nutrici (capi)', sheep: 'Ovino (cabezas)|Sheep (head)|Ovins (têtes)|Ovini (capi)', goats: 'Caprino (cabezas)|Goats (head)|Caprins (têtes)|Caprini (capi)', pigs: 'Porcino (cabezas)|Pigs (head)|Porcins (têtes)|Suini (capi)',
    chickens: 'Gallinas y pollos (cabezas)|Chickens (head)|Poulets (têtes)|Polli (capi)', laying_hens: 'Gallinas ponedoras (cabezas)|Laying hens (head)|Poules pondeuses (têtes)|Galline ovaiole (capi)', broilers: 'Pollos de carne (cabezas)|Broilers (head)|Poulets de chair (têtes)|Polli da carne (capi)', farms_cattle: 'Explotaciones con bovino|Farms with cattle|Exploitations avec bovins|Aziende con bovini', farms_pigs: 'Explotaciones con porcino|Farms with pigs|Exploitations avec porcins|Aziende con suini', farms_chickens: 'Explotaciones con aves|Farms with chickens|Exploitations avec poulets|Aziende con polli' };
  var SUBN = { total: 'Total subvenciones|Total subsidies|Total subventions|Totale sovvenzioni', direct: 'Pagos directos|Direct payments|Paiements directs|Pagamenti diretti', basic: 'Ayuda básica y ecológica|Basic and green support|Aide de base et verte|Sostegno di base e verde', eco_total: 'Ecorregímenes (total)|Eco-schemes (total)|Eco-régimes (total)|Eco-schemi (totale)', eco_biodiv: 'Biodiversidad y sostenibilidad|Biodiversity and sustainability|Biodiversité et durabilité|Biodiversità e sostenibilità', eco_grass: 'Pastos respetuosos con el clima|Climate-friendly grass|Herbages respectueux du climat|Prati rispettosi del clima', eco_mowing: 'Siega extensiva|Extensive mowing|Fauche extensive|Sfalcio estensivo', eco_varied: 'Producción vegetal variada|Varied plant production|Production végétale variée|Produzione vegetale varia', eco_organic: 'Superficie ecológica|Organic area|Surface bio|Superficie biologica', other_direct: 'Otros pagos directos|Other direct payments|Autres paiements directs|Altri pagamenti diretti', coupled: 'Ayudas asociadas|Coupled support|Aides couplées|Sostegno accoppiato', young: 'Jóvenes agricultores|Young farmers|Jeunes agriculteurs|Giovani agricoltori', other_total: 'Otros regímenes (total)|Other schemes (total)|Autres régimes (total)|Altri regimi (totale)', natura2000: 'Natura 2000|Natura 2000|Natura 2000|Natura 2000', organic_invest: 'Ecológico: ayudas e inversiones|Organic area aid and investments|Bio : aides et investissements|Biologico: aiuti e investimenti' };
  var CAPN = { basic: 'Ayuda básica a la renta (grundbetaling)|Basic income support (grundbetaling)|Aide de base au revenu (grundbetaling)|Sostegno di base al reddito (grundbetaling)', island: 'Ayuda a islas|Island support|Aide aux îles|Sostegno alle isole', starch_potato: 'Patata para almidón (ayuda asociada)|Starch potatoes (coupled)|Pommes de terre féculières (couplée)|Patate da fecola (accoppiato)', bio_area: 'Ecorrégimen: superficie ecológica|Eco-scheme: organic area|Éco-régime : surface bio|Eco-schema: superficie biologica', bio_extensive: 'Ecorrégimen: siega extensiva|Eco-scheme: extensive mowing|Éco-régime : fauche extensive|Eco-schema: sfalcio estensivo', bio_grass: 'Ecorrégimen: pastos|Eco-scheme: grass|Éco-régime : herbages|Eco-schema: prati', bio_varied: 'Ecorrégimen: producción vegetal variada|Eco-scheme: varied plant production|Éco-régime : production végétale variée|Eco-schema: produzione vegetale varia',
    min_area: 'Superficie mínima por explotación|Minimum area per holding|Surface minimale par exploitation|Superficie minima per azienda', min_parcel: 'Parcela mínima|Minimum parcel|Parcelle minimale|Particella minima', active_farmer: 'Agricultor activo: umbral de superficie|Active farmer: area threshold|Agriculteur actif : seuil de surface|Agricoltore attivo: soglia di superficie' };
  function tx(k, lang) { var v = X[k]; if (!v) return k; var a = v.split('|'); return a[LI[lang]] || a[0]; }
  function pk(m, k, lang) { var v = m[k]; if (!v) return k; var a = v.split('|'); return a[LI[lang]] || a[0]; }
  function esc(s) { return String(s == null ? '' : s).replace(/[&<>"]/g, function (c) { return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]; }); }
  function nf(v, d, lang) { try { return v.toLocaleString(lang, { minimumFractionDigits: d, maximumFractionDigits: d }); } catch (e) { return v.toFixed(d); } }
  function pc(v, lang) { if (v == null || !isFinite(v)) return '–'; if (Math.abs(v) < 0.05) v = 0; return (v > 0 ? '+' : v < 0 ? '−' : '') + nf(Math.abs(v), 1, lang) + ' %'; }
  function dec(v) { return Math.abs(v) >= 1000 ? 0 : Math.abs(v) >= 100 ? 1 : 2; }
  function get(f) { if (!ML[f]) ML[f] = fetch(f).then(function (r) { if (!r.ok) throw new Error(r.status); return r.json(); }); return ML[f]; }
  function at(a, p) { if (!a) return null; for (var i = a.length - 1; i >= 0; i--) { if (a[i][0] === p) return a[i][1]; if (a[i][0] < p) break; } return null; }
  function lastP(a) { return a && a.length ? a[a.length - 1] : null; }
  function ts(p) { var s = String(p), m; if ((m = /^(\d{4})-W(\d{2})$/.exec(s))) return Date.UTC(+m[1], 0, 1) + (+m[2] - 1) * 7 * 864e5; if ((m = /^(\d{4})-Q(\d)$/.exec(s))) return Date.UTC(+m[1], (+m[2] - 1) * 3, 1); return Date.UTC(+s.slice(0, 4), s.length > 4 ? +s.slice(5, 7) - 1 : 0, 1); }
  function pts(a, from) { var r = []; (a || []).forEach(function (p) { if (!from || p[0] >= from) r.push({ x: ts(p[0]), y: p[1], l: String(p[0]) }); }); return r; }
  var PAL = ['#2f6b4a', '#b7791f', '#2b5f9e', '#a23b3b', '#6b4fa1', '#3a8f8f', '#8a8a8a', '#c2670b', '#5a7d2a'];
  function chart(series, o) { var C = window.DehesaChart; if (!C) return ''; series = series.map(function (x, i) { return { name: x.name, pts: x.pts, color: x.color || PAL[i % PAL.length], dash: x.dash }; }); return C.render({ series: series, xMode: o.xMode === 'num' ? undefined : 'time', yTitle: o.unit, aria: o.aria, noLegend: series.length < 2, yMin: o.yMin, yMax: o.yMax, vFmt: o.vFmt, yFmt: function (v) { return nf(v, Math.abs(v) >= 100 ? 0 : Math.abs(v) >= 10 ? 1 : 2, o.lang); }, xFmt: o.xFmt }); }
  function cite(id, period) { var Q = window.DICite; if (!Q) return ''; var c = Q.html(id, { period: String(period || '') }); return c ? '<div class="pp-cites">' + c + '</div>' : ''; }
  function sel(k, label, opts, cur) { return '<label>' + esc(label) + '<br><select data-k="' + k + '">' + opts.map(function (o) { return '<option value="' + esc(o[0]) + '"' + (o[0] === cur ? ' selected' : '') + '>' + esc(o[1]) + '</option>'; }).join('') + '</select></label>'; }
  function tiles(a) { return '<div class="de-tiles">' + a.map(function (x) { return '<div class="de-tile"><div class="de-tl">' + esc(x[0]) + '</div><div class="de-tv">' + x[1] + '</div>' + (x[2] ? '<div class="de-tl">' + x[2] + '</div>' : '') + '</div>'; }).join('') + '</div>'; }
  function tbl(head, rows, nr) { return '<div class="de-sc"><table class="de-t" data-no-cards><thead><tr>' + head.map(function (h, i) { return '<th scope="col"' + (i && !nr ? ' class="r"' : '') + '>' + esc(h) + '</th>'; }).join('') + '</tr></thead><tbody>' + rows.map(function (r) { return '<tr>' + r.map(function (c, i) { return (i ? '<td class="r">' : '<td>') + c + '</td>'; }).join('') + '</tr>'; }).join('') + '</tbody></table></div>'; }
  function note(s) { return '<p class="di-movers-hint">' + esc(s) + '</p>'; }
  function avg5(a, y) { var s = 0, n = 0, i; for (i = 1; i <= 5; i++) { var v = at(a, String(+y - i)); if (v != null) { s += v; n++; } } return n >= 3 ? s / n : null; }
  function delta(v, b) { return v != null && b ? (v / b - 1) * 100 : null; }
  /* --------- cosecha por region (DK y NL): misma maquina, distintos ficheros --------- */
  function harvest(body, lang, cfg) {
    var D = cfg.d, H = cfg.h, st = cfg.st, keys = Object.keys(H.data).filter(function (c) { var n = H.data[c][cfg.nat]; return n && n.prod; });
    keys.sort(function (a, b) { return pk(CROPS, a, lang).localeCompare(pk(CROPS, b, lang), lang); });
    if (!st.crop || keys.indexOf(st.crop) < 0) st.crop = keys.indexOf(cfg.def) >= 0 ? cfg.def : keys[0];
    var cd = H.data[st.crop], nat = cd[cfg.nat], m = st.m || 'yield', unit = m === 'yield' ? tx('th', lang) : m === 'area' ? tx('ha', lang) : cfg.prodUnit(lang), ser = nat[m] || [], lp = lastP(ser);
    var h = '<div class="de-ctl">' + sel('crop', tx('crop', lang), keys.map(function (c) { return [c, pk(CROPS, c, lang)]; }), st.crop) + sel('m', tx('meas', lang), [['yield', tx('yld', lang)], ['prod', tx('prod', lang)], ['area', tx('area', lang)]], m) + '</div>';
    if (!lp) { body.innerHTML = h + note(tx('none', lang)); return; }
    var y = lp[0], pv = at(ser, String(+y - 1)), a5 = avg5(ser, y), fm = function (v) { return v == null ? '–' : nf(v, m === 'yield' ? 2 : cfg.dec(m, v), lang) + ' ' + unit; };
    h += tiles([[tx('last', lang) + ' (' + y + (cfg.prov && cfg.prov.indexOf(+y) >= 0 ? ', ' + tx('prov', lang).toLowerCase() : '') + ')', fm(lp[1])], [tx('vsPrev', lang), pc(delta(lp[1], pv), lang)], [tx('vs5', lang), pc(delta(lp[1], a5), lang)]]);
    h += chart([{ name: pk(CROPS, st.crop, lang), pts: pts(ser) }], { unit: unit, lang: lang, yMin: m === 'yield' ? undefined : 0, aria: pk(CROPS, st.crop, lang) + ' – ' + tx(m === 'yield' ? 'yld' : m, lang) });
    var ty = y, cntR = function (yy) { var n = 0; cfg.order.forEach(function (g) { var s = cd[g] && cd[g][m]; if (s && at(s, yy) != null) n++; }); return n; };
    while (+ty > 1990 && cntR(ty) < Math.min(5, cfg.order.length)) ty = String(+ty - 1);
    var rows = [];
    cfg.order.forEach(function (g) { var s = cd[g] && cd[g][m]; if (!s) return; var v = at(s, ty); if (v == null) return; rows.push([(cfg.indent[g] ? '&nbsp;&nbsp;' : '') + esc(cfg.rn[g] || g), esc(nf(v, m === 'yield' ? 2 : cfg.dec(m, v), lang)), pc(delta(v, at(s, String(+ty - 1))), lang), pc(delta(v, avg5(s, ty)), lang)]); });
    h += tbl([tx('reg', lang) + ' (' + ty + ', ' + unit + ')', ty, tx('vsPrev', lang), tx('vs5', lang)], rows);
    if (cfg.brk && H.crops[st.crop] && H.crops[st.crop].classBreak) h += note(tx('brk', lang));
    h += note(cfg.note(lang)) + cfg.cite(y) + '<p class="di-movers-hint">' + esc(tx('upd', lang)) + ': ' + esc(cfg.until) + '</p>';
    body.innerHTML = h;
  }
  /* --------- Dinamarca --------- */
  var DKF = 'data/denmark-depth.json';
  function dkHarvest(body, lang, st) {
    return get(DKF).then(function (D) {
      var H = D.harvest, order = [], rn = {}, ind = {}; Object.keys(H.regions).forEach(function (k) { if (H.regions[k].kind === 'nation') { order.unshift(k); rn[k] = lang === 'es' ? 'Dinamarca' : lang === 'fr' ? 'Danemark' : lang === 'it' ? 'Danimarca' : 'Denmark'; } });
      Object.keys(H.regions).forEach(function (k) { var r = H.regions[k]; if (r.kind === 'region') { order.push(k); rn[k] = r.name.replace('Region ', ''); Object.keys(H.regions).forEach(function (j) { if (H.regions[j].parent === k) { order.push(j); rn[j] = H.regions[j].name.replace(/^Provinces? /, ''); ind[j] = 1; } }); } });
      harvest(body, lang, { d: D, h: H, st: st, nat: '000', def: 'wheat_winter', order: order, rn: rn, indent: ind, brk: true, until: String(H.breakYear),
        prodUnit: function (l) { return tx('kt', l); }, dec: function (m, v) { return m === 'area' ? 0 : v >= 100 ? 0 : 1; }, note: function (l) { return tx('yNote', l); }, cite: function (y) { return cite('dst_dk', y); } });
    });
  }
  function dkLive(body, lang, st) {
    return get(DKF).then(function (D) {
      var v = st.v || 'sl', h = '<div class="de-ctl">' + sel('v', tx('view', lang), [['sl', tx('sl', lang)], ['milk', tx('milk', lang)], ['herd', tx('herd', lang)], ['sub', tx('sub', lang)]], v);
      if (v === 'sl') {
        var sp = st.sp || 'pigs', cats = Object.keys(D.slaughter[sp]), ct = cats.indexOf(st.cat) >= 0 ? st.cat : cats[0], me = st.me || 'heads';
        h += sel('sp', tx('sp', lang), [['pigs', pk(SPN, 'pigs', lang).replace(/ \(.*/, '')], ['cattle', pk(SPN, 'cattle', lang).replace(/ \(.*/, '')]], sp) + sel('cat', tx('cat', lang), cats.map(function (c) { return [c, pk(SPN, c, lang)]; }), ct) + sel('me', tx('meas', lang), [['heads', tx('heads', lang)], ['prod', tx('wt', lang)], ['price', tx('price', lang)]], me) + '</div>';
        var s = D.slaughter[sp][ct][me], lp = lastP(s);
        if (!lp) h += note(tx('none', lang)); else { var pm = (+lp[0].slice(0, 4) - 1) + lp[0].slice(4);
          h += tiles([[tx('month', lang) + ' (' + lp[0] + ')', nf(lp[1], dec(lp[1]), lang)], [tx('sameM', lang), pc(delta(lp[1], at(s, pm)), lang)]]) + chart([{ name: pk(SPN, ct, lang), pts: pts(s, '2015') }], { unit: tx(me === 'heads' ? 'heads' : me === 'prod' ? 'wt' : 'price', lang), lang: lang, yMin: me === 'price' ? undefined : 0, aria: pk(SPN, ct, lang) }); }
        h += note(tx('slNote', lang));
      } else if (v === 'milk') {
        var ms = D.milk.milk_total; h += '</div>' + chart([{ name: tx('mkTot', lang), pts: pts(ms, '2015') }], { unit: tx('mkTot', lang), lang: lang, yMin: 0, aria: tx('mkTot', lang) });
      } else if (v === 'herd') {
        h += '</div>' + chart([{ name: tx('pigsT', lang), pts: pts(D.herd.pigs.total, '2010') }], { unit: tx('pigsT', lang), lang: lang, yMin: 0, aria: tx('pigsT', lang) }) + chart([{ name: tx('cattT', lang), pts: pts(D.herd.cattle.total['000'], '2010') }], { unit: tx('cattT', lang), lang: lang, yMin: 0, aria: tx('cattT', lang) });
      } else {
        h += '</div>'; var S = D.subsidies, ks = Object.keys(S.data), yrs = (S.data.total || []).slice(-4).map(function (p) { return p[0]; });
        h += tbl([tx('sub', lang) + ' (' + tx('mDKK', lang) + ')'].concat(yrs), ks.map(function (k) { return [esc(pk(SUBN, k, lang))].concat(yrs.map(function (y) { var x = at(S.data[k], y); return x == null ? '–' : esc(nf(x, 1, lang)); })); })) + note(tx('subNote', lang));
      }
      h += cite('dst_dk', '') + '<p class="di-movers-hint">' + esc(tx('checked', lang)) + ': ' + esc((D.generatedAt || '').slice(0, 10)) + '</p>';
      body.innerHTML = h;
    });
  }
  function dkCap(body, lang) {
    return Promise.all([get('data/cap/dk/amounts.json'), get('data/cap/dk/watch.json')]).then(function (r) {
      var A = r[0], W = r[1], h = '';
      if (W.reviewNeeded && W.reviewNeeded.length) h += '<p class="di-movers-hint" role="alert"><b>' + esc(tx('capWarn', lang)) + '</b></p>';
      var rows = [];
      A.schemes.forEach(function (s) { s.items.forEach(function (it) { rows.push([esc(pk(CAPN, s.id, lang)) + (s.items.length > 1 ? ' – ' + esc(it.label) : ''), esc(nf(it.amount, 2, lang) + ' ' + it.unit + (it.max ? ' (' + tx('max', lang) + ')' : '')), esc(s.doc + ' ' + s.par)]); }); });
      h += '<h4>' + esc(tx('capT', lang)) + '</h4>' + tbl([tx('scheme', lang), tx('amt', lang), tx('par', lang)], rows);
      h += '<h4>' + esc(tx('capTh', lang)) + '</h4>' + tbl([tx('scheme', lang), tx('amt', lang), tx('par', lang)], A.thresholds.map(function (t) { return [esc(pk(CAPN, t.id, lang)), esc(nf(t.value, 2, lang).replace(/[.,]00$/, '') + ' ' + t.unit + (t.alt ? ' / ' + nf(t.alt.value, 0, lang) + ' ' + t.alt.unit : '')), esc(t.doc + ' ' + t.par)]; }));
      h += '<h4>' + esc(tx('capDoc', lang)) + '</h4><ul class="di-movers-hint">' + A.documents.map(function (d) { return '<li><a href="' + esc(d.url) + '" rel="noopener">BEK ' + d.number + '</a> – ' + esc(d.title) + ' (' + esc(tx('ver', lang)) + ' ' + esc(d.versionDate) + '; ' + d.amendments.length + ' ' + esc(tx('amend', lang)) + ')</li>'; }).join('') + '</ul>';
      h += note(tx('capNote', lang) + ': ' + A.verifiedAt + '.') + cite('retsinformation', '');
      body.innerHTML = h;
    });
  }
  /* --------- Paises Bajos --------- */
  var NLF = 'data/netherlands-farm.json', NLM = 'data/netherlands-markets.json';
  function nlCrops(body, lang, st) {
    return get(NLF).then(function (D) {
      var C = D.crops, order = Object.keys(C.regions).sort(function (a, b) { return a === 'NL01' ? -1 : b === 'NL01' ? 1 : (a < b ? -1 : 1); }), ind = {}; order.forEach(function (k) { if (k.slice(0, 2) === 'PV') ind[k] = 1; });
      var rn = {}; Object.keys(C.regions).forEach(function (k) { rn[k] = k === 'NL01' ? { es: 'Países Bajos', en: 'Netherlands', fr: 'Pays-Bas', it: 'Paesi Bassi' }[lang] : C.regions[k].replace(/ \((LD|PV)\)/, ''); });
      harvest(body, lang, { d: D, h: C, st: st, nat: 'NL01', def: 'A042170', order: order, rn: rn, indent: ind, brk: false, prov: C.provisional, until: String(((lastP((C.data.A042170.NL01 || {}).prod) || [''])[0])),
        prodUnit: function (l) { return tx('t', l); }, dec: function () { return 0; }, note: function (l) { return tx('cbsNote', l); }, cite: function (y) { return cite('cbs_nl', y); } });
    });
  }
  function nlFarms(body, lang, st) {
    return get(NLF).then(function (D) {
      var F = D.farms, ks = Object.keys(F.data), m = ks.indexOf(st.m) >= 0 ? st.m : 'dairy_cows', ser = F.data[m], nat = ser.NL01, lp = lastP(nat);
      var h = '<div class="de-ctl">' + sel('m', tx('metric', lang), ks.map(function (k) { return [k, pk(FM, k, lang)]; }), m) + '</div>';
      if (!lp) { body.innerHTML = h + note(tx('none', lang)); return; }
      var y = lp[0], p5 = at(nat, String(+y - 5));
      h += tiles([[pk(FM, m, lang) + ' (' + y + ')', nf(lp[1], 0, lang)], [tx('vsPrev', lang), pc(delta(lp[1], at(nat, String(+y - 1))), lang)], [tx('ch5', lang), pc(delta(lp[1], p5), lang)]]) + chart([{ name: pk(FM, m, lang), pts: pts(nat) }], { unit: pk(FM, m, lang), lang: lang, yMin: 0, aria: pk(FM, m, lang) });
      var rows = Object.keys(ser).filter(function (g) { return g !== 'NL01'; }).sort(function (a, b) { return (at(ser[b], y) || 0) - (at(ser[a], y) || 0); }).map(function (g) { var v = at(ser[g], y); if (v == null) return null; return [esc(F.regions[g].replace(/ \((LD|PV)\)/, '')), esc(nf(v, 0, lang)), pc(delta(v, at(ser[g], String(+y - 1))), lang), pc(delta(v, at(ser[g], String(+y - 5))), lang)]; }).filter(Boolean);
      h += tbl([tx('reg', lang) + ' (' + y + ')', y, tx('vsPrev', lang), tx('ch5', lang)], rows) + note(tx('farmNote', lang)) + cite('cbs_nl', y) + '<p class="di-movers-hint">' + esc(tx('checked', lang)) + ': ' + esc((D.generatedAt || '').slice(0, 10)) + '</p>';
      body.innerHTML = h;
    });
  }
  function nlMarkets(body, lang, st) {
    return Promise.all([get(NLM), get(NLF)]).then(function (r) {
      var M = r[0], F = r[1], v = st.v || 'pig', h = '<div class="de-ctl">' + sel('v', tx('view', lang), [['pig', tx('pig', lang)], ['cattle', tx('cattleP', lang)], ['sl', tx('slW', lang)], ['cbs', tx('cbsSl', lang)], ['idx', tx('pidx', lang)]], v), cs = [], unit = '', cc = null, ser;
      if (v === 'cattle') { var ks = Object.keys(M.cattlePrice.data); cc = ks.indexOf(st.cc) >= 0 ? st.cc : ks[0]; h += sel('cc', tx('cat', lang), ks.map(function (k) { return [k, M.cattlePrice.labels[k] + ' (' + k.replace('_', ' ') + ')']; }), cc); }
      if (v === 'sl') { h += sel('me', tx('meas', lang), [['heads', tx('slW', lang)], ['weight', 'kg'], ['lean', tx('lean', lang)]], st.me || 'heads'); }
      if (v === 'cbs') { var sk = Object.keys(F.slaughter.data), sc = sk.indexOf(st.sc) >= 0 ? st.sc : 'pigs'; h += sel('sc', tx('sp', lang), sk.map(function (k) { return [k, pk(SPN, k, lang)]; }), sc); }
      h += '</div>';
      if (v === 'pig') { ser = M.pigPrice.pigs; unit = tx('pig', lang); } else if (v === 'cattle') { ser = M.cattlePrice.data[cc]; unit = tx('cattleP', lang); } else if (v === 'sl') { ser = M.pigSlaughter[st.me || 'heads']; unit = (st.me || 'heads') === 'heads' ? tx('slW', lang) : (st.me === 'weight' ? 'kg' : tx('lean', lang)); }
      else if (v === 'cbs') { ser = F.slaughter.data[sc || 'pigs'].heads; unit = tx('heads', lang); } else ser = null;
      if (ser) {
        var lp = lastP(ser), wk = v !== 'cbs', ly = lp ? (+lp[0].slice(0, 4) - 1) + lp[0].slice(4) : '';
        h += tiles([[(wk ? tx('wk', lang) : tx('month', lang)) + ' ' + lp[0], nf(lp[1], v === 'pig' || v === 'cattle' ? 2 : dec(lp[1]), lang)], [wk ? tx('vsW', lang) : tx('sameM', lang), pc(delta(lp[1], wk ? (ser.length > 1 ? ser[ser.length - 2][1] : null) : at(ser, ly)), lang)], [wk ? tx('vsY', lang) : '', wk ? pc(delta(lp[1], at(ser, ly)), lang) : '']].filter(function (t) { return t[0]; })) +
          chart([{ name: unit, pts: pts(ser, wk ? String(+lp[0].slice(0, 4) - 3) : '2015') }], { unit: unit, lang: lang, yMin: v === 'sl' && (st.me || 'heads') !== 'heads' ? undefined : 0, aria: unit });
        if (v === 'cattle' && M.cattlePrice.atypical && M.cattlePrice.atypical[cc]) h += note(tx('atyp', lang) + ': ' + M.cattlePrice.atypical[cc].join(', ') + '.');
      } else {
        var P = F.priceIndex, sr = Object.keys(P.data).map(function (k) { return { name: P.labels[k], pts: pts(P.data[k]) }; });
        h += chart(sr.slice(0, 9), { unit: tx('pidx', lang), lang: lang, aria: tx('pidx', lang) });
      }
      h += note(v === 'cbs' || v === 'idx' ? tx('cbsNote', lang) : tx('rvoNote', lang)) + cite(v === 'cbs' || v === 'idx' ? 'cbs_nl' : 'rvo', '') + '<p class="di-movers-hint">' + esc(tx('checked', lang)) + ': ' + esc((M.generatedAt || '').slice(0, 10)) + '</p>';
      body.innerHTML = h;
    });
  }
  /* --------- Francia --------- */
  var LV = [null, 'vigilance', 'alerte', 'alerte_renforcee', 'crise'];
  function frWater(body, lang, st) {
    return get('data/france-vigieau.json').then(function (V) {
      var f = st.f || 'all', cnt = V.counts, tl = [[tx('lv4', lang), cnt.crise], [tx('lv3', lang), cnt.alerte_renforcee], [tx('lv2', lang), cnt.alerte], [tx('lv1', lang), cnt.vigilance], [tx('lv0', lang), cnt.none]];
      var h = tiles(tl.map(function (t) { return [t[0], String(t[1])]; })), opts = [['all', tx('all', lang)]].concat([4, 3, 2, 1, 0].map(function (i) { return [String(i), tx('lv' + i, lang)]; }));
      h += '<div class="de-ctl">' + sel('f', tx('worst', lang), opts, f) + '</div>';
      var rank = function (l) { return LV.indexOf(l); }, nm = function (l) { return tx('lv' + rank(l), lang); };
      var rows = V.departments.filter(function (d) { return f === 'all' || String(rank(d.level)) === f; }).sort(function (a, b) { return rank(b.level) - rank(a.level) || (a.code < b.code ? -1 : 1); }).map(function (d) { return [esc(d.code + ' ' + d.name), esc(nm(d.level)), esc(nm(d.sup)), esc(nm(d.sou)), esc(nm(d.aep))]; });
      h += tbl([tx('dep', lang), tx('worst', lang), tx('sup', lang), tx('sou', lang), tx('aep', lang)], rows);
      var hs = V.history || []; h += '<h4>' + esc(tx('hist', lang)) + '</h4>';
      if (hs.length > 1) h += chart([{ name: tx('lv4', lang), pts: hs.map(function (x) { return { x: ts(x.date), y: x.counts.crise, l: x.date }; }) }], { unit: tx('lv4', lang), lang: lang, yMin: 0, aria: tx('hist', lang), xFmt: function (x) { return new Date(x).toISOString().slice(0, 10); } });
      h += note(tx('histNote', lang) + ' (' + hs[0].date + ').') + note(tx('wNote', lang)) + cite('vigieau', '') + '<p class="di-movers-hint">' + esc(tx('upd', lang)) + ': ' + esc(((V.source.asOf || V.generatedAt) || '').slice(0, 10)) + '</p>';
      body.innerHTML = h;
    });
  }
  var STG = [['sowing', 'sw'], ['emergence', 'em'], ['leaves', 'lf'], ['flowering', 'fl'], ['moisture50', 'mo'], ['harvest', 'hv']];
  function frMaize(body, lang, st) {
    return get('data/france-cereobs.json').then(function (C) {
      var reg = st.r && C.regions[st.r] ? st.r : 'FR', rows = reg === 'FR' ? C.national : C.regions[reg], yrs = {}; rows.forEach(function (r) { yrs[r[0].slice(0, 4)] = 1; });
      var ys = Object.keys(yrs).sort(), y = ys.indexOf(st.y) >= 0 ? st.y : ys[ys.length - 1], cy = ys.indexOf(st.cy) >= 0 && st.cy !== y ? st.cy : (ys.length > 1 ? ys[ys.indexOf(y) > 0 ? ys.indexOf(y) - 1 : 1] : y);
      var ro = [['FR', tx('nat', lang)]].concat(Object.keys(C.regions).sort().map(function (k) { return [k, k]; })), st2 = st.s || 'flowering', sx = STG.map(function (s) { return [s[0], tx(s[1], lang)]; });
      var h = '<div class="de-ctl">' + sel('r', tx('reg', lang), ro, reg) + sel('y', tx('season', lang), ys.map(function (v) { return [v, v]; }), y) + sel('cy', tx('compare', lang), ys.map(function (v) { return [v, v]; }), cy) + sel('s', tx('st', lang), sx, st2) + '</div>';
      var ix = C.fields.indexOf(st2) + 1, wkn = function (p) { return +p.slice(6); }, line = function (yy) { return rows.filter(function (r) { return r[0].slice(0, 4) === yy && r[ix] != null; }).map(function (r) { return { x: wkn(r[0]), y: r[ix], l: r[0] }; }); };
      h += chart([{ name: y, pts: line(y) }, { name: cy, pts: line(cy), dash: true }], { unit: tx('pcA', lang) + ' – ' + tx('wkN', lang), lang: lang, xMode: 'num', yMin: 0, yMax: 100, aria: tx(STG.filter(function (s) { return s[0] === st2; })[0][1], lang) });
      var cur = rows.filter(function (r) { return r[0].slice(0, 4) === y && r[C.fields.indexOf('c1') + 1] != null; }), l = cur.length ? cur[cur.length - 1] : null;
      if (l) { var c0 = C.fields.indexOf('c1') + 1, same = rows.filter(function (r) { return r[0] === cy + l[0].slice(4); })[0], sm = function (r) { return r ? [r[c0] + r[c0 + 1], r[c0 + 2], r[c0 + 3] + r[c0 + 4]] : [null, null, null]; }, a = sm(l), b = sm(same);
        h += '<h4>' + esc(tx('cond', lang)) + ' – ' + esc(l[0]) + '</h4>' + tbl([tx('cond', lang), y, cy], [[tx('c12', lang), nf(a[0], 1, lang) + ' %', b[0] == null ? '–' : nf(b[0], 1, lang) + ' %'], [tx('c3', lang), nf(a[1], 1, lang) + ' %', b[1] == null ? '–' : nf(b[1], 1, lang) + ' %'], [tx('c45', lang), nf(a[2], 1, lang) + ' %', b[2] == null ? '–' : nf(b[2], 1, lang) + ' %']].map(function (r) { return r.map(esc); })); }
      h += note(tx('mNote', lang)) + cite('franceagrimer', '') + '<p class="di-movers-hint">' + esc(tx('upd', lang)) + ': ' + esc(C.source.dataUntil || '') + '</p>';
      body.innerHTML = h;
    });
  }
  var MODS = { 'dk-harvest': dkHarvest, 'dk-live': dkLive, 'dk-cap': dkCap, 'nl-crops': nlCrops, 'nl-farms': nlFarms, 'nl-markets': nlMarkets, 'fr-water': frWater, 'fr-maize': frMaize };
  function mount(body, mod, lang) {
    lang = LI[lang] != null ? lang : 'es'; var st = {}, fn = MODS[mod]; if (!fn) return;
    function draw() { return fn(body, lang, st); }
    body.innerHTML = '<p class="di-movers-hint">' + esc(tx('loading', lang)) + '</p>';
    body.addEventListener('change', function (e) { var k = e.target && e.target.getAttribute && e.target.getAttribute('data-k'); if (!k) return; st[k] = e.target.value; if (k === 'sp') st.cat = null; var pr = draw(); if (pr && pr.then) pr.then(function () { var n = body.querySelector('select[data-k="' + k + '"]'); if (n) n.focus(); }); });
    var p = draw(); if (p && p.catch) p.catch(function () { body.innerHTML = '<p class="di-movers-hint">' + esc(tx('err', lang)) + '</p>'; });
  }
  window.EUDepth = { mount: mount };
})();
