/* Dehesa Index — Sequía en Europa (EDO, Combined Drought Indicator, JRC / Copernicus EMS). ES5.
   Lee data/eu-drought.json: por país y para la UE-27, % de la superficie en cada clase del CDI cada diez días. Es superficie total del país, no solo tierra cultivada. */
(function () {
  'use strict';
  var D = null, SEL = 'EU27', DN = {};
  var LI = { es: 0, en: 1, fr: 2, it: 3 };
  var T = {
    es: { h: 'Sequía en Europa', sub: 'Porcentaje de la superficie de cada país en situación de sequía agrícola según el Indicador Combinado de Sequía (CDI) del Observatorio Europeo de la Sequía (JRC). Se actualiza cada diez días.', dec: 'Década del', cls: ['Vigilancia', 'Aviso', 'Alerta', 'Recuperación', 'Recup. temporal de humedad', 'Recup. temporal de vegetación'], cd: ['Déficit de precipitación', 'Déficit de humedad del suelo tras la falta de lluvia', 'Estrés de la vegetación tras falta de lluvia o humedad', 'Vuelta a condiciones normales', 'Humedad del suelo recuperada, vegetación aún afectada', 'Vegetación recuperada, humedad aún baja'],
      ctry: 'País', drought: 'En sequía (vigilancia, aviso o alerta)', ly: 'Misma década, año anterior', pts: 'puntos', hist: 'Evolución en los últimos años', histAlt: '{n}: superficie en sequía de {a} ({x} %) a {b} ({y} %)', now: 'Superficie en sequía', alert: 'En alerta', pick: 'Pulsa un país para ver su evolución.', eu: 'Unión Europea (27)',
      note: 'Cada clase se calcula como porcentaje de la superficie con dato, ponderado por la latitud. «En sequía» suma vigilancia, aviso y alerta. Datos de la última decada pueden revisarse (los ficheros provisionales se sustituyen por los finales).', src: 'Fuente: European Drought Observatory (EDO), Combined Drought Indicator © Comisión Europea, JRC (CC BY 4.0). Agregado por país por Dehesa Index.' },
    en: { h: 'Drought in Europe', sub: 'Share of each country’s area in agricultural drought according to the Combined Drought Indicator (CDI) of the European Drought Observatory (JRC). Updated every ten days.', dec: 'Ten-day period of', cls: ['Watch', 'Warning', 'Alert', 'Recovery', 'Temporary soil-moisture recovery', 'Temporary vegetation recovery'], cd: ['Precipitation deficit', 'Soil-moisture deficit following the rain deficit', 'Vegetation stress following rain or soil-moisture deficit', 'Back to normal conditions', 'Soil moisture recovered, vegetation still affected', 'Vegetation recovered, moisture still low'],
      ctry: 'Country', drought: 'In drought (watch, warning or alert)', ly: 'Same period, last year', pts: 'points', hist: 'Trend over the past years', histAlt: '{n}: area in drought from {a} ({x}%) to {b} ({y}%)', now: 'Area in drought', alert: 'In alert', pick: 'Select a country to see its trend.', eu: 'European Union (27)',
      note: 'Each class is the percentage of the area with data, weighted by latitude. “In drought” adds watch, warning and alert. The latest ten-day period can be revised (provisional files are replaced by final ones).', src: 'Source: European Drought Observatory (EDO), Combined Drought Indicator © European Commission, JRC (CC BY 4.0). Aggregated by country by Dehesa Index.' },
    fr: { h: 'Sécheresse en Europe', sub: 'Part de la superficie de chaque pays en sécheresse agricole selon l’indicateur combiné de sécheresse (CDI) de l’Observatoire européen de la sécheresse (JRC). Mis à jour tous les dix jours.', dec: 'Décade du', cls: ['Vigilance', 'Avertissement', 'Alerte', 'Récupération', 'Récup. temporaire de l’humidité', 'Récup. temporaire de la végétation'], cd: ['Déficit de précipitations', 'Déficit d’humidité du sol après le manque de pluie', 'Stress de la végétation après manque de pluie ou d’humidité', 'Retour à des conditions normales', 'Humidité du sol rétablie, végétation encore touchée', 'Végétation rétablie, humidité encore basse'],
      ctry: 'Pays', drought: 'En sécheresse (vigilance, avertissement ou alerte)', ly: 'Même décade, an dernier', pts: 'points', hist: 'Évolution ces dernières années', histAlt: '{n} : superficie en sécheresse de {a} ({x} %) à {b} ({y} %)', now: 'Superficie en sécheresse', alert: 'En alerte', pick: 'Sélectionnez un pays pour voir son évolution.', eu: 'Union européenne (27)',
      note: 'Chaque classe est le pourcentage de la superficie avec données, pondéré par la latitude. « En sécheresse » additionne vigilance, avertissement et alerte. La dernière décade peut être révisée (les fichiers provisoires sont remplacés par les définitifs).', src: 'Source : European Drought Observatory (EDO), Combined Drought Indicator © Commission européenne, JRC (CC BY 4.0). Agrégé par pays par Dehesa Index.' },
    it: { h: 'Siccità in Europa', sub: 'Quota della superficie di ogni paese in siccità agricola secondo l’indicatore combinato di siccità (CDI) dell’Osservatorio europeo della siccità (JRC). Aggiornato ogni dieci giorni.', dec: 'Decade del', cls: ['Vigilanza', 'Avviso', 'Allerta', 'Recupero', 'Recupero temporaneo dell’umidità', 'Recupero temporaneo della vegetazione'], cd: ['Deficit di precipitazioni', 'Deficit di umidità del suolo dopo la mancanza di pioggia', 'Stress della vegetazione dopo mancanza di pioggia o umidità', 'Ritorno a condizioni normali', 'Umidità del suolo recuperata, vegetazione ancora colpita', 'Vegetazione recuperata, umidità ancora bassa'],
      ctry: 'Paese', drought: 'In siccità (vigilanza, avviso o allerta)', ly: 'Stessa decade, anno scorso', pts: 'punti', hist: 'Andamento negli ultimi anni', histAlt: '{n}: superficie in siccità da {a} ({x}%) a {b} ({y}%)', now: 'Superficie in siccità', alert: 'In allerta', pick: 'Seleziona un paese per vedere l’andamento.', eu: 'Unione europea (27)',
      note: 'Ogni classe è la percentuale della superficie con dati, ponderata per la latitudine. «In siccità» somma vigilanza, avviso e allerta. L’ultima decade può essere rivista (i file provvisori sono sostituiti da quelli definitivi).', src: 'Fonte: European Drought Observatory (EDO), Combined Drought Indicator © Commissione europea, JRC (CC BY 4.0). Aggregato per paese da Dehesa Index.' }
  };
  var COL = ['#e0b84a', '#e08a3a', '#b03a2e', '#6aa6c8', '#8ec3a7', '#a8b86a'];
  function lang() { return window.DehesaShared && window.DehesaShared.getLang ? window.DehesaShared.getLang() : 'es'; }
  function esc(x) { return String(x == null ? '' : x).replace(/[&<>"]/g, function (c) { return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]; }); }
  function nf(v, d) { try { return v.toLocaleString(lang(), { minimumFractionDigits: d, maximumFractionDigits: d }); } catch (e) { return v.toFixed(d); } }
  function day(iso) { var p = iso.split('-'); try { return new Date(Date.UTC(+p[0], +p[1] - 1, +p[2])).toLocaleDateString(lang(), { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC' }); } catch (e) { return iso; } }
  function cname(c, d) { var t = T[lang()] || T.es; if (c === 'EU27') return t.eu; try { var L = lang(); DN[L] = DN[L] || new Intl.DisplayNames([L], { type: 'region' }); var n = DN[L].of(c); return n && n !== c ? n : d.name; } catch (e) { return d.name; } }
  function dr(r) { return Math.min(100, Math.round((r[0] + r[1] + r[2]) * 10) / 10); }
  function sameLast(c) { var ps = D.periods, last = ps[ps.length - 1], p = last.split('-'), want = (+p[0] - 1) + '-' + p[1] + '-' + p[2], i = ps.indexOf(want); return i < 0 ? null : c.v[i]; }
  function chart(code, t) {
    var c = D.countries[code], ps = D.periods, s = c.v.map(function (r) { return dr(r); });
    var W = 640, H = 190, L = 40, R = 10, Tp = 12, B = 24, n = s.length; if (n < 4) return '';
    function X(i) { return L + i * (W - L - R) / (n - 1); } function Y(v) { return Tp + (100 - v) * (H - Tp - B) / 100; }
    var ar = s.map(function (v, i) { return (i ? 'L' : 'M') + X(i).toFixed(1) + ' ' + Y(v).toFixed(1); }).join(' '), al = c.v.map(function (r, i) { return (i ? 'L' : 'M') + X(i).toFixed(1) + ' ' + Y(r[2]).toFixed(1); }).join(' ');
    var grid = [0, 25, 50, 75, 100].map(function (v) { return '<g><line x1="' + L + '" x2="' + (W - R) + '" y1="' + Y(v).toFixed(1) + '" y2="' + Y(v).toFixed(1) + '" stroke="var(--border)"/><text x="' + (L - 6) + '" y="' + (Y(v) + 4).toFixed(1) + '" text-anchor="end" font-size="11" fill="var(--text-faint)">' + v + '</text></g>'; }).join('');
    var a = ps[0], b = ps[n - 1], nm = cname(code, c);
    var alt = t.histAlt.replace('{n}', nm).replace('{a}', day(a)).replace('{x}', nf(s[0], 0)).replace('{b}', day(b)).replace('{y}', nf(s[n - 1], 0));
    return '<h3 class="cof-h3">' + esc(nm) + ' · ' + esc(t.hist) + '</h3><svg viewBox="0 0 ' + W + ' ' + H + '" role="img" aria-label="' + esc(alt) + '" style="width:100%;height:auto;max-width:720px">' + grid + '<path d="' + ar + '" fill="none" stroke="' + COL[1] + '" stroke-width="2"/><path d="' + al + '" fill="none" stroke="' + COL[2] + '" stroke-width="2"/><text x="' + L + '" y="' + (H - 6) + '" font-size="11" fill="var(--text-faint)">' + esc(a.slice(0, 7)) + '</text><text x="' + (W - R) + '" y="' + (H - 6) + '" text-anchor="end" font-size="11" fill="var(--text-faint)">' + esc(b.slice(0, 7)) + '</text></svg><p class="cof-note"><span style="color:' + COL[1] + '">■</span> ' + esc(t.now) + ' (%) &nbsp; <span style="color:' + COL[2] + '">■</span> ' + esc(t.alert) + ' (%)</p>';
  }
  function render() {
    var root = document.getElementById('eusq'); if (!root || !D || !D.countries) return;
    var t = T[lang()] || T.es, last = D.periods.length - 1, codes = Object.keys(D.countries).filter(function (c) { return c !== 'EU27'; });
    codes.sort(function (a, b) { return dr(D.countries[b].v[last]) - dr(D.countries[a].v[last]); }); codes.unshift('EU27');
    var legend = t.cls.map(function (n, i) { return '<span style="margin-right:12px;white-space:nowrap" title="' + esc(t.cd[i]) + '"><span style="color:' + COL[i] + '">■</span> ' + esc(n) + '</span>'; }).join('');
    var rows = codes.map(function (c) {
      var d = D.countries[c], r = d.v[last], ly = sameLast(d), bar = r.map(function (v, i) { return v > 0 ? '<span style="display:inline-block;height:12px;width:' + v.toFixed(1) + '%;background:' + COL[i] + '"></span>' : ''; }).join('');
      return '<tr data-c="' + c + '" style="cursor:pointer' + (c === SEL ? ';background:rgba(29,81,120,.06)' : '') + '"><th scope="row"><button type="button" class="eusq-b" data-c="' + c + '" style="all:unset;cursor:pointer;font-weight:' + (c === 'EU27' ? 700 : 600) + '">' + esc(cname(c, d)) + '</button></th><td class="cof-n"><strong>' + esc(nf(dr(r), 1)) + ' %</strong></td><td class="cof-b" style="width:34%"><div style="display:flex;background:var(--border);border-radius:3px;overflow:hidden" role="img" aria-label="' + esc(r.map(function (v, i) { return t.cls[i] + ' ' + nf(v, 1) + ' %'; }).join(', ')) + '">' + bar + '</div></td><td class="cof-n">' + (ly ? esc(nf(dr(ly), 1)) + ' %' : '—') + '</td></tr>';
    }).join('');
    root.innerHTML = '<h2 class="cof-h2">' + esc(t.h) + '</h2><p class="cof-sub">' + esc(t.sub) + ' ' + esc(t.dec) + ' ' + esc(day(D.asOf)) + '.</p><p class="cof-note" style="line-height:1.8">' + legend + '</p><div class="di-card" style="padding:6px 14px;overflow-x:auto"><table class="cof-tbl"><thead><tr><th scope="col">' + esc(t.ctry) + '</th><th scope="col" class="cof-n">' + esc(t.drought) + '</th><th scope="col"></th><th scope="col" class="cof-n">' + esc(t.ly) + '</th></tr></thead><tbody>' + rows + '</tbody></table></div>' + chart(SEL, t) + '<p class="cof-note">' + esc(t.note) + '</p><p class="cof-note">' + esc(t.src) + '</p>' + (window.DICite ? window.DICite.html('edo_cdi', {}) : '');
    Array.prototype.forEach.call(root.querySelectorAll('.eusq-b'), function (b) { b.onclick = function () { SEL = b.getAttribute('data-c'); render(); }; });
  }
  function boot() {
    if (!document.getElementById('eusq')) return;
    Promise.all([fetch('data/eu-drought.json').then(function (r) { return r.ok ? r.json() : null; }).catch(function () { return null; }), window.DICite ? window.DICite.load().catch(function () { return null; }) : Promise.resolve(null)]).then(function (a) { D = a[0]; render(); });
    var prev = window.DehesaShared && window.DehesaShared.onLangChange;
    if (window.DehesaShared) window.DehesaShared.onLangChange = function () { if (prev) prev.apply(this, arguments); render(); };
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot); else boot();
})();
