/* Cabeceras (titulo y subtitulo) de los bloques de Dinamarca, Paises Bajos y Francia de paises.html; se cargan solo en esos tres paises. El contenido lo pinta js/eu-depth.js al abrir cada bloque. */
(function () {
  'use strict';
  window.EUHeads = { 'dk-harvest': { es: ['Dinamarca: cosecha por región (superficie, rendimiento y producción)', 'Ver cada cultivo por región y su evolución'], en: ['Denmark: harvest by region (area, yield and production)', 'See each crop by region and how it has moved'], fr: ['Danemark : récolte par région (surface, rendement et production)', 'Voir chaque culture par région et son évolution'], it: ['Danimarca: raccolto per regione (superficie, resa e produzione)', 'Vedi ogni coltura per regione e la sua evoluzione'] },
    'dk-live': { es: ['Dinamarca: ganado, leche, censos y subvenciones', 'Ver sacrificios, precios, leche, censos y pagos de la PAC'], en: ['Denmark: livestock, milk, herd counts and subsidies', 'See slaughter, prices, milk, herd counts and CAP payments'], fr: ['Danemark : élevage, lait, cheptel et subventions', 'Voir abattages, prix, lait, cheptel et paiements PAC'], it: ['Danimarca: allevamento, latte, consistenze e sovvenzioni', 'Vedi macellazioni, prezzi, latte, consistenze e pagamenti PAC'] },
    'dk-cap': { es: ['Dinamarca: PAC 2026 (importes y umbrales)', 'Ver los importes por hectárea y los requisitos de los decretos'], en: ['Denmark: CAP 2026 (amounts and thresholds)', 'See the per-hectare amounts and the requirements in the orders'], fr: ['Danemark : PAC 2026 (montants et seuils)', 'Voir les montants à l\'hectare et les exigences des arrêtés'], it: ['Danimarca: PAC 2026 (importi e soglie)', 'Vedi gli importi per ettaro e i requisiti dei decreti'] },
    'nl-crops': { es: ['Países Bajos: cultivos por provincia (superficie, rendimiento y producción)', 'Ver cada cultivo por provincia desde 1994'], en: ['Netherlands: crops by province (area, yield and production)', 'See each crop by province since 1994'], fr: ['Pays-Bas : cultures par province (surface, rendement et production)', 'Voir chaque culture par province depuis 1994'], it: ['Paesi Bassi: colture per provincia (superficie, resa e produzione)', 'Vedi ogni coltura per provincia dal 1994'] },
    'nl-farms': { es: ['Países Bajos: explotaciones y animales por provincia', 'Ver vacas lecheras, cerdos, aves y superficie por provincia'], en: ['Netherlands: farms and animals by province', 'See dairy cows, pigs, poultry and land by province'], fr: ['Pays-Bas : exploitations et animaux par province', 'Voir vaches laitières, porcs, volailles et surfaces par province'], it: ['Paesi Bassi: aziende e animali per provincia', 'Vedi vacche da latte, suini, avicoli e superfici per provincia'] },
    'nl-markets': { es: ['Países Bajos: precios del cerdo y el vacuno y sacrificios (semanal)', 'Ver precios semanales, sacrificios y el índice de precios agrarios'], en: ['Netherlands: pig and cattle prices and slaughter (weekly)', 'See weekly prices, slaughter and the farm price index'], fr: ['Pays-Bas : prix du porc et des bovins et abattages (hebdomadaire)', 'Voir prix hebdomadaires, abattages et indice des prix agricoles'], it: ['Paesi Bassi: prezzi di suini e bovini e macellazioni (settimanale)', 'Vedi prezzi settimanali, macellazioni e indice dei prezzi agricoli'] },
    'nl-fruit-dairy': { es: ['Países Bajos: manzana, pera y leche', 'Ver la cosecha de fruta desde 1997 y la leche y el queso de las lecherías cada mes'], en: ['Netherlands: apples, pears and milk', 'See the fruit harvest since 1997 and dairies’ monthly milk and cheese'], fr: ['Pays-Bas : pommes, poires et lait', 'Voir la récolte de fruits depuis 1997 et le lait et le fromage des laiteries chaque mois'], it: ['Paesi Bassi: mele, pere e latte', 'Vedi il raccolto di frutta dal 1997 e latte e formaggio dei caseifici ogni mese'] },
    'fr-water': { es: ['Francia: restricciones de agua por departamento (sequía)', 'Ver qué departamentos están en vigilancia, alerta o crisis'], en: ['France: water restrictions by department (drought)', 'See which departments are on vigilance, alert or crisis'], fr: ['France : restrictions d\'eau par département (sécheresse)', 'Voir quels départements sont en vigilance, alerte ou crise'], it: ['Francia: restrizioni idriche per dipartimento (siccità)', 'Vedi quali dipartimenti sono in vigilanza, allerta o crisi'] },
    'fr-maize': { es: ['Francia: estado semanal del maíz grano (Céré\'Obs)', 'Ver etapas del cultivo y estado por región frente a otros años'], en: ['France: weekly grain maize condition (Céré\'Obs)', 'See crop stages and condition by region against other years'], fr: ['France : état hebdomadaire du maïs grain (Céré\'Obs)', 'Voir les stades et l\'état des cultures par région face aux autres années'], it: ['Francia: stato settimanale del mais da granella (Céré\'Obs)', 'Vedi le fasi e lo stato per regione rispetto ad altri anni'] } };
  var EUMODS = { DK: ['dk-harvest', 'dk-live', 'dk-cap'], NL: ['nl-crops', 'nl-farms', 'nl-markets', 'nl-fruit-dairy'], FR: ['fr-water', 'fr-maize'] };
  function esc(s) { return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;'); }
  window.EUHeads.mount = function (box, c, lang) {
    box.innerHTML = EUMODS[c].map(function (m) { var H = window.EUHeads[m], tt = H[lang] || H.es; return '<details class="pa-card di-card" data-eu="' + m + '" id="eu-' + m + '"><summary>' + esc(tt[0]) + ' · <span>' + esc(tt[1]) + '</span></summary><div class="es-body"></div></details>'; }).join('');
    Array.prototype.forEach.call(box.querySelectorAll('details'), function (d) {
      var mod = d.getAttribute('data-eu'), go = function () { window.EUDepth.mount(d.lastChild, mod, lang); }, load = function () { if (window.EUDepth) go(); else { var sc = document.createElement('script'); sc.src = 'js/eu-depth.js?v=20261003'; sc.onload = go; document.head.appendChild(sc); } };
      d.addEventListener('toggle', function () { if (d.open && !d.getAttribute('data-ld')) { d.setAttribute('data-ld', '1'); load(); } }); if (location.hash === '#eu-' + mod) d.open = true;
    });
  };
})();
