/* Dehesa Index — Ganadería de España por provincia (MAPA, Encuestas ganaderas: efectivos de mayo y noviembre; data/spain-livestock).
   Pestaña «España (provincias)» de ganaderia.html sobre js/ca-explorer.js. Solo muestra lo que publica el MAPA; un hueco es un hueco. ES5. */
(function () {
  'use strict';
  var SP = { bovino: ['Vacuno', 'Cattle', 'Bovins', 'Bovini'], ovino: ['Ovino', 'Sheep', 'Ovins', 'Ovini'], caprino: ['Caprino', 'Goats', 'Caprins', 'Caprini'], porcino: ['Porcino', 'Pigs', 'Porcins', 'Suini'] };
  var PIG = ['Total', 'Lechones', 'Cerdos de 20 a 49 kg', 'Cebo · total', 'Cebo de 50 a 79 kg', 'Cebo de 80 a 109 kg', 'Cebo de más de 109 kg', 'Verracos', 'Cerdas reproductoras · total', 'Cerdas que nunca han parido y no cubiertas', 'Cerdas cubiertas por primera vez', 'Cerdas cubiertas más de una vez', 'Cerdas criando o en reposo'];
  var PIG_L = {
    en: ['Total', 'Piglets', 'Pigs 20–49 kg', 'Fattening · total', 'Fattening 50–79 kg', 'Fattening 80–109 kg', 'Fattening over 109 kg', 'Boars', 'Breeding sows · total', 'Sows never farrowed, not yet mated', 'Sows mated for the first time', 'Sows mated more than once', 'Sows suckling or resting'],
    fr: ['Total', 'Porcelets', 'Porcs de 20 à 49 kg', 'Engraissement · total', 'Engraissement 50–79 kg', 'Engraissement 80–109 kg', 'Engraissement > 109 kg', 'Verrats', 'Truies reproductrices · total', 'Truies n’ayant jamais mis bas, non saillies', 'Truies saillies pour la première fois', 'Truies saillies plusieurs fois', 'Truies allaitantes ou au repos'],
    it: ['Totale', 'Lattonzoli', 'Suini da 20 a 49 kg', 'Ingrasso · totale', 'Ingrasso 50–79 kg', 'Ingrasso 80–109 kg', 'Ingrasso oltre 109 kg', 'Verri', 'Scrofe riproduttrici · totale', 'Scrofe mai partorito, non coperte', 'Scrofe coperte la prima volta', 'Scrofe coperte più volte', 'Scrofe in allattamento o a riposo']
  };
  PIG_L.es = PIG;
  var PIGP = { 0: ['', '', '', ''], 1: ['no ibérico · ', 'non-Iberian · ', 'non ibérique · ', 'non iberico · '], 2: ['ibérico · ', 'Iberian · ', 'ibérique · ', 'iberico · '] };
  var LANG = ['es', 'en', 'fr', 'it'];
  var OTHER = {
    bovino: { 1: ['Total', 'Total', 'Total', 'Totale'], 2: ['Menores de 12 meses para sacrificio', 'Under 12 months, for slaughter', 'Moins de 12 mois, pour abattage', 'Sotto i 12 mesi, da macello'], 3: ['Menores de 12 meses · otros machos', 'Under 12 months · other males', 'Moins de 12 mois · autres mâles', 'Sotto i 12 mesi · altri maschi'], 4: ['Menores de 12 meses · otras hembras', 'Under 12 months · other females', 'Moins de 12 mois · autres femelles', 'Sotto i 12 mesi · altre femmine'], 5: ['De 12 a 24 meses · machos', '12–24 months · males', '12 à 24 mois · mâles', '12–24 mesi · maschi'], 6: ['De 12 a 24 meses · hembras para sacrificio', '12–24 months · females for slaughter', '12 à 24 mois · femelles pour abattage', '12–24 mesi · femmine da macello'], 7: ['De 12 a 24 meses · hembras de reposición', '12–24 months · replacement females', '12 à 24 mois · femelles de remplacement', '12–24 mesi · femmine da rimonta'], 8: ['De 24 meses o más · machos', '24 months or over · males', '24 mois ou plus · mâles', '24 mesi o più · maschi'], 9: ['Novillas para sacrificio', 'Heifers for slaughter', 'Génisses pour abattage', 'Giovenche da macello'], 10: ['Novillas · resto', 'Heifers · other', 'Génisses · autres', 'Giovenche · altre'], 11: ['Vacas lecheras', 'Dairy cows', 'Vaches laitières', 'Vacche da latte'], 12: ['Vacas · resto', 'Cows · other', 'Vaches · autres', 'Vacche · altre'] },
    ovino: { 1: ['Total', 'Total', 'Total', 'Totale'], 2: ['Corderos', 'Lambs', 'Agneaux', 'Agnelli'], 3: ['Sementales', 'Breeding rams', 'Béliers reproducteurs', 'Montoni'], 4: ['Hembras para vida · total', 'Females kept for life · total', 'Femelles de vie · total', 'Femmine da vita · totale'], 5: ['Hembras que nunca han parido y no cubiertas', 'Females never lambed, not yet mated', 'Femelles n’ayant jamais mis bas, non saillies', 'Femmine mai partorito, non coperte'], 6: ['Cubiertas por primera vez · ordeño', 'Mated for the first time · milked', 'Saillies pour la première fois · traites', 'Coperte la prima volta · da latte'], 7: ['Cubiertas por primera vez · no ordeño', 'Mated for the first time · not milked', 'Saillies pour la première fois · non traites', 'Coperte la prima volta · non munte'], 8: ['Que ya han parido · ordeño', 'Already lambed · milked', 'Ayant déjà mis bas · traites', 'Già partorito · da latte'], 9: ['Que ya han parido · no ordeño', 'Already lambed · not milked', 'Ayant déjà mis bas · non traites', 'Già partorito · non munte'] },
    caprino: { 1: ['Total', 'Total', 'Total', 'Totale'], 2: ['Chivos', 'Kids', 'Chevreaux', 'Capretti'], 3: ['Sementales', 'Breeding bucks', 'Boucs reproducteurs', 'Becchi'], 4: ['Hembras para vida · total', 'Females kept for life · total', 'Femelles de vie · total', 'Femmine da vita · totale'], 5: ['Hembras que nunca han parido y no cubiertas', 'Females never kidded, not yet mated', 'Femelles n’ayant jamais mis bas, non saillies', 'Femmine mai partorito, non coperte'], 6: ['Cubiertas por primera vez', 'Mated for the first time', 'Saillies pour la première fois', 'Coperte la prima volta'], 8: ['Que ya han parido · ordeño', 'Already kidded · milked', 'Ayant déjà mis bas · traites', 'Già partorito · da latte'], 9: ['Que ya han parido · no ordeño', 'Already kidded · not milked', 'Ayant déjà mis bas · non traites', 'Già partorito · non munte'] }
  };
  function lab(sp, code) {
    var n = parseInt(code, 10), o = [];
    if (sp === 'porcino') { var g = n <= 13 ? 0 : n <= 26 ? 1 : 2, k = n - 13 * g; for (var i = 0; i < 4; i++) o.push(SP.porcino[i] + ' · ' + PIGP[g][i] + PIG_L[LANG[i]][k - 1]); return o; }
    return OTHER[sp][n].map(function (x, i) { return SP[sp][i] + ' · ' + x; });
  }
  var T = {
    es: { tabUS: 'EE. UU.', tabCA: 'España (por provincia, MAPA)', title: 'Ganadería de España por provincia', sub: 'Efectivos de vacuno, ovino, caprino y porcino por provincia, según los censos de mayo y noviembre de las Encuestas ganaderas del Ministerio de Agricultura, Pesca y Alimentación (MAPA), tal como se publican.',
      item: 'Ganado', measure: 'Cifra', period: 'Censo', head: 'Efectivos (cabezas)', ca: 'España', vsPrev: 'frente al censo anterior', hist: 'Evolución nacional', prov: 'Por provincia', share: 'Peso en España', value: 'Valor', change: 'Variación', province: 'Provincia', pick: 'Pulsa una provincia (mapa o tabla) para compararla con España.', clear: 'Quitar la provincia', open: 'Perfil', noData: 'Sin datos disponibles.', noProv: 'Sin dato publicado para esta cifra y censo.', last: 'Último censo',
      note: 'Unidades originales del MAPA: cabezas. Los censos de ovino y caprino son de noviembre; vacuno y porcino, de mayo y noviembre. Los últimos censos pueden ser provisionales. Desde 2016 el MAPA publica algunas cifras de ovino y caprino con decimales (las redondeamos a un decimal). El MAPA redondea cada celda por separado, así que las provincias pueden diferir del total en unas pocas unidades. Un valor negativo en la fuente se deja como hueco. Un hueco es un hueco, nunca cero. Ceuta y Melilla no figuran.', src: 'Fuente: Ministerio de Agricultura, Pesca y Alimentación (MAPA), Encuestas ganaderas.', mapAlt: 'Mapa de provincias de España coloreado por la cifra elegida' },
    en: { tabUS: 'United States', tabCA: 'Spain (by province, MAPA)', title: 'Spanish livestock by province', sub: 'Cattle, sheep, goat and pig numbers by province, from the May and November censuses of the Spanish Ministry of Agriculture, Fisheries and Food (MAPA) livestock surveys, as published.',
      item: 'Livestock', measure: 'Measure', period: 'Census', head: 'Numbers (head)', ca: 'Spain', vsPrev: 'vs. previous census', hist: 'National trend', prov: 'By province', share: 'Share of Spain', value: 'Value', change: 'Change', province: 'Province', pick: 'Select a province (map or table) to compare it with Spain.', clear: 'Remove province', open: 'Profile', noData: 'No data available.', noProv: 'No published figure for this measure and census.', last: 'Latest census',
      note: 'Original MAPA units: head. Sheep and goat censuses are taken in November; cattle and pigs in May and November. The latest censuses may be provisional. Since 2016 MAPA publishes some sheep and goat figures with decimals (we round them to one decimal). MAPA rounds each cell separately, so provinces may differ from the total by a few units. A negative value in the source is left as a gap. A gap is a gap, never zero. Ceuta and Melilla are not shown.', src: 'Source: Ministry of Agriculture, Fisheries and Food (MAPA), livestock surveys.', mapAlt: 'Map of Spanish provinces coloured by the chosen measure' },
    fr: { tabUS: 'États-Unis', tabCA: 'Espagne (par province, MAPA)', title: 'Élevage en Espagne par province', sub: 'Effectifs de bovins, ovins, caprins et porcins par province, d’après les recensements de mai et novembre des enquêtes sur l’élevage du ministère espagnol de l’Agriculture, de la Pêche et de l’Alimentation (MAPA), tels que publiés.',
      item: 'Cheptel', measure: 'Chiffre', period: 'Recensement', head: 'Effectifs (têtes)', ca: 'Espagne', vsPrev: 'par rapport au recensement précédent', hist: 'Évolution nationale', prov: 'Par province', share: 'Part de l’Espagne', value: 'Valeur', change: 'Variation', province: 'Province', pick: 'Sélectionnez une province (carte ou tableau) pour la comparer à l’Espagne.', clear: 'Retirer la province', open: 'Profil', noData: 'Aucune donnée disponible.', noProv: 'Aucun chiffre publié pour cette mesure et ce recensement.', last: 'Dernier recensement',
      note: 'Unités d’origine du MAPA : têtes. Les recensements d’ovins et de caprins ont lieu en novembre ; ceux de bovins et de porcins en mai et novembre. Les derniers recensements peuvent être provisoires. Depuis 2016 le MAPA publie certains chiffres d’ovins et de caprins avec décimales (arrondis ici à une décimale). Le MAPA arrondit chaque cellule séparément : les provinces peuvent différer du total de quelques unités. Une valeur négative dans la source est laissée comme manque. Un manque est un manque, jamais zéro. Ceuta et Melilla ne figurent pas.', src: 'Source : ministère de l’Agriculture, de la Pêche et de l’Alimentation (MAPA), enquêtes sur l’élevage.', mapAlt: 'Carte des provinces espagnoles colorée selon le chiffre choisi' },
    it: { tabUS: 'Stati Uniti', tabCA: 'Spagna (per provincia, MAPA)', title: 'Zootecnia della Spagna per provincia', sub: 'Consistenze di bovini, ovini, caprini e suini per provincia, dai censimenti di maggio e novembre delle indagini zootecniche del ministero spagnolo dell’Agricoltura, della Pesca e dell’Alimentazione (MAPA), come pubblicati.',
      item: 'Bestiame', measure: 'Dato', period: 'Censimento', head: 'Consistenze (capi)', ca: 'Spagna', vsPrev: 'rispetto al censimento precedente', hist: 'Andamento nazionale', prov: 'Per provincia', share: 'Peso sulla Spagna', value: 'Valore', change: 'Variazione', province: 'Provincia', pick: 'Seleziona una provincia (mappa o tabella) per confrontarla con la Spagna.', clear: 'Rimuovi la provincia', open: 'Profilo', noData: 'Nessun dato disponibile.', noProv: 'Nessun dato pubblicato per questo dato e censimento.', last: 'Ultimo censimento',
      note: 'Unità originali del MAPA: capi. I censimenti di ovini e caprini sono di novembre; quelli di bovini e suini di maggio e novembre. Gli ultimi censimenti possono essere provvisori. Dal 2016 il MAPA pubblica alcuni dati di ovini e caprini con decimali (arrotondati qui a un decimale). Il MAPA arrotonda ogni cella separatamente: le province possono differire dal totale di poche unità. Un valore negativo nella fonte è lasciato come vuoto. Un vuoto è un vuoto, mai zero. Ceuta e Melilla non compaiono.', src: 'Fonte: Ministero dell’Agricoltura, della Pesca e dell’Alimentazione (MAPA), indagini zootecniche.', mapAlt: 'Mappa delle province spagnole colorata in base al dato scelto' }
  };
  var items = [], FILES = ['bovino', 'ovino', 'caprino', 'porcino'], CUR = null;
  function loadAll() {
    return Promise.all(FILES.map(function (s) { return fetch('data/spain-livestock/livestock-' + s + '.json').then(function (r) { return r.ok ? r.json() : null; }).catch(function () { return null; }); })).then(function (docs) {
      var D = { docs: {}, provinces: { ES: 1 }, names: {} };
      docs.forEach(function (d, i) { if (!d) return; D.docs[FILES[i]] = d; Object.keys(d.v).forEach(function (k) { D.provinces[k] = 1; }); });
      if (!Object.keys(D.docs).length) return null;
      ((window.DEHESA_ES_PROVINCES || {}).states || []).forEach(function (s) { D.names[s.id] = s.name; });
      items.length = 0;
      FILES.forEach(function (s) { var d = D.docs[s]; if (d) d.vars.forEach(function (v) { items.push({ id: s + '|' + v.id, label: lab(s, v.id) }); }); });
      CUR = D; return D;
    });
  }
  function series(D, prov, id) {
    var p = id.split('|'), d = D.docs[p[0]], a = d && d.v[prov] && d.v[prov][p[1]]; if (!a) return null;
    var out = []; a.forEach(function (x, i) { if (x != null) out.push([d.periods[i], x]); }); return out.length ? out : null;
  }
  window.GNSpainMapa = window.CAExplorer.create({
    id: 'gn-esm', tabsHost: 'gn-ca-tabs', usBody: 'gn-body', usExtra: '#cof, #nd, #nl', country: 'ES', nat: 'ES', map: 'DEHESA_ES_PROVINCES', noRegionLink: true, texts: T, items: items, defaultItem: 'bovino|01', defaultMeasure: 'head', cite: 'mapa_es',
    load: loadAll,
    pname: function (id) { return (CUR && CUR.names[id]) || id; },
    provIds: function (D) { CUR = D; return Object.keys(D.provinces).filter(function (k) { return k !== 'ES'; }); },
    measures: function (D, id) { CUR = D; return series(D, 'ES', id) ? ['head'] : []; },
    series: function (D, prov, id) { CUR = D; return series(D, prov, id); },
    fmt: function (m, v) { var d = function (x, n) { try { return x.toLocaleString(window.DehesaShared.getLang(), { minimumFractionDigits: n, maximumFractionDigits: n }); } catch (e) { return x.toFixed(n); } }; return v >= 1e6 ? d(v / 1e6, 2) + ' M' : d(v, 0); },
    yTitle: function () { return 'cabezas'; },
    shareMeasure: function () { return true; }
  });
})();
