/* Dehesa Index — Ganadería de España por comunidad autónoma (Eurostat, estadísticas agrarias regionales: efectivos y leche; data/eu-regions-es.json).
   Pestaña «España» de ganaderia.html sobre js/ca-explorer.js. El total es la suma de las 17 comunidades solo en los años en que las 17 tienen dato (nunca se rellena un hueco); no incluye Ceuta ni Melilla. ES5. */
(function () {
  'use strict';
  var ITEMS = [['A2000', ['Vacuno · total', 'Cattle · total', 'Bovins · total', 'Bovini · totale']], ['A2300F', ['Vacas lecheras', 'Dairy cows', 'Vaches laitières', 'Vacche da latte']], ['A2300G', ['Vacas no lecheras', 'Other cows', 'Vaches allaitantes', 'Vacche non da latte']],
    ['A3100', ['Porcino', 'Pigs', 'Porcins', 'Suini']], ['A4100', ['Ovino', 'Sheep', 'Ovins', 'Ovini']], ['A4200', ['Caprino', 'Goats', 'Caprins', 'Caprini']], ['milk', ['Leche de vaca producida', 'Cow’s milk produced', 'Lait de vache produit', 'Latte vaccino prodotto']]];
  var T = {
    es: { tabUS: 'EE. UU.', tabCA: 'España (por comunidad)', title: 'Ganadería de España por comunidad autónoma', sub: 'Efectivos de vacuno, porcino, ovino y caprino y leche de vaca producida por comunidad autónoma. Datos de Eurostat (estadísticas agrarias regionales), tal como los publica.',
      item: 'Ganado', measure: 'Cifra', period: 'Año', head: 'Efectivos', milk: 'Producción', ca: 'España (17 comunidades)', vsPrev: 'frente al año anterior', hist: 'Evolución nacional', prov: 'Por comunidad autónoma', share: 'Peso en España', value: 'Valor', change: 'Variación', province: 'Comunidad', pick: 'Pulsa una comunidad (mapa o tabla) para compararla con el total.', clear: 'Quitar la comunidad', open: 'Perfil de la comunidad', noData: 'Sin datos disponibles.', noProv: 'Sin dato publicado para esta cifra y año.', last: 'Último año',
      note: 'Unidades originales de Eurostat: miles de cabezas y miles de toneladas. El total es la suma de las 17 comunidades solo en los años en que todas tienen dato; no incluye Ceuta ni Melilla, que Eurostat no publica. Los efectivos son los de la encuesta del Ministerio, recopilados por Eurostat y revisables. Un hueco es un hueco, nunca cero.', src: 'Fuente: Eurostat (estadísticas agrarias regionales).', mapAlt: 'Mapa de comunidades autónomas coloreado por la cifra elegida' },
    en: { tabUS: 'United States', tabCA: 'Spain (by region)', title: 'Spanish livestock by autonomous community', sub: 'Cattle, pig, sheep and goat numbers and cow’s milk produced by autonomous community. Eurostat data (regional agricultural statistics), as published.',
      item: 'Livestock', measure: 'Measure', period: 'Year', head: 'Numbers', milk: 'Production', ca: 'Spain (17 communities)', vsPrev: 'vs. previous year', hist: 'National trend', prov: 'By autonomous community', share: 'Share of Spain', value: 'Value', change: 'Change', province: 'Community', pick: 'Select a community (map or table) to compare it with the total.', clear: 'Remove community', open: 'Community profile', noData: 'No data available.', noProv: 'No published figure for this measure and year.', last: 'Latest year',
      note: 'Original Eurostat units: thousand head and thousand tonnes. The total is the sum of the 17 communities only in years when all of them have data; it excludes Ceuta and Melilla, which Eurostat does not publish. Numbers come from the ministry survey as compiled by Eurostat and may be revised. A gap is a gap, never zero.', src: 'Source: Eurostat (regional agricultural statistics).', mapAlt: 'Map of Spanish autonomous communities coloured by the chosen measure' },
    fr: { tabUS: 'États-Unis', tabCA: 'Espagne (par communauté)', title: 'Élevage en Espagne par communauté autonome', sub: 'Effectifs de bovins, porcins, ovins et caprins et lait de vache produit par communauté autonome. Données d’Eurostat (statistiques agricoles régionales), telles que publiées.',
      item: 'Cheptel', measure: 'Chiffre', period: 'Année', head: 'Effectifs', milk: 'Production', ca: 'Espagne (17 communautés)', vsPrev: 'par rapport à l’an dernier', hist: 'Évolution nationale', prov: 'Par communauté autonome', share: 'Part de l’Espagne', value: 'Valeur', change: 'Variation', province: 'Communauté', pick: 'Sélectionnez une communauté (carte ou tableau) pour la comparer au total.', clear: 'Retirer la communauté', open: 'Profil de la communauté', noData: 'Aucune donnée disponible.', noProv: 'Aucun chiffre publié pour cette mesure et cette année.', last: 'Dernière année',
      note: 'Unités d’origine d’Eurostat : milliers de têtes et milliers de tonnes. Le total est la somme des 17 communautés uniquement les années où toutes ont une donnée ; il exclut Ceuta et Melilla, qu’Eurostat ne publie pas. Les effectifs proviennent de l’enquête du ministère compilée par Eurostat et sont révisables. Un manque est un manque, jamais zéro.', src: 'Source : Eurostat (statistiques agricoles régionales).', mapAlt: 'Carte des communautés autonomes colorée selon le chiffre choisi' },
    it: { tabUS: 'Stati Uniti', tabCA: 'Spagna (per comunità)', title: 'Zootecnia della Spagna per comunità autonoma', sub: 'Consistenze di bovini, suini, ovini e caprini e latte vaccino prodotto per comunità autonoma. Dati Eurostat (statistiche agricole regionali), come pubblicati.',
      item: 'Bestiame', measure: 'Dato', period: 'Anno', head: 'Consistenze', milk: 'Produzione', ca: 'Spagna (17 comunità)', vsPrev: 'rispetto all’anno scorso', hist: 'Andamento nazionale', prov: 'Per comunità autonoma', share: 'Peso sulla Spagna', value: 'Valore', change: 'Variazione', province: 'Comunità', pick: 'Seleziona una comunità (mappa o tabella) per confrontarla con il totale.', clear: 'Rimuovi la comunità', open: 'Profilo della comunità', noData: 'Nessun dato disponibile.', noProv: 'Nessun dato pubblicato per questo dato e anno.', last: 'Ultimo anno',
      note: 'Unità originali di Eurostat: migliaia di capi e migliaia di tonnellate. Il totale è la somma delle 17 comunità solo negli anni in cui tutte hanno il dato; esclude Ceuta e Melilla, che Eurostat non pubblica. Le consistenze derivano dall’indagine del ministero compilata da Eurostat e possono essere riviste. Un vuoto è un vuoto, mai zero.', src: 'Fonte: Eurostat (statistiche agricole regionali).', mapAlt: 'Mappa delle comunità autonome colorata in base al dato scelto' }
  };
  var items = ITEMS.map(function (i) { return { id: i[0], label: i[1] }; });
  function regSeries(r, id) { var a = id === 'milk' ? r.milk : r.animals && r.animals[id]; return a && a.length ? a.map(function (p) { return [String(p[0]), p[1]]; }) : null; }
  function series(D, prov, id) {
    if (prov !== 'ES') return regSeries(D.regions[prov], id);
    var ids = Object.keys(D.regions), by = {}, n = ids.length;
    ids.forEach(function (k) { (regSeries(D.regions[k], id) || []).forEach(function (p) { var e = by[p[0]] || (by[p[0]] = { s: 0, n: 0 }); e.s += p[1]; e.n++; }); });
    var out = Object.keys(by).sort().filter(function (y) { return by[y].n === n; }).map(function (y) { return [y, Math.round(by[y].s * 10) / 10]; });
    return out.length ? out : null;
  }
  window.GNSpain = window.CAExplorer.create({
    id: 'gn-es', tabsHost: 'gn-ca-tabs', usBody: 'gn-body', usExtra: '#cof, #nd, #nl', country: 'ES', nat: 'ES', map: 'DEHESA_ES_CCAA', texts: T, items: items, defaultItem: 'A2000', defaultMeasure: 'head', cite: 'eurostat',
    load: function () { return fetch('data/eu-regions-es.json').then(function (r) { return r.ok ? r.json() : null; }).catch(function () { return null; }).then(function (d) { if (d) { d.provinces = { ES: 1 }; Object.keys(d.regions).forEach(function (k) { d.provinces[k] = 1; }); } return d; }); },
    pname: function (id, i) { var N = window.DehesaRegionNames && window.DehesaRegionNames.ES, v = N && N[id]; if (!v) return id; var p = v.split('|'), L = { 0: 1, 1: 0, 2: 2, 3: 3 }[i]; return p[L] || p[0]; },
    measures: function (D, id) { return series(D, 'ES', id) ? [id === 'milk' ? 'milk' : 'head'] : []; },
    series: series,
    fmt: function (m, v) { var l = window.DehesaShared.getLang(), d = function (x, n) { try { return x.toLocaleString(l, { minimumFractionDigits: n, maximumFractionDigits: n }); } catch (e) { return x.toFixed(n); } }; var u = m === 'milk' ? ' kt' : ' k'; return v >= 1000 ? d(v / 1000, 2) + (m === 'milk' ? ' Mt' : ' M') : d(v, v >= 100 ? 0 : 1) + u; },
    yTitle: function (m) { return m === 'milk' ? 'kt' : '1000'; },
    shareMeasure: function () { return true }
  });
})();
