/* Dehesa Index — Costes de los insumos agrarios de EE. UU. Índices de precios pagados por los agricultores (USDA NASS, base 2011 = 100). */
(function () {
  'use strict';
  var D = null, SEL = { key: 'NITROGEN', span: 60 };
  var C1 = '#1d5178', C2 = '#b8a98a';
  var LI = { es: 0, en: 1, fr: 2, it: 3 }, P = 0;
  var SFX = ' - INDEX FOR PRICE PAID, 2011';
  var G = [
    { id: 'fert', l: ['Fertilizantes', 'Fertilizers', 'Engrais', 'Fertilizzanti'], k: { 'FERTILIZER TOTALS, INCL LIME & SOIL CONDITIONERS': ['Fertilizantes · total (con cal y enmiendas)', 'Fertilizer · total (incl. lime and soil conditioners)', 'Engrais · total (chaux et amendements inclus)', 'Fertilizzanti · totale (con calce e ammendanti)'], NITROGEN: ['Nitrógeno', 'Nitrogen', 'Azote', 'Azoto'], 'POTASH & PHOSPHATE': ['Potasa y fosfato', 'Potash and phosphate', 'Potasse et phosphate', 'Potassio e fosfato'], 'FERTILIZER, MIXED': ['Fertilizante mezclado', 'Mixed fertilizer', 'Engrais composé', 'Fertilizzante composto'] } },
    { id: 'fuel', l: ['Combustibles', 'Fuels', 'Carburants', 'Carburanti'], k: { FUELS: ['Combustibles · total', 'Fuels · total', 'Carburants · total', 'Carburanti · totale'], 'FUELS, DIESEL': ['Gasóleo', 'Diesel', 'Gazole', 'Gasolio'], 'FUELS, GASOLINE': ['Gasolina', 'Gasoline', 'Essence', 'Benzina'], 'FUELS, LP GAS': ['Gas propano (GLP)', 'LP gas', 'GPL', 'GPL'] } },
    { id: 'feed', l: ['Piensos', 'Feed', 'Aliments du bétail', 'Mangimi'], k: { FEED: ['Piensos · total', 'Feed · total', 'Aliments · total', 'Mangimi · totale'], 'FEED GRAINS': ['Cereales pienso', 'Feed grains', 'Céréales fourragères', 'Cereali da foraggio'], 'FEED, COMPLETE FEEDS': ['Piensos completos', 'Complete feeds', 'Aliments complets', 'Mangimi completi'], 'FEED, CONCENTRATES': ['Concentrados', 'Concentrates', 'Concentrés', 'Concentrati'], 'FEED, SUPPLEMENTS': ['Suplementos', 'Supplements', 'Compléments', 'Integratori'], 'FEED, FORAGE': ['Forrajes', 'Forage', 'Fourrages', 'Foraggi'] } },
    { id: 'chem', l: ['Agroquímicos y semillas', 'Agrochemicals and seed', 'Agrochimie et semences', 'Agrochimici e sementi'], k: { 'CHEMICAL TOTALS': ['Agroquímicos · total', 'Agrochemicals · total', 'Agrochimie · total', 'Agrochimici · totale'], HERBICIDES: ['Herbicidas', 'Herbicides', 'Herbicides', 'Erbicidi'], INSECTICIDES: ['Insecticidas', 'Insecticides', 'Insecticides', 'Insetticidi'], 'FUNGICIDES & OTHER': ['Fungicidas y otros', 'Fungicides and other', 'Fongicides et autres', 'Fungicidi e altri'], 'SEEDS & PLANTS TOTALS': ['Semillas y plantas', 'Seeds and plants', 'Semences et plants', 'Sementi e piante'] } },
    { id: 'mach', l: ['Maquinaria, servicios y financiación', 'Machinery, services and finance', 'Machines, services et financement', 'Macchinari, servizi e finanza'], k: { 'MACHINERY TOTALS': ['Maquinaria · total', 'Machinery · total', 'Machines · total', 'Macchinari · totale'], TRACTORS: ['Tractores', 'Tractors', 'Tracteurs', 'Trattori'], REPAIRS: ['Reparaciones', 'Repairs', 'Réparations', 'Riparazioni'], 'AG SERVICES': ['Servicios agrarios', 'Ag services', 'Services agricoles', 'Servizi agricoli'], 'AG SERVICES, CUSTOM RATES': ['Trabajos por contrata', 'Custom rates', 'Travaux à façon', 'Lavori per conto terzi'], 'LABOR, WAGE RATES': ['Salarios agrarios', 'Farm wage rates', 'Salaires agricoles', 'Salari agricoli'], RENT: ['Alquiler de tierra', 'Land rent', 'Fermage', 'Affitto terreni'], INTEREST: ['Intereses', 'Interest', 'Intérêts', 'Interessi'], TAXES: ['Impuestos', 'Taxes', 'Impôts', 'Imposte'] } },
    { id: 'animal', l: ['Animales y sectores', 'Animals and sectors', 'Animaux et secteurs', 'Animali e settori'], k: { 'CATTLE, FEEDER CATTLE': ['Terneros de cebo (feeder)', 'Feeder cattle', 'Bovins d’engraissement (feeder)', 'Vitelli da ingrasso (feeder)'], 'HOGS, FEEDER PIGS': ['Lechones (feeder pigs)', 'Feeder pigs', 'Porcelets (feeder)', 'Suinetti (feeder)'], 'POULTRY TOTALS': ['Aves · total', 'Poultry · total', 'Volaille · total', 'Pollame · totale'], 'ANIMAL SECTOR': ['Sector ganadero', 'Animal sector', 'Secteur animal', 'Settore zootecnico'], 'CROP SECTOR': ['Sector agrícola', 'Crop sector', 'Secteur végétal', 'Settore colturale'], 'PRODUCTION ITEMS': ['Insumos de producción', 'Production items', 'Intrants de production', 'Fattori di produzione'], 'FARM SECTOR': ['Total del sector agrario', 'Farm sector total', 'Total du secteur agricole', 'Totale del settore agricolo'], 'CONSUMER PRICE INDEX': ['Índice de precios al consumo (IPC)', 'Consumer price index (CPI)', 'Indice des prix à la consommation', 'Indice dei prezzi al consumo'] } }
  ];
  var T = {
    es: { title: 'Costes de los insumos agrarios de EE. UU.', sub: 'Cuánto pagan los agricultores estadounidenses por fertilizantes, combustibles, piensos, agroquímicos, maquinaria y más. Índices mensuales de precios pagados de USDA NASS (base 2011 = 100).',
      series: 'Índice', latest: 'Último mes', vsPrev: 'frente al mes anterior', vsYear: 'frente al mismo mes del año anterior', hist: 'Evolución', span: 'Periodo', s12: '12 meses', s36: '3 años', s60: '5 años', all: 'Todos los índices', name: 'Índice', now: 'Ahora', mm: 'Mes', yy: 'Año', noData: 'Sin datos.',
      note: 'Fuente: USDA NASS, Agricultural Prices (Quick Stats). Son índices de precios pagados por los agricultores con base 2011 = 100: un valor de 150 significa que el precio es un 50 % superior al de 2011. NASS ya no publica precios absolutos de fertilizantes o combustibles; los índices son la referencia oficial disponible. Este producto usa la API de NASS pero no está respaldado ni certificado por NASS.', src: 'Fuente: USDA NASS (datos públicos)' },
    en: { title: 'U.S. farm input costs', sub: 'What U.S. farmers pay for fertilizer, fuel, feed, agrochemicals, machinery and more. Monthly prices-paid indexes from USDA NASS (2011 = 100).',
      series: 'Index', latest: 'Latest month', vsPrev: 'vs. previous month', vsYear: 'vs. same month last year', hist: 'Trend', span: 'Period', s12: '12 months', s36: '3 years', s60: '5 years', all: 'All indexes', name: 'Index', now: 'Now', mm: 'Month', yy: 'Year', noData: 'No data.',
      note: 'Source: USDA NASS, Agricultural Prices (Quick Stats). These are prices-paid indexes with 2011 = 100: a value of 150 means prices are 50% above 2011. NASS no longer publishes absolute fertilizer or fuel prices; the indexes are the official reference available. This product uses the NASS API but is not endorsed or certified by NASS.', src: 'Source: USDA NASS (public data)' },
    fr: { title: 'Coûts des intrants agricoles aux États-Unis', sub: 'Ce que paient les agriculteurs américains pour les engrais, carburants, aliments du bétail, produits phytosanitaires, machines, etc. Indices mensuels des prix payés de l’USDA NASS (base 2011 = 100).',
      series: 'Indice', latest: 'Dernier mois', vsPrev: 'par rapport au mois précédent', vsYear: 'par rapport au même mois l’an dernier', hist: 'Évolution', span: 'Période', s12: '12 mois', s36: '3 ans', s60: '5 ans', all: 'Tous les indices', name: 'Indice', now: 'Actuel', mm: 'Mois', yy: 'An', noData: 'Pas de données.',
      note: 'Source : USDA NASS, Agricultural Prices (Quick Stats). Indices des prix payés, base 2011 = 100 : 150 signifie des prix 50 % au-dessus de 2011. NASS ne publie plus de prix absolus d’engrais ou de carburants ; les indices sont la référence officielle disponible. Ce produit utilise l’API de NASS mais n’est ni approuvé ni certifié par NASS.', src: 'Source : USDA NASS (données publiques)' },
    it: { title: 'Costi degli input agricoli negli USA', sub: 'Quanto pagano gli agricoltori americani per fertilizzanti, carburanti, mangimi, agrochimici, macchinari e altro. Indici mensili dei prezzi pagati dell’USDA NASS (base 2011 = 100).',
      series: 'Indice', latest: 'Ultimo mese', vsPrev: 'rispetto al mese precedente', vsYear: 'rispetto allo stesso mese dell’anno scorso', hist: 'Andamento', span: 'Periodo', s12: '12 mesi', s36: '3 anni', s60: '5 anni', all: 'Tutti gli indici', name: 'Indice', now: 'Ora', mm: 'Mese', yy: 'Anno', noData: 'Nessun dato.',
      note: 'Fonte: USDA NASS, Agricultural Prices (Quick Stats). Indici dei prezzi pagati con base 2011 = 100: 150 significa prezzi del 50% sopra il 2011. NASS non pubblica più prezzi assoluti di fertilizzanti o carburanti; gli indici sono il riferimento ufficiale disponibile. Questo prodotto usa l’API di NASS ma non è approvato né certificato da NASS.', src: 'Fonte: USDA NASS (dati pubblici)' }
  };
  function lang() { return window.DehesaShared && window.DehesaShared.getLang ? window.DehesaShared.getLang() : 'es'; }
  function tr() { P = LI[lang()] || 0; return T[lang()] || T.es; }
  function esc(s) { return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); }
  function nf(v, d) { try { return v.toLocaleString(lang(), { minimumFractionDigits: d, maximumFractionDigits: d }); } catch (e) { return v.toFixed(d); } }
  function pct(a, b) { return b ? (a / b - 1) * 100 : null; }
  // Para costes, subir es malo: rojo si sube, verde si baja
  function chg(p) { if (p === null) return '<span style="color:var(--text-faint)">—</span>'; var c = p > 0.05 ? '#a9491f' : p < -0.05 ? '#2f7d4f' : 'var(--text-faint)'; return '<span style="color:' + c + ';font-weight:600">' + (p > 0.05 ? '+' : p < -0.05 ? '−' : '') + nf(Math.abs(p), 1) + ' %</span>'; }
  function ser(k) { var s = D.series[k + SFX]; return s ? s.n : null; }
  function find(a, p) { for (var i = a.length - 1; i >= 0; i--) if (a[i][0] === p) return a[i][1]; return null; }
  function py(p) { return (Number(p.slice(0, 4)) - 1) + p.slice(4); }
  function pm(a) { return a.length > 1 ? a[a.length - 2][1] : null; }
  var AXX = { es: ['Mes', 'Índice (2011 = 100)'], en: ['Month', 'Index (2011 = 100)'], fr: ['Mois', 'Indice (2011 = 100)'], it: ['Mese', 'Indice (2011 = 100)'] };
  function axTitle(y, x, yx) { return '<text transform="translate(12 ' + yx + ') rotate(-90)" font-size="11" font-weight="600" text-anchor="middle" fill="var(--text-faint)">' + esc(y) + '</text><text x="' + x[0] + '" y="' + x[1] + '" font-size="11" font-weight="600" text-anchor="middle" fill="var(--text-faint)">' + esc(x[2]) + '</text>'; }
  function lineChart(a, cmp) {
    var W = 720, H = 252, L = 62, R = 12, Tp = 12, Bt = 48, n = a.length, min = Infinity, max = -Infinity;
    a.concat(cmp || []).forEach(function (x) { if (x[1] > max) max = x[1]; if (x[1] < min) min = x[1]; });
    if (n < 2) return '';
    var lo = Math.floor(min / 10) * 10 - 10 > 0 ? Math.floor(min / 10) * 10 - 10 : 0, hi = Math.ceil(max / 10) * 10 + 5;
    var x = function (i) { return L + (W - L - R) * i / (n - 1); }, y = function (v) { return Tp + (H - Tp - Bt) * (1 - (v - lo) / (hi - lo)); };
    var g = ''; for (var k = 0; k <= 4; k++) { var vv = lo + (hi - lo) * k / 4; g += '<line x1="' + L + '" x2="' + (W - R) + '" y1="' + y(vv) + '" y2="' + y(vv) + '" stroke="var(--border)"/><text x="' + (L - 6) + '" y="' + (y(vv) + 4) + '" font-size="11" text-anchor="end" fill="var(--text-faint)">' + nf(vv, 0) + '</text>'; }
    var d = a.map(function (p, i) { return (i ? 'L' : 'M') + x(i).toFixed(1) + ' ' + y(p[1]).toFixed(1); }).join(' ');
    var dots = n <= 40 ? a.map(function (p, i) { return '<circle cx="' + x(i).toFixed(1) + '" cy="' + y(p[1]).toFixed(1) + '" r="3" fill="' + C1 + '"><title>' + esc(p[0] + ': ' + nf(p[1], 1)) + '</title></circle>'; }).join('') : '';
    var xl = [0, Math.floor((n - 1) / 2), n - 1].map(function (i) { return '<text x="' + x(i) + '" y="' + (H - Bt + 17) + '" font-size="11" text-anchor="' + (i === 0 ? 'start' : i === n - 1 ? 'end' : 'middle') + '" fill="var(--text-faint)">' + esc(a[i][0]) + '</text>'; }).join('') + axTitle((AXX[lang()] || AXX.es)[1], [(L + W - R) / 2, H - 5, (AXX[lang()] || AXX.es)[0]], (Tp + H - Bt) / 2);
    var spec = { L: L, R: W - R, T: Tp, B: H - Bt, s: [{ n: '', c: C1, p: a.map(function (p, i) { return [+x(i).toFixed(1), +y(p[1]).toFixed(1), nf(p[1], 1), p[0], p[1]]; }) }] };
    return '<svg viewBox="0 0 ' + W + ' ' + H + '" style="width:100%;height:auto;display:block;touch-action:pan-y" role="img"' + window.DehesaChart.attr(spec).replace(' style="touch-action:pan-y"', '') + '>' + g + '<path d="' + d + '" fill="none" stroke="' + C1 + '" stroke-width="2.2" stroke-linejoin="round"/>' + dots + xl + '</svg>';
  }
  function card(l, v, sub) { return '<div class="di-card" style="padding:14px 16px;flex:1 1 200px;min-width:180px"><div style="font-size:11px;letter-spacing:.4px;color:var(--text-faint);font-weight:700">' + esc(l).toUpperCase() + '</div><div style="font-size:24px;font-weight:700;margin:4px 0 2px;font-family:\'Source Serif 4\',serif">' + v + '</div><div style="font-size:12.5px">' + sub + '</div></div>'; }
  function render() {
    var t = tr(), root = document.getElementById('in-body');
    document.title = 'Dehesa Index — ' + t.title; document.getElementById('pg-h1').textContent = t.title; document.getElementById('pg-sub').textContent = t.sub;
    if (!D) { root.innerHTML = '<p class="di-movers-hint">' + esc(t.noData) + '</p>'; return; }
    var all = []; G.forEach(function (g) { Object.keys(g.k).forEach(function (k) { if (ser(k)) all.push({ k: k, g: g, l: g.k[k][P] }); }); });
    if (!all.some(function (x) { return x.k === SEL.key; })) SEL.key = all[0].k;
    var a = ser(SEL.key), last = a[a.length - 1], prev = pm(a), yv = find(a, py(last[0])), shown = DIRange.cut(a, SEL.span);
    var cur = all.filter(function (x) { return x.k === SEL.key; })[0];
    var opts = G.map(function (g) { return '<optgroup label="' + esc(g.l[P]) + '">' + all.filter(function (x) { return x.g === g; }).map(function (x) { return '<option value="' + esc(x.k) + '"' + (x.k === SEL.key ? ' selected' : '') + '>' + esc(x.l) + '</option>'; }).join('') + '</optgroup>'; }).join('');
    var sp = DIRange.options(SEL.span, lang(), a);
    var cards = '<div style="display:flex;gap:12px;flex-wrap:wrap;margin:14px 0">' + card(t.latest + ' · ' + last[0], nf(last[1], 1), '<span style="color:var(--text-faint)">2011 = 100</span>') + card(t.vsPrev, prev !== null ? chg(pct(last[1], prev)) : '—', prev !== null ? '<span style="color:var(--text-faint)">' + nf(prev, 1) + '</span>' : '') + card(t.vsYear, yv !== null ? chg(pct(last[1], yv)) : '—', yv !== null ? '<span style="color:var(--text-faint)">' + esc(py(last[0])) + ': ' + nf(yv, 1) + '</span>' : '') + '</div>';
    var chart = '<div class="di-card" style="padding:14px 16px"><div style="font-weight:600;margin-bottom:6px">' + esc(cur.l) + ' · ' + esc(t.hist) + '</div>' + lineChart(shown) + '</div>';
    var th = function (x, r) { return '<th style="padding:10px 6px;font-size:10.5px;font-weight:700;letter-spacing:.4px;color:var(--text-faint);text-align:' + (r ? 'right' : 'left') + '">' + esc(x).toUpperCase() + '</th>'; };
    var tbl = '<div style="font-weight:600;margin:20px 0 6px">' + esc(t.all) + ' · ' + esc(last[0]) + '</div><div class="di-card" style="padding:6px 16px;overflow-x:auto"><table style="border-collapse:collapse;width:100%;min-width:480px;font-size:14px"><tr>' + th(t.name) + th(t.now, 1) + th(t.mm, 1) + th(t.yy, 1) + '</tr>' +
      G.map(function (g) { return '<tr><td colspan="4" style="padding:12px 6px 4px;font-size:11px;font-weight:700;letter-spacing:.4px;color:var(--text-faint)">' + esc(g.l[P]).toUpperCase() + '</td></tr>' + all.filter(function (x) { return x.g === g; }).map(function (x) { var s = ser(x.k), l = s[s.length - 1]; return '<tr data-k="' + esc(x.k) + '" style="border-top:1px solid var(--border);cursor:pointer' + (x.k === SEL.key ? ';background:rgba(29,81,120,.06)' : '') + '"><td style="padding:9px 6px;font-weight:600">' + esc(x.l) + '</td><td style="padding:9px 6px;text-align:right">' + nf(l[1], 1) + '</td><td style="padding:9px 6px;text-align:right">' + chg(pm(s) !== null ? pct(l[1], pm(s)) : null) + '</td><td style="padding:9px 6px;text-align:right">' + chg(find(s, py(l[0])) !== null ? pct(l[1], find(s, py(l[0]))) : null) + '</td></tr>'; }).join(''); }).join('') + '</table></div>';
    root.innerHTML = '<div style="display:flex;gap:16px;flex-wrap:wrap"><label style="font-size:13px">' + esc(t.series) + '<br><select id="in-sel" class="di-compare-select">' + opts + '</select></label><label style="font-size:13px">' + esc(t.span) + '<br><select id="in-span" class="di-compare-select">' + sp + '</select></label></div>' + cards + chart + tbl + '<p class="di-info-api-notice" style="margin:14px 0 6px">' + esc(t.note) + '</p><p class="di-movers-hint">' + esc(t.src) + '</p>';
    document.getElementById('in-sel').onchange = function (e) { SEL.key = e.target.value; render(); };
    document.getElementById('in-span').onchange = function (e) { SEL.span = parseInt(e.target.value, 10); render(); };
    Array.prototype.forEach.call(root.querySelectorAll('[data-k]'), function (r) { r.onclick = function () { SEL.key = r.getAttribute('data-k'); render(); window.scrollTo({ top: 0, behavior: 'smooth' }); }; });
  }
  window.DehesaShared.init('informacion');
  var prevCb = window.DehesaShared.onLangChange;
  window.DehesaShared.onLangChange = function () { if (prevCb) prevCb.apply(this, arguments); render(); };
  fetch('data/nass-prices.json').then(function (r) { return r.ok ? r.json() : null; }).catch(function () { return null; }).then(function (d) {
    D = d && d.series && Object.keys(d.series).length ? d : null;
    var q = new URLSearchParams(window.location.search); if (q.get('k')) SEL.key = q.get('k');
    render();
  });
})();
