/* Dehesa Index — Insumos agrarios de Canadá (Statistics Canada): índice de precios de insumos, envíos de fertilizantes y combustible. Pestaña «Canadá» de insumos.html sobre js/ca-series.js. ES5. */
(function () {
  'use strict';
  var T = {
    es: { tabUS: 'EE. UU.', tabCA: 'Canadá', title: 'Costes de los insumos agrarios de Canadá', sub: 'Lo que pagan los agricultores canadienses por fertilizantes, combustible, piensos, maquinaria y más: índice trimestral de precios de insumos, envíos de fertilizantes y diésel. Datos de Statistics Canada.',
      latest: 'Último dato', vsPrev: 'frente al periodo anterior', vsYear: 'frente al mismo periodo del año anterior', change: 'Variación', period: 'Periodo', series: 'Serie', range: 'Periodo mostrado', years: 'años', all: 'Todo', date: 'Fecha', noData: 'Sin datos disponibles.',
      note: 'El índice de precios de insumos (base 2012 = 100) mide cuánto cambian los precios que pagan los agricultores, no su nivel: 130 significa un 30 % más que en 2012. Los envíos de fertilizantes son toneladas entregadas a la agricultura por campaña (julio-junio), no precios: Canadá no tiene una serie abierta de precios de fertilizantes. El combustible es el precio al público por ciudad (centavos por litro), no el precio que paga una explotación. Un hueco es un hueco, nunca cero.', src: 'Fuente: Statistics Canada, tablas 18-10-0258, 32-10-0038 y 18-10-0001 (Open Government Licence – Canada).' },
    en: { tabUS: 'United States', tabCA: 'Canada', title: 'Canadian farm input costs', sub: 'What Canadian farmers pay for fertilizer, fuel, feed, machinery and more: quarterly farm input price index, fertilizer shipments and diesel. Statistics Canada data.',
      latest: 'Latest', vsPrev: 'vs. previous period', vsYear: 'vs. same period last year', change: 'Change', period: 'Period', series: 'Series', range: 'Period shown', years: 'years', all: 'All', date: 'Date', noData: 'No data available.',
      note: 'The farm input price index (2012 = 100) measures how much prices paid by farmers change, not their level: 130 means 30% above 2012. Fertilizer shipments are tonnes delivered to agriculture per season (July–June), not prices: Canada has no open fertilizer price series. Fuel is the retail pump price by city (cents per litre), not the price a farm pays. A gap is a gap, never zero.', src: 'Source: Statistics Canada, tables 18-10-0258, 32-10-0038 and 18-10-0001 (Open Government Licence – Canada).' },
    fr: { tabUS: 'États-Unis', tabCA: 'Canada', title: 'Coûts des intrants agricoles au Canada', sub: 'Ce que paient les agriculteurs canadiens pour les engrais, le carburant, les aliments du bétail, les machines, etc. : indice trimestriel des prix des intrants, livraisons d’engrais et diesel. Données de Statistique Canada.',
      latest: 'Dernière donnée', vsPrev: 'par rapport à la période précédente', vsYear: 'par rapport à la même période l’an dernier', change: 'Variation', period: 'Période', series: 'Série', range: 'Période affichée', years: 'ans', all: 'Tout', date: 'Date', noData: 'Aucune donnée disponible.',
      note: 'L’indice des prix des intrants agricoles (base 2012 = 100) mesure l’évolution des prix payés par les agriculteurs, pas leur niveau : 130 signifie 30 % de plus qu’en 2012. Les livraisons d’engrais sont des tonnes livrées à l’agriculture par campagne (juillet-juin), pas des prix : le Canada n’a pas de série ouverte de prix des engrais. Le carburant est le prix à la pompe par ville (cents par litre), pas le prix payé par une exploitation. Un manque est un manque, jamais zéro.', src: 'Source : Statistique Canada, tableaux 18-10-0258, 32-10-0038 et 18-10-0001 (Licence du gouvernement ouvert – Canada).' },
    it: { tabUS: 'Stati Uniti', tabCA: 'Canada', title: 'Costi degli input agricoli in Canada', sub: 'Quanto pagano gli agricoltori canadesi per fertilizzanti, carburante, mangimi, macchinari e altro: indice trimestrale dei prezzi degli input, consegne di fertilizzanti e gasolio. Dati di Statistics Canada.',
      latest: 'Ultimo dato', vsPrev: 'rispetto al periodo precedente', vsYear: 'rispetto allo stesso periodo dell’anno scorso', change: 'Variazione', period: 'Periodo', series: 'Serie', range: 'Periodo mostrato', years: 'anni', all: 'Tutto', date: 'Data', noData: 'Nessun dato disponibile.',
      note: 'L’indice dei prezzi degli input (base 2012 = 100) misura quanto cambiano i prezzi pagati dagli agricoltori, non il loro livello: 130 significa il 30% in più del 2012. Le consegne di fertilizzanti sono tonnellate consegnate all’agricoltura per campagna (luglio-giugno), non prezzi: il Canada non ha una serie aperta dei prezzi dei fertilizzanti. Il carburante è il prezzo alla pompa per città (centesimi al litro), non il prezzo pagato da un’azienda. Un vuoto è un vuoto, mai zero.', src: 'Fonte: Statistics Canada, tabelle 18-10-0258, 32-10-0038 e 18-10-0001 (Open Government Licence – Canada).' }
  };
  window.INCanada = window.CASeries.create({
    id: 'in-ca', usBody: 'in-body', texts: T, defaultGroup: 'index', cite: 'statcan',
    groups: [
      { id: 'index', label: ['Índice de precios de insumos', 'Input price index', 'Indice des prix des intrants', 'Indice dei prezzi degli input'], pick: function (s) { return s.group === 'idx_pag'; } },
      { id: 'fert', label: ['Fertilizantes (envíos)', 'Fertilizers (shipments)', 'Engrais (livraisons)', 'Fertilizzanti (consegne)'], pick: function (s) { return s.group === 'inputs_f'; } },
      { id: 'fuel', label: ['Combustible (precio al público)', 'Fuel (pump price)', 'Carburant (prix à la pompe)', 'Carburante (prezzo alla pompa)'], pick: function (s) { return s.group === 'inputs'; } }
    ],
    usRender: function () { if (window.__inUsRender) window.__inUsRender(); }
  });
})();
