/* Dehesa Index — Leche cruda de España: entregas, precio, grasa, proteína y ganaderos por comunidad autónoma (MAPA, INFOLAC; data/spain-milk/infolac.json).
   Pestaña «España (leche, INFOLAC)» de ganaderia.html sobre js/ca-explorer.js. Solo muestra lo que publica el MAPA; un mes sin dato es un hueco, nunca cero. ES5. */
(function () {
  'use strict';
  var CODE = { andalucia: 'AN', aragon: 'AR', asturias: 'AS', baleares: 'IB', canarias: 'CN', cantabria: 'CB', clm: 'CM', cyl: 'CL', cataluna: 'CT', extremadura: 'EX', galicia: 'GA', madrid: 'MD', murcia: 'MC', navarra: 'NC', paisvasco: 'PV', larioja: 'RI', valenciana: 'VC' };
  var ITEMS = [['production', ['Leche entregada', 'Milk delivered', 'Lait livré', 'Latte consegnato']], ['price', ['Precio medio declarado', 'Average declared price', 'Prix moyen déclaré', 'Prezzo medio dichiarato']], ['fat', ['Materia grasa', 'Fat content', 'Matière grasse', 'Materia grassa']], ['protein', ['Proteína', 'Protein content', 'Protéines', 'Proteine']],
    ['farmers', ['Ganaderos con entregas', 'Farmers delivering', 'Éleveurs livrant', 'Allevatori con consegne']], ['buyers', ['Compradores con entregas', 'Buyers declaring deliveries', 'Acheteurs déclarant des livraisons', 'Acquirenti con consegne']], ['organic', ['Leche ecológica', 'Organic milk', 'Lait biologique', 'Latte biologico']]];
  var MEAS = { production: 'prod', organic: 'prod', price: 'price', fat: 'pct', protein: 'pct', farmers: 'n', buyers: 'n' };
  var T = {
    es: { tabUS: 'EE. UU.', tabCA: 'España (leche, INFOLAC)', title: 'Leche cruda en España: entregas, precio y calidad', sub: 'Entregas mensuales de leche cruda a los primeros compradores, precio medio declarado, grasa y proteína, y ganaderos, por comunidad autónoma. Datos del Ministerio de Agricultura, Pesca y Alimentación (MAPA, INFOLAC), tal como los publica.',
      item: 'Serie', measure: 'Cifra', period: 'Mes', prod: 'Toneladas', price: '€ por litro', pct: 'Porcentaje', n: 'Número', ca: 'España', vsPrev: 'frente al mismo mes del año anterior', hist: 'Evolución nacional', prov: 'Por comunidad autónoma', share: 'Peso en España', value: 'Valor', change: 'Variación', province: 'Comunidad', pick: 'Pulsa una comunidad (mapa o tabla) para compararla con España.', clear: 'Quitar la comunidad', open: 'Perfil', noData: 'Sin datos disponibles.', noProv: 'Sin dato publicado para esta serie y mes.', last: 'Último mes',
      note: 'Los datos salen de las declaraciones obligatorias de entregas de leche cruda a los primeros compradores (INFOLAC) y el MAPA avisa de que no están consolidados: puede revisarlos en informes posteriores y entonces prevalece el último. El precio es el importe medio declarado (media ponderada, con bonificaciones y penalizaciones por calidad, sin IVA ni transporte). Precio, compradores y leche ecológica solo se publican a nivel nacional. La leche se asigna a la comunidad del ganadero. Cada informe cubre 12 meses: la historia se acumula (precio desde enero de 2022, entregas desde septiembre de 2024, resto por comunidad desde septiembre de 2025). En septiembre de 2025 el total incluye a un ganadero de Portugal que no figura por comunidad. Un hueco es un hueco, nunca cero.', src: 'Fuente: Ministerio de Agricultura, Pesca y Alimentación (MAPA), INFOLAC: declaraciones de entregas de leche cruda a los primeros compradores.', mapAlt: 'Mapa de comunidades autónomas de España coloreado por la cifra elegida' },
    en: { tabUS: 'United States', tabCA: 'Spain (milk, INFOLAC)', title: 'Raw milk in Spain: deliveries, price and quality', sub: 'Monthly raw milk deliveries to first buyers, average declared price, fat and protein, and farmers, by autonomous community. Data from the Spanish Ministry of Agriculture, Fisheries and Food (MAPA, INFOLAC), as published.',
      item: 'Series', measure: 'Measure', period: 'Month', prod: 'Tonnes', price: '€ per litre', pct: 'Percent', n: 'Number', ca: 'Spain', vsPrev: 'vs. the same month a year earlier', hist: 'National trend', prov: 'By autonomous community', share: 'Share of Spain', value: 'Value', change: 'Change', province: 'Community', pick: 'Select a community (map or table) to compare it with Spain.', clear: 'Remove community', open: 'Profile', noData: 'No data available.', noProv: 'No published figure for this series and month.', last: 'Latest month',
      note: 'The data come from the mandatory declarations of raw milk deliveries to first buyers (INFOLAC) and MAPA warns they are not consolidated: later reports may revise them, and the latest one prevails. The price is the average declared amount (weighted mean, including quality bonuses and penalties, excluding VAT and transport). Price, buyers and organic milk are published at national level only. Milk is assigned to the farmer’s community. Each report covers 12 months, so history accumulates (price since January 2022, deliveries since September 2024, the rest by community since September 2025). In September 2025 the total includes a farmer from Portugal who is not listed by community. A gap is a gap, never zero.', src: 'Source: Ministry of Agriculture, Fisheries and Food (MAPA), INFOLAC: declarations of raw milk deliveries to first buyers.', mapAlt: 'Map of Spanish autonomous communities coloured by the chosen measure' },
    fr: { tabUS: 'États-Unis', tabCA: 'Espagne (lait, INFOLAC)', title: 'Lait cru en Espagne : livraisons, prix et qualité', sub: 'Livraisons mensuelles de lait cru aux premiers acheteurs, prix moyen déclaré, matière grasse et protéines, et éleveurs, par communauté autonome. Données du ministère espagnol de l’Agriculture, de la Pêche et de l’Alimentation (MAPA, INFOLAC), telles que publiées.',
      item: 'Série', measure: 'Chiffre', period: 'Mois', prod: 'Tonnes', price: '€ par litre', pct: 'Pourcentage', n: 'Nombre', ca: 'Espagne', vsPrev: 'par rapport au même mois un an plus tôt', hist: 'Évolution nationale', prov: 'Par communauté autonome', share: 'Part de l’Espagne', value: 'Valeur', change: 'Variation', province: 'Communauté', pick: 'Sélectionnez une communauté (carte ou tableau) pour la comparer à l’Espagne.', clear: 'Retirer la communauté', open: 'Profil', noData: 'Aucune donnée disponible.', noProv: 'Aucun chiffre publié pour cette série et ce mois.', last: 'Dernier mois',
      note: 'Les données proviennent des déclarations obligatoires de livraisons de lait cru aux premiers acheteurs (INFOLAC) et le MAPA précise qu’elles ne sont pas consolidées : des rapports ultérieurs peuvent les réviser et le dernier prévaut. Le prix est le montant moyen déclaré (moyenne pondérée, avec bonus et pénalités de qualité, hors TVA et transport). Prix, acheteurs et lait biologique ne sont publiés qu’au niveau national. Le lait est attribué à la communauté de l’éleveur. Chaque rapport couvre 12 mois : l’historique s’accumule (prix depuis janvier 2022, livraisons depuis septembre 2024, le reste par communauté depuis septembre 2025). En septembre 2025 le total inclut un éleveur du Portugal absent du détail par communauté. Un manque est un manque, jamais zéro.', src: 'Source : ministère de l’Agriculture, de la Pêche et de l’Alimentation (MAPA), INFOLAC : déclarations de livraisons de lait cru aux premiers acheteurs.', mapAlt: 'Carte des communautés autonomes d’Espagne colorée selon le chiffre choisi' },
    it: { tabUS: 'Stati Uniti', tabCA: 'Spagna (latte, INFOLAC)', title: 'Latte crudo in Spagna: consegne, prezzo e qualità', sub: 'Consegne mensili di latte crudo ai primi acquirenti, prezzo medio dichiarato, grasso e proteine, e allevatori, per comunità autonoma. Dati del ministero spagnolo dell’Agricoltura, della Pesca e dell’Alimentazione (MAPA, INFOLAC), come pubblicati.',
      item: 'Serie', measure: 'Dato', period: 'Mese', prod: 'Tonnellate', price: '€ al litro', pct: 'Percentuale', n: 'Numero', ca: 'Spagna', vsPrev: 'rispetto allo stesso mese dell’anno prima', hist: 'Andamento nazionale', prov: 'Per comunità autonoma', share: 'Peso sulla Spagna', value: 'Valore', change: 'Variazione', province: 'Comunità', pick: 'Seleziona una comunità (mappa o tabella) per confrontarla con la Spagna.', clear: 'Rimuovi la comunità', open: 'Profilo', noData: 'Nessun dato disponibile.', noProv: 'Nessun dato pubblicato per questa serie e questo mese.', last: 'Ultimo mese',
      note: 'I dati provengono dalle dichiarazioni obbligatorie di consegne di latte crudo ai primi acquirenti (INFOLAC) e il MAPA avverte che non sono consolidati: rapporti successivi possono rivederli e prevale l’ultimo. Il prezzo è l’importo medio dichiarato (media ponderata, con bonus e penalità di qualità, esclusi IVA e trasporto). Prezzo, acquirenti e latte biologico sono pubblicati solo a livello nazionale. Il latte è attribuito alla comunità dell’allevatore. Ogni rapporto copre 12 mesi, quindi lo storico si accumula (prezzo da gennaio 2022, consegne da settembre 2024, il resto per comunità da settembre 2025). A settembre 2025 il totale include un allevatore del Portogallo non elencato per comunità. Un vuoto è un vuoto, mai zero.', src: 'Fonte: Ministero dell’Agricoltura, della Pesca e dell’Alimentazione (MAPA), INFOLAC: dichiarazioni di consegne di latte crudo ai primi acquirenti.', mapAlt: 'Mappa delle comunità autonome spagnole colorata in base al dato scelto' }
  };
  var items = ITEMS.map(function (i) { return { id: i[0], label: i[1] }; });
  function pairs(a, per) { var o = []; for (var i = 0; i < a.length; i++) if (a[i] !== null && a[i] !== undefined) o.push([per[i], a[i]]); return o.length ? o : null; }
  function series(D, prov, id) {
    var d = D.doc, per = d.periods;
    if (prov === 'ES') { var n = d.national[id === 'production' ? 'deliveries' : id]; return n ? pairs(n, per) : null; }
    var slug = D.slug[prov], c = slug && d.ccaa[slug]; return c && c[id] ? pairs(c[id], per) : null;
  }
  window.GNMilk = window.CAExplorer.create({
    id: 'gn-esl', tabsHost: 'gn-ca-tabs', usBody: 'gn-body', usExtra: '#cof, #nd, #nl', country: 'ES', tabKey: 'ES-INFOLAC', nat: 'ES', map: 'DEHESA_ES_CCAA', noRegionLink: true, texts: T, items: items, defaultItem: 'production', defaultMeasure: 'prod', cite: 'mapa_es',
    load: function () {
      return fetch('data/spain-milk/infolac.json').then(function (r) { return r.ok ? r.json() : null; }).catch(function () { return null; }).then(function (d) {
        if (!d || !d.periods) return null;
        var D = { doc: d, provinces: { ES: 1 }, slug: {} }; Object.keys(d.ccaa).forEach(function (s) { if (CODE[s]) { D.provinces[CODE[s]] = 1; D.slug[CODE[s]] = s; } }); return D;
      });
    },
    pname: function (id, i) { var N = window.DehesaRegionNames && window.DehesaRegionNames.ES, v = N && N[id]; if (!v) return id; var p = v.split('|'), L = { 0: 1, 1: 0, 2: 2, 3: 3 }[i]; return p[L] || p[0]; },
    measures: function (D, id) { return series(D, 'ES', id) ? [MEAS[id]] : []; },
    series: series,
    fmt: function (m, v) {
      var l = window.DehesaShared.getLang(), d = function (x, n) { try { return x.toLocaleString(l, { minimumFractionDigits: n, maximumFractionDigits: n }); } catch (e) { return x.toFixed(n); } };
      if (m === 'price') return d(v, 3) + ' €/l'; if (m === 'pct') return d(v, 2) + ' %'; if (m === 'n') return d(v, 0);
      return v >= 1000 ? d(v / 1000, 1) + ' kt' : d(v, 0) + ' t';
    },
    chartX: function (x) { var d = new Date(x); try { return d.toLocaleDateString(window.DehesaShared.getLang(), { month: 'short', year: '2-digit', timeZone: 'UTC' }); } catch (e) { return String(d.getUTCFullYear()); } },
    chartV: function (m, v) { var l = window.DehesaShared.getLang(), d = function (x, n) { try { return x.toLocaleString(l, { minimumFractionDigits: n, maximumFractionDigits: n }); } catch (e) { return x.toFixed(n); } }; return m === 'price' ? d(v, 3) : m === 'pct' ? d(v, 2) : d(v, 0); },
    yTitle: function (m) { return m === 'price' ? '€/l' : m === 'pct' ? '%' : m === 'n' ? '' : 't'; },
    shareMeasure: function (m) { return m === 'prod' || m === 'n'; }
  });
})();
