/* Dehesa Index — Metodología (4 idiomas). Todo lo que afirma esta página describe lo que hace el código y los datos de data/. */
(function () {
  'use strict';
  var STRINGS = {
    es: {
      title: 'Metodología',
      sub: 'Cómo se verifican, fechan y convierten los datos, y cómo se calcula el índice compuesto.',
      sections: [
        { h: 'Principio: solo datos verificables', p: ['Cada cifra del panel viene de una fuente oficial o abierta, con su fecha y un enlace para comprobarla. Si no hay una serie trazable, no se muestra ningún valor: no rellenamos huecos con estimaciones ni con datos de muestra.'] },
        { h: 'Qué significan las etiquetas', id: 'etiquetas', ul: [
          { b: 'REAL.', t: 'Dato verificado en su fuente oficial, con fecha de observación y de publicación.' },
          { b: 'NO COMPARABLE.', t: 'El dato es real, pero su definición no equivale a la del otro mercado. Ejemplos: el precio de EE. UU. de cerdo, vacuno y pollo es en peso vivo, frente a la canal de la UE; los fertilizantes de la UE son índices agregados de nutriente, no un producto concreto. Se muestra con la etiqueta y no entra en comparaciones directas.' },
          { b: 'PENDIENTE.', t: 'Aún no hay una fuente verificable y con licencia adecuada. La tarjeta no muestra cifra hasta que la haya.' }
        ] },
        { h: 'Fuentes y frecuencia', ul: [
          { b: 'EE. UU. — USDA NASS (Quick Stats).', t: 'Precio recibido por el productor, mensual y nacional: trigo, maíz, arroz, leche, huevos, cerdo, vacuno y pollo. NASS publica una vez al mes; consultamos cada semana para no perder ninguna publicación.' },
          { b: 'UE — Comisión Europea, Agri-food Data Portal.', t: 'Precios semanales de mercado con España como referencia (cerdo, vacuno, cordero, pollo, huevos, cereales, aceite de oliva, azúcar, leche, harina de soja, fertilizantes). Los coeficientes por país se calculan con datos reales de la misma semana.' },
          { b: 'Reino Unido — Defra (Open Government Licence v3.0).', t: 'Leche e índices de precios agrarios, mensuales. Los precios semanales de cereales y ganado del Reino Unido los publica AHDB con términos que impiden su uso automático; por eso esas tarjetas figuran como pendientes.' },
          { b: 'Eurostat.', t: 'Índices de precios agrarios de la UE, trimestrales.' },
          { b: 'Energía y fertilizantes.', t: 'Diésel de EE. UU. (EIA, semanal) y de la UE (Oil Bulletin, semanal); urea (Banco Mundial, mensual).' },
          { b: 'Clima — NASA POWER.', t: 'Lluvia y temperatura mensuales (reanálisis MERRA-2) en 12 puntos representativos de regiones productoras, comparadas con la media 2001-2020 del mismo mes, con histórico mensual desde 2000. Los meses más recientes los calcula NASA con otro flujo de procesamiento (GEOS-IT) que puede revisarse. Es contexto climático (una celda de unos 50 km, no una estación ni la región entera); no predice cosechas ni precios.' },
          { b: 'Oferta y demanda — USDA PSD.', t: 'Balances por país y campaña de cereales, oleaginosas, carne, leche y azúcar (licencia CC BY 4.0), mensuales con el WASDE.' },
          { b: 'Harina de soja de EE. UU. — USDA AMS.', t: 'Precio semanal de la harina de soja (Iowa, FOB, 46,5-48 % de proteína) del informe 3511 de USDA AMS Market News, en tonelada corta. Es un mercado regional, no un futuro; la comparación con Europa es orientativa.' },
          { b: 'Tipos de cambio.', t: 'Cotizaciones de referencia del Banco Central Europeo, cada día laborable.' }
        ] },
        { h: 'Fechas: observación y publicación', p: ['Cada dato lleva dos fechas: la de observación (el periodo al que se refiere) y la de publicación (cuándo lo publicó la fuente). Algunas fuentes no informan de su fecha de publicación; en ese caso registramos el día en que recogimos el dato por primera vez y lo anotamos en la ficha.'] },
        { h: 'Monedas y unidades', p: ['Los datos se guardan en la moneda y la unidad de la fuente. Para compararlos, el panel los convierte con el tipo de cambio de referencia del BCE del último día laborable y con factores de unidad fijos y visibles (por ejemplo, 1 docena de huevos = 0,6804 kg). Una conversión no vuelve comparable un dato que no lo es.'] },
        { h: 'Estado de los cultivos', id: 'cultivos', p: ['Viene del informe semanal Crop Progress de USDA NASS (API Quick Stats), que se publica los lunes por la tarde, hora de EE. UU., aproximadamente de abril a noviembre (el trigo de invierno también se valora en otoño). La valoración es el porcentaje de superficie en cada categoría —muy mala, mala, regular, buena, excelente—; "buena + excelente" es la suma de las dos últimas. La dan corresponsales locales de NASS, así que es subjetiva y no es una previsión de cosecha ni de precios. El avance es el porcentaje de superficie que ha llegado a cada etapa (sembrado, cosechado...). La media de 5 años y la comparación con el año pasado son cálculo propio de Dehesa Index: se toma la misma fecha en las campañas anteriores, interpolando entre informes semanales, y solo se calcula si hay dato en al menos 4 de las 5 campañas. Una etapa ya completada (100 %) se mantiene en 100 % en las semanas siguientes. Los valores que NASS no publica no se rellenan.'] },
        { h: 'Mercados USDA', id: 'mercados', p: ['Precios de mercado de EE. UU. tal como los publica USDA AMS Market News (API MARS): piensos y subproductos, etanol y coproductos, granos, oleaginosas, legumbres, arroz, aves, huevos, carne y subproductos, cerdos de recría, ganado de venta directa, heno y lácteos. Se leen a diario de lunes a viernes (algunos informes son semanales). Cada serie es una combinación fija de producto, calidad, lugar y unidad del propio informe; si en un mismo día o semana hay dos cifras distintas para la misma serie, ese punto se descarta en lugar de adivinar. No se convierten monedas ni unidades. Cuando el informe da un precio medio se muestra ese; cuando solo da mínimo y máximo se muestra el punto medio, marcado con ≈. Son datos oficiales pero no son un índice de Dehesa Index ni son comparables con los europeos: cada informe tiene su propia base de lugar, calidad y entrega.'] },
        { h: 'Exportaciones de EE. UU.', id: 'exportaciones', p: ['Las ventas de exportación semanales vienen del informe Export Sales Reporting de USDA FAS (API abierta de FAS), que se publica los jueves y cubre trigo, maíz, sorgo, cebada, soja y derivados, algodón, arroz, vacuno y cerdo. Las cifras son toneladas métricas (algodón en balas) que las empresas declaran a USDA: «exportado» son los embarques acumulados de la campaña, «ventas pendientes» las ya cerradas y sin embarcar, y «compromiso total» su suma. Los totales suman los destinos publicados y el agregado de la UE cuenta como un solo destino. El comercio mensual por país viene de USDA FAS GATS, con datos del Census Bureau de EE. UU.: solo comercio de EE. UU. con cada país (no flujos entre terceros), en dólares corrientes y, cuando el Census mide en kilos, en toneladas; se incluyen los socios agrarios principales, no todos los países. Los grupos de producto se forman con capítulos arancelarios (HS) y son aproximados. Los dos últimos meses pueden revisarse. Datos públicos del Gobierno de EE. UU.; no se convierten ni se comparan con precios.'] },
        { h: 'Ficha de producto', id: 'producto', p: ['La ficha de producto (trigo, maíz, soja, arroz, vacuno, cerdo, leche y pollo) no crea datos nuevos: reúne en una página lo que ya publica cada bloque, con su fuente y su unidad (precios, oferta y demanda, ventas de exportación, comercio por país, cultivo o existencias de ganado, sequía y costes). Los mercados no se convierten ni se suman: el precio de EE. UU. de vacuno y cerdo es peso vivo y no equivale al precio en canal europeo. La media de sequía ponderada por producción es un cálculo de Dehesa con los 5 mayores estados productores y expresa el porcentaje de superficie del estado en sequía moderada o peor, no de la superficie cultivada. Si un bloque no tiene dato, no aparece. En soja, el precio mostrado es el de la harina de soja (no del grano).'] },
        { h: 'Precios de la UE', id: 'europa', p: ['La página Precios de la UE reúne todas las series de precios que publica la Comisión Europea en su Agri-food Data Portal (API pública): cereales, oleaginosas y tortas, lácteos, vacuno, cerdo, pollo, huevos, cordero, arroz, leche cruda, aceite de oliva, azúcar, vino y fertilizantes, país por país. Cada línea es el precio que publica el portal, en su propia unidad (€/t, €/100 kg, €/hl…), sin convertir y sin promediar mercados; si un país publica varios mercados, cada uno se muestra por separado, y las filas que no están en euros se descartan. «UE» es un agregado calculado por la Comisión, no por Dehesa Index. El portal no publica la fecha en que sube cada dato ni los precios de todos los países cada semana, por eso algunos países tienen huecos. Se actualiza los jueves; el histórico llega hasta 2015 en la mayoría de familias (desde 2021 en cereales y vacuno) y, en azúcar, vino y fertilizantes, hasta donde publica la fuente.'] },
        { h: 'Monitor de sequía de EE. UU.', id: 'sequia', p: ['El porcentaje de superficie de cada estado en sequía viene del U.S. Drought Monitor, elaborado por el National Drought Mitigation Center (Universidad de Nebraska-Lincoln) con USDA y NOAA. Se publica los jueves con el mapa válido al martes anterior. Se muestran las categorías D0–D4 tal como las publica la API (acumuladas: D1 incluye D2, D3 y D4); las variaciones se calculan restando porcentajes (puntos porcentuales) frente a la semana anterior y frente a 52 semanas antes. Es una valoración, no un pronóstico.'] },
        { h: 'Ganadería y lácteo de EE. UU.', id: 'ganaderia', p: ['Los censos de cerdos y vacuno, la producción de leche por estado y las existencias en frío vienen de USDA NASS (Quick Stats: Hogs and Pigs, Cattle, Milk Production y Cold Storage) y se muestran tal como se publican, en su unidad original. Las encuestas de cerdos son trimestrales, las de vacuno semestrales, y la leche y las existencias en frío mensuales. Los datos por estado solo se muestran cuando NASS los publica para el mismo periodo. Las variaciones son cambios porcentuales simples entre dos datos publicados.'] },
        { h: 'Costes de los insumos agrarios de EE. UU.', id: 'insumos', p: ['Los índices de precios pagados por los agricultores (fertilizantes, combustibles, piensos, agroquímicos, semillas, maquinaria, servicios, salarios, alquiler e intereses) vienen de USDA NASS, Agricultural Prices (Quick Stats), con base 2011 = 100. NASS ya no publica precios absolutos de fertilizantes ni combustibles, así que se muestran los índices oficiales; no se estiman precios por tonelada ni por litro. Las variaciones son porcentuales entre índices publicados.'] },
        { h: 'Alimentos, costes y renta agraria de EE. UU.', id: 'costes', p: ['Los precios de alimentos (previsión de IPC e IPP), los costes y rentabilidad por cultivo y ganado, la previsión de costes y la renta agraria vienen de los ficheros oficiales del USDA Economic Research Service (Food Price Outlook, Commodity Costs and Returns, Cost of Production Forecasts y Farm Income and Wealth Statistics). Se muestran tal como se publican; el último año de renta agraria y las previsiones de precios y costes son previsiones del ERS. El punto de equilibrio por unidad se calcula en Dehesa dividiendo el total de costes por acre por el rendimiento por acre, y así se indica en la página.'] },
        { h: 'Rendimientos y superficie por estado de EE. UU.', id: 'rendimientos', p: ['El rendimiento por acre, la superficie sembrada y cosechada y la producción por estado vienen de USDA NASS (Quick Stats, encuestas Crop Production y Acreage), en sus unidades originales (acres, bushels, libras). Los datos por condado no están incluidos todavía. El último año puede ser una estimación o previsión de NASS hasta que se cierre la campaña; los estados sin dato publicado no se rellenan.'] },
        { h: 'Oferta y demanda', id: 'oferta-demanda', p: ['Los balances de producción, consumo, comercio y existencias vienen de USDA Foreign Agricultural Service (PSD Online, licencia CC BY 4.0) y se actualizan con el informe mensual WASDE. La campaña indicada (2025) es la que empieza ese año (2025/26); la más reciente es una previsión que USDA revisa cada mes. "Mundo" es la suma de los países de la base PSD, contando la UE una sola vez; no es una cifra publicada por USDA. Las campañas comerciales no coinciden entre países, y exportaciones e importaciones se declaran por separado, así que el comercio mundial no siempre cuadra. Las cifras van en miles de toneladas (carne en equivalente canal). Sin dato en PSD, no se pinta nada.'] },
        { h: 'Dehesa Index: el índice compuesto', id: 'indice', p: ['Es un índice mensual con base 100 en octubre de 2024, solo para el mercado de la UE. Cada serie verificada se convierte a media mensual y se reexpresa a base 100; cada grupo es la media simple de sus series; el índice es la media ponderada de los grupos: Cereales 25 %, Ganadería 25 %, Lácteos 15 %, Pienso 15 %, Fertilizantes 10 %, Energía 10 %.', 'Como cada serie se reexpresa en su propia unidad, el índice mide evolución, no es un precio y no mezcla monedas. Si una serie tiene un mes sin dato en el origen, se arrastra el mes anterior y queda declarado en el archivo de datos. EE. UU. y Reino Unido se añadirán cuando tengan al menos 24 meses de historia. El panel «Crea tu propio índice» permite cambiar los pesos y compararlos con el oficial.'] },
        { h: 'Limitaciones', ul: [
          { t: 'No son precios en tiempo real: la frecuencia la marca cada fuente (semanal, mensual o trimestral).' },
          { t: 'Los precios de EE. UU. (NASS) son al productor y los de la UE son de mercado; aunque se muestren en la misma moneda, no son siempre el mismo concepto.' },
          { t: 'Las fuentes pueden revisar sus datos o cambiar sus definiciones; reflejamos la última versión publicada.' },
          { t: 'Nada de esto es asesoramiento financiero ni de inversión.' }
        ] },
        { h: 'Datos abiertos y correcciones', p: ['Los archivos con los que se construye el panel están publicados en la carpeta de datos del sitio (JSON y CSV), con la fuente y la metodología de cada serie. Si ves un error o una definición mejorable, escríbenos a hola@dehesaindex.com.'] }
      ],
      links: [{ href: 'clima.html', t: 'Clima agrícola' }, { href: 'data/', t: 'Datos abiertos' }, { href: 'legal.html', t: 'Aviso legal y privacidad' }, { href: 'informacion.html', t: 'Información' }]
    },
    en: {
      title: 'Methodology',
      sub: 'How data is verified, dated and converted, and how the composite index is calculated.',
      sections: [
        { h: 'Principle: verifiable data only', p: ['Every figure on the dashboard comes from an official or open source, with its date and a link to check it. If there is no traceable series, no value is shown: we do not fill gaps with estimates or sample data.'] },
        { h: 'What the labels mean', id: 'etiquetas', ul: [
          { b: 'REAL.', t: 'Data verified at its official source, with observation and publication dates.' },
          { b: 'NOT COMPARABLE.', t: 'The data is real, but its definition is not equivalent to the other market’s. Examples: U.S. hog, cattle and chicken prices are live weight, versus EU carcass weight; EU fertiliser figures are aggregated nutrient indices, not a specific product. It is shown with the label and left out of direct comparisons.' },
          { b: 'PENDING.', t: 'There is no verifiable, properly licensed source yet. The card shows no figure until there is one.' }
        ] },
        { h: 'Sources and frequency', ul: [
          { b: 'U.S. — USDA NASS (Quick Stats).', t: 'Price received by farmers, monthly and national: wheat, corn, rice, milk, eggs, hogs, cattle and chicken. NASS publishes once a month; we check every week so no release is missed.' },
          { b: 'EU — European Commission, Agri-food Data Portal.', t: 'Weekly market prices with Spain as the reference (pork, beef, lamb, chicken, eggs, cereals, olive oil, sugar, milk, soya meal, fertilisers). Country coefficients are computed from real same-week data.' },
          { b: 'UK — Defra (Open Government Licence v3.0).', t: 'Milk and agricultural price indices, monthly. Weekly UK cereal and livestock prices are published by AHDB under terms that prevent automated use, so those cards are shown as pending.' },
          { b: 'Eurostat.', t: 'EU agricultural price indices, quarterly.' },
          { b: 'Energy and fertilisers.', t: 'U.S. diesel (EIA, weekly) and EU diesel (Oil Bulletin, weekly); urea (World Bank, monthly).' },
          { b: 'Climate — NASA POWER.', t: 'Monthly rainfall and temperature (MERRA-2 reanalysis) at 12 representative points in producing regions, compared with the 2001-2020 average for the same month, with monthly history since 2000. The most recent months are computed by NASA with a different processing stream (GEOS-IT) that may be revised. It is climate context (a ~50 km grid cell, not a station or the whole region); it does not forecast crops or prices.' },
          { b: 'Supply and demand — USDA PSD.', t: 'Country balances by marketing year for grains, oilseeds, meat, milk and sugar (CC BY 4.0 licence), monthly with the WASDE.' },
          { b: 'US soybean meal — USDA AMS.', t: 'Weekly soybean meal price (Iowa, FOB, 46.5-48% protein) from USDA AMS Market News report 3511, per short ton. It is a regional market, not a futures price; the comparison with Europe is indicative.' },
          { b: 'Exchange rates.', t: 'European Central Bank reference rates, every business day.' }
        ] },
        { h: 'Dates: observation and publication', p: ['Each data point carries two dates: observation (the period it refers to) and publication (when the source released it). Some sources do not report a publication date; in that case we record the day we first collected the data and note it on the card.'] },
        { h: 'Currencies and units', p: ['Data is stored in the source’s currency and unit. To compare, the dashboard converts it using the ECB reference rate of the latest business day and fixed, visible unit factors (for example, 1 dozen eggs = 0.6804 kg). A conversion does not make a non-comparable figure comparable.'] },
        { h: 'Crop conditions', id: 'cultivos', p: ['This comes from USDA NASS’s weekly Crop Progress report (Quick Stats API), published Monday afternoons U.S. time, roughly April to November (winter wheat is also rated in autumn). The rating is the share of acreage in each category — very poor, poor, fair, good, excellent —; “good + excellent” is the sum of the last two. It is given by local NASS reporters, so it is subjective and not a crop or price forecast. Progress is the share of acreage that has reached each stage (planted, harvested...). The 5-year average and the year-ago comparison are Dehesa Index’s own calculation: the same date in earlier seasons is taken, interpolating between weekly reports, and only computed if at least 4 of the 5 seasons have data. A completed stage (100 %) stays at 100 % in later weeks. Values NASS does not publish are not filled in.'] },
        { h: 'USDA markets', id: 'mercados', p: ['U.S. market prices as published by USDA AMS Market News (MARS API): feed and by-products, ethanol and co-products, grains, oilseeds, pulses, rice, poultry, eggs, meat and by-products, feeder pigs, direct cattle, hay and dairy. They are read every weekday (some reports are weekly). Each series is a fixed combination of product, quality, place and unit from the report itself; if a single day or week has two different figures for the same series, that point is dropped rather than guessed. Currencies and units are not converted. When a report gives an average price that is shown; when it only gives a minimum and maximum the midpoint is shown, flagged with ≈. The data is official but is not a Dehesa Index measure and is not comparable with European data: each report has its own basis of place, quality and delivery.'] },
        { h: 'U.S. exports', id: 'exportaciones', p: ['Weekly export sales come from USDA FAS’s Export Sales Reporting (FAS open API), released on Thursdays and covering wheat, corn, sorghum, barley, soybeans and products, cotton, rice, beef and pork. Figures are metric tons (cotton in bales) reported by companies to USDA: “exported” is accumulated shipments in the marketing year, “outstanding sales” are sales already made but not shipped, and “total commitment” is their sum. Totals add up the published destinations and the EU aggregate counts as one destination. Monthly trade by country comes from USDA FAS GATS, using U.S. Census Bureau data: only U.S. trade with each country (not flows between third countries), in current dollars and, where the Census measures in kilograms, in tonnes; the main agricultural partners are included, not every country. Product groups are built from tariff (HS) chapters and are approximate. The last two months may be revised. Public U.S. Government data; not converted or compared with prices.'] },
        { h: 'Product page', id: 'producto', p: ['The product page (wheat, corn, soybeans, rice, beef, pork, milk and chicken) creates no new data: it gathers on one page what each block already publishes, with its source and unit (prices, supply and demand, export sales, trade by country, crop or livestock inventories, drought and costs). Markets are neither converted nor added together: the U.S. beef and pork price is live weight and is not equivalent to the European carcass price. The production-weighted drought average is a Dehesa calculation over the 5 largest producing states and expresses the share of each state\'s area in moderate drought or worse, not of the cropped area. A block with no data does not appear. For soybeans, the price shown is soybean meal, not the beans.'] },
        { h: 'EU prices', id: 'europa', p: ['The EU prices page gathers every price series that the European Commission publishes in its Agri-food Data Portal (public API): cereals, oilseeds and meals, dairy, beef, pigmeat, poultry, eggs, lamb, rice, raw milk, olive oil, sugar, wine and fertilisers, country by country. Each line is the price the portal publishes, in its own unit (€/t, €/100 kg, €/hl…), not converted and with no markets averaged; when a country publishes several markets, each is shown separately, and rows that are not in euros are dropped. “EU” is an aggregate calculated by the Commission, not by Dehesa Index. The portal does not publish the date each figure is released, nor every country every week, so some countries have gaps. It is updated on Thursdays; history goes back to 2015 for most families (2021 for cereals and beef) and, for sugar, wine and fertilisers, as far as the source publishes.'] },
        { h: 'U.S. Drought Monitor', id: 'sequia', p: ['The share of each state in drought comes from the U.S. Drought Monitor, produced by the National Drought Mitigation Center (University of Nebraska-Lincoln) with USDA and NOAA. It is released on Thursdays with the map valid the previous Tuesday. Categories D0–D4 are shown as published by the API (cumulative: D1 includes D2, D3 and D4); changes are computed by subtracting percentages (percentage points) against the previous week and 52 weeks earlier. It is an assessment, not a forecast.'] },
        { h: 'U.S. livestock and dairy', id: 'ganaderia', p: ['Hog and cattle inventories, milk production by state and cold-storage stocks come from USDA NASS (Quick Stats: Hogs and Pigs, Cattle, Milk Production and Cold Storage) and are shown as published, in their original unit. Hog surveys are quarterly, cattle inventories semi-annual, and milk and cold storage monthly. State data are shown only when NASS publishes them for the same period. Changes are simple percentage changes between two published figures.'] },
        { h: 'U.S. farm input costs', id: 'insumos', p: ['Prices-paid indexes for farmers (fertilizer, fuel, feed, agrochemicals, seed, machinery, services, wages, rent and interest) come from USDA NASS, Agricultural Prices (Quick Stats), with 2011 = 100. NASS no longer publishes absolute fertilizer or fuel prices, so the official indexes are shown; no per-tonne or per-litre prices are estimated. Changes are percentage changes between published indexes.'] },
        { h: 'U.S. food prices, costs and farm income', id: 'costes', p: ['Food prices (CPI and PPI forecasts), costs and returns by crop and livestock, cost forecasts and farm income come from official USDA Economic Research Service files (Food Price Outlook, Commodity Costs and Returns, Cost of Production Forecasts and Farm Income and Wealth Statistics). They are shown as published; the latest farm-income year and the price and cost forecasts are ERS forecasts. The per-unit break-even is computed by Dehesa as total cost per acre divided by yield per acre, and is labelled as such on the page.'] },
        { h: 'U.S. yields and acreage by state', id: 'rendimientos', p: ['Yield per acre, planted and harvested area and production by state come from USDA NASS (Quick Stats, Crop Production and Acreage surveys), in their original units (acres, bushels, pounds). County data are not included yet. The latest year may be a NASS estimate or forecast until the crop year closes; states without a published figure are not filled in.'] },
        { h: 'Supply and demand', id: 'oferta-demanda', p: ['Production, consumption, trade and stock balances come from the USDA Foreign Agricultural Service (PSD Online, CC BY 4.0 licence) and are updated with the monthly WASDE report. The year shown (2025) is the marketing year that starts that year (2025/26); the latest one is a forecast USDA revises every month. "World" is the sum of the countries in the PSD database, counting the EU once; it is not a figure published by USDA. Marketing years differ between countries, and exports and imports are reported separately, so world trade does not always balance. Figures are in thousand tonnes (meat in carcass-weight equivalent). Without PSD data, nothing is drawn.'] },
        { h: 'Dehesa Index: the composite index', id: 'indice', p: ['A monthly index with base 100 in October 2024, for the EU market only. Each verified series is converted to a monthly average and rebased to 100; each group is the simple mean of its series; the index is the weighted mean of the groups: Cereals 25%, Livestock 25%, Dairy 15%, Feed 15%, Fertilisers 10%, Energy 10%.', 'Because each series is rebased in its own unit, the index measures evolution, is not a price and does not mix currencies. If a series has a month missing at the source, the previous month is carried forward and declared in the data file. The U.S. and UK will be added once they have at least 24 months of history. The “Build your own index” panel lets you change the weights and compare them with the official index.'] },
        { h: 'Limitations', ul: [
          { t: 'These are not real-time prices: frequency is set by each source (weekly, monthly or quarterly).' },
          { t: 'U.S. prices (NASS) are farm-gate and EU prices are market prices; even shown in the same currency, they are not always the same concept.' },
          { t: 'Sources may revise their data or change definitions; we show the latest published version.' },
          { t: 'Nothing here is financial or investment advice.' }
        ] },
        { h: 'Open data and corrections', p: ['The files behind the dashboard are published in the site’s data folder (JSON and CSV), with the source and methodology of each series. If you spot an error or a definition that could be better, write to hola@dehesaindex.com.'] }
      ],
      links: [{ href: 'clima.html', t: 'Agricultural climate' }, { href: 'data/', t: 'Open data' }, { href: 'legal.html', t: 'Legal notice & privacy' }, { href: 'informacion.html', t: 'Information' }]
    },
    fr: {
      title: 'Méthodologie',
      sub: 'Comment les données sont vérifiées, datées et converties, et comment l’indice composite est calculé.',
      sections: [
        { h: 'Principe : uniquement des données vérifiables', p: ['Chaque chiffre du tableau de bord provient d’une source officielle ou ouverte, avec sa date et un lien pour le vérifier. Sans série traçable, aucune valeur n’est affichée : nous ne comblons pas les trous avec des estimations ni des données fictives.'] },
        { h: 'Signification des étiquettes', id: 'etiquettes', ul: [
          { b: 'RÉEL.', t: 'Donnée vérifiée à sa source officielle, avec date d’observation et de publication.' },
          { b: 'NON COMPARABLE.', t: 'La donnée est réelle, mais sa définition n’équivaut pas à celle de l’autre marché. Exemples : les prix américains du porc, du bovin et du poulet sont en poids vif, contre le poids carcasse dans l’UE ; les engrais de l’UE sont des indices agrégés d’éléments nutritifs. Elle est affichée avec l’étiquette et exclue des comparaisons directes.' },
          { b: 'EN ATTENTE.', t: 'Il n’existe pas encore de source vérifiable et correctement licenciée. La fiche n’affiche aucun chiffre tant qu’il n’y en a pas.' }
        ] },
        { h: 'Sources et fréquence', ul: [
          { b: 'États-Unis — USDA NASS (Quick Stats).', t: 'Prix reçu par l’agriculteur, mensuel et national : blé, maïs, riz, lait, œufs, porc, bovin et poulet. NASS publie une fois par mois ; nous consultons chaque semaine pour ne manquer aucune publication.' },
          { b: 'UE — Commission européenne, Agri-food Data Portal.', t: 'Prix de marché hebdomadaires avec l’Espagne comme référence (porc, bœuf, agneau, poulet, œufs, céréales, huile d’olive, sucre, lait, tourteau de soja, engrais). Les coefficients par pays sont calculés avec des données réelles de la même semaine.' },
          { b: 'Royaume-Uni — Defra (Open Government Licence v3.0).', t: 'Lait et indices des prix agricoles, mensuels. Les prix hebdomadaires britanniques des céréales et du bétail sont publiés par l’AHDB à des conditions qui interdisent l’usage automatisé ; ces fiches restent donc en attente.' },
          { b: 'Eurostat.', t: 'Indices des prix agricoles de l’UE, trimestriels.' },
          { b: 'Énergie et engrais.', t: 'Diesel américain (EIA, hebdomadaire) et de l’UE (Oil Bulletin, hebdomadaire) ; urée (Banque mondiale, mensuelle).' },
          { b: 'Climat — NASA POWER.', t: 'Pluie et température mensuelles (réanalyse MERRA-2) en 12 points représentatifs de régions productrices, comparées à la moyenne 2001-2020 du même mois, avec un historique mensuel depuis 2000. Les mois les plus récents sont calculés par la NASA avec un autre flux de traitement (GEOS-IT), susceptible d’être révisé. C’est un contexte climatique (une maille d’environ 50 km, pas une station ni la région entière) ; il ne prévoit ni récoltes ni prix.' },
          { b: 'Offre et demande — USDA PSD.', t: 'Bilans par pays et par campagne des céréales, oléagineux, viandes, lait et sucre (licence CC BY 4.0), mensuels avec le WASDE.' },
          { b: 'Tourteau de soja des États-Unis — USDA AMS.', t: 'Prix hebdomadaire du tourteau de soja (Iowa, FOB, 46,5-48 % de protéines) du rapport 3511 d’USDA AMS Market News, en tonne courte. C’est un marché régional, pas un contrat à terme ; la comparaison avec l’Europe est indicative.' },
          { b: 'Taux de change.', t: 'Taux de référence de la Banque centrale européenne, chaque jour ouvré.' }
        ] },
        { h: 'Dates : observation et publication', p: ['Chaque donnée porte deux dates : l’observation (la période concernée) et la publication (quand la source l’a diffusée). Certaines sources n’indiquent pas de date de publication ; nous enregistrons alors le jour où nous avons collecté la donnée pour la première fois et l’indiquons sur la fiche.'] },
        { h: 'Devises et unités', p: ['Les données sont conservées dans la devise et l’unité de la source. Pour les comparer, le tableau de bord les convertit avec le taux de référence de la BCE du dernier jour ouvré et des facteurs d’unité fixes et visibles (par exemple, 1 douzaine d’œufs = 0,6804 kg). Une conversion ne rend pas comparable une donnée qui ne l’est pas.'] },
        { h: 'État des cultures', id: 'cultivos', p: ['Ces données viennent du rapport hebdomadaire Crop Progress de l’USDA NASS (API Quick Stats), publié le lundi après-midi, heure américaine, environ d’avril à novembre (le blé d’hiver est aussi noté à l’automne). La notation est la part de la surface dans chaque catégorie — très mauvais, mauvais, moyen, bon, excellent — ; « bon + excellent » est la somme des deux dernières. Elle est donnée par des correspondants locaux du NASS : elle est donc subjective et ne constitue pas une prévision de récolte ni de prix. L’avancement est la part de la surface ayant atteint chaque stade (semé, récolté...). La moyenne 5 ans et la comparaison avec l’an dernier sont un calcul propre à Dehesa Index : on prend la même date dans les campagnes précédentes, par interpolation entre rapports hebdomadaires, et seulement si au moins 4 des 5 campagnes ont une donnée. Un stade terminé (100 %) reste à 100 % les semaines suivantes. Les valeurs que le NASS ne publie pas ne sont pas complétées.'] },
        { h: 'Marchés USDA', id: 'mercados', p: ['Prix de marché américains tels que publiés par USDA AMS Market News (API MARS) : aliments et sous-produits, éthanol et coproduits, céréales, oléagineux, légumineuses, riz, volaille, œufs, viande et sous-produits, porcelets, bétail en vente directe, foin et produits laitiers. Ils sont lus chaque jour ouvré (certains rapports sont hebdomadaires). Chaque série est une combinaison fixe de produit, qualité, lieu et unité du rapport lui-même ; si un même jour ou une même semaine porte deux chiffres différents pour la même série, ce point est écarté plutôt que deviné. Les devises et les unités ne sont pas converties. Quand un rapport donne un prix moyen, il est affiché ; quand il ne donne que minimum et maximum, le milieu est affiché, signalé par ≈. Les données sont officielles mais ne constituent pas un indicateur de Dehesa Index et ne sont pas comparables aux données européennes : chaque rapport a sa propre base de lieu, qualité et livraison.'] },
        { h: 'Exportations américaines', id: 'exportaciones', p: ['Les ventes à l’exportation hebdomadaires viennent du rapport Export Sales Reporting de l’USDA FAS (API ouverte de la FAS), publié le jeudi, qui couvre le blé, le maïs, le sorgho, l’orge, le soja et ses dérivés, le coton, le riz, le bœuf et le porc. Les chiffres sont des tonnes métriques (coton en balles) déclarées par les entreprises à l’USDA : « exporté » correspond aux expéditions cumulées de la campagne, « ventes en attente » aux ventes conclues mais non expédiées, et « engagement total » à leur somme. Les totaux additionnent les destinations publiées et l’agrégat UE compte comme une seule destination. Le commerce mensuel par pays vient de l’USDA FAS GATS, à partir des données du Census Bureau : uniquement le commerce des États-Unis avec chaque pays (pas les flux entre pays tiers), en dollars courants et, lorsque le Census mesure en kilos, en tonnes ; les principaux partenaires agricoles sont inclus, pas tous les pays. Les groupes de produits reposent sur les chapitres tarifaires (SH) et sont approximatifs. Les deux derniers mois peuvent être révisés. Données publiques du gouvernement américain ; ni converties ni comparées aux prix.'] },
        { h: 'Fiche produit', id: 'producto', p: ['La fiche produit (blé, maïs, soja, riz, bœuf, porc, lait et poulet) ne crée pas de données nouvelles : elle réunit sur une page ce que publie déjà chaque bloc, avec sa source et son unité (prix, offre et demande, ventes à l’exportation, commerce par pays, culture ou effectifs de bétail, sécheresse et coûts). Les marchés ne sont ni convertis ni additionnés : le prix américain du bœuf et du porc est en poids vif et n’équivaut pas au prix en carcasse européen. La moyenne de sécheresse pondérée par la production est un calcul de Dehesa sur les 5 premiers États producteurs et exprime la part de la surface de l’État en sécheresse modérée ou pire, pas de la surface cultivée. Un bloc sans données n’apparaît pas. Pour le soja, le prix affiché est celui du tourteau, pas du grain.'] },
        { h: 'Prix de l’UE', id: 'europa', p: ['La page Prix de l’UE réunit toutes les séries de prix publiées par la Commission européenne dans son Agri-food Data Portal (API publique) : céréales, oléagineux et tourteaux, produits laitiers, bovins, porc, volaille, œufs, agneau, riz, lait cru, huile d’olive, sucre, vin et engrais, pays par pays. Chaque courbe est le prix publié par le portail, dans son unité (€/t, €/100 kg, €/hl…), sans conversion ni moyenne entre marchés ; si un pays publie plusieurs marchés, chacun est affiché séparément, et les lignes qui ne sont pas en euros sont écartées. « UE » est un agrégat calculé par la Commission, pas par Dehesa Index. Le portail ne publie pas la date de mise en ligne de chaque valeur, ni tous les pays chaque semaine : certains pays ont donc des trous. Mise à jour le jeudi ; l’historique remonte à 2015 pour la plupart des familles (2021 pour les céréales et les bovins) et, pour le sucre, le vin et les engrais, aussi loin que la source le publie.'] },
        { h: 'Moniteur de sécheresse américain', id: 'sequia', p: ['La part de chaque État en sécheresse vient du U.S. Drought Monitor, produit par le National Drought Mitigation Center (Université du Nebraska-Lincoln) avec l’USDA et la NOAA. Il est publié le jeudi avec la carte valable le mardi précédent. Les catégories D0–D4 sont affichées telles que publiées par l’API (cumulatives : D1 inclut D2, D3 et D4) ; les variations sont calculées en soustrayant les pourcentages (points de pourcentage) par rapport à la semaine précédente et à 52 semaines avant. C’est une évaluation, pas une prévision.'] },
        { h: 'Élevage et lait aux États-Unis', id: 'ganaderia', p: ['Les inventaires de porcs et de bovins, la production de lait par État et les stocks frigorifiques viennent de l’USDA NASS (Quick Stats : Hogs and Pigs, Cattle, Milk Production et Cold Storage) et sont présentés tels que publiés, dans leur unité d’origine. Les enquêtes porcines sont trimestrielles, celles des bovins semestrielles, et le lait et les stocks frigorifiques mensuels. Les données par État ne sont affichées que si NASS les publie pour la même période. Les variations sont de simples variations en pourcentage entre deux chiffres publiés.'] },
        { h: 'Coûts des intrants agricoles aux États-Unis', id: 'insumos', p: ['Les indices des prix payés par les agriculteurs (engrais, carburants, aliments du bétail, agrochimie, semences, machines, services, salaires, fermages et intérêts) viennent de l’USDA NASS, Agricultural Prices (Quick Stats), base 2011 = 100. NASS ne publie plus de prix absolus d’engrais ni de carburants ; on affiche donc les indices officiels, sans estimer de prix à la tonne ou au litre. Les variations sont des variations en pourcentage entre indices publiés.'] },
        { h: 'Prix alimentaires, coûts et revenu agricole aux États-Unis', id: 'costes', p: ['Les prix alimentaires (prévisions IPC et IPP), les coûts et rendements par culture et élevage, les prévisions de coûts et le revenu agricole viennent des fichiers officiels de l’USDA Economic Research Service (Food Price Outlook, Commodity Costs and Returns, Cost of Production Forecasts et Farm Income and Wealth Statistics). Ils sont présentés tels que publiés ; la dernière année de revenu agricole et les prévisions de prix et de coûts sont des prévisions de l’ERS. Le seuil de rentabilité par unité est calculé par Dehesa (coût total par acre divisé par le rendement par acre) et signalé comme tel sur la page.'] },
        { h: 'Rendements et surfaces par État américain', id: 'rendimientos', p: ['Le rendement par acre, les surfaces semées et récoltées et la production par État viennent de l’USDA NASS (Quick Stats, enquêtes Crop Production et Acreage), dans leurs unités d’origine (acres, bushels, livres). Les données par comté ne sont pas encore incluses. La dernière année peut être une estimation ou prévision de NASS tant que la campagne n’est pas close ; les États sans chiffre publié ne sont pas complétés.'] },
        { h: 'Offre et demande', id: 'oferta-demanda', p: ['Les bilans de production, consommation, commerce et stocks proviennent de l’USDA Foreign Agricultural Service (PSD Online, licence CC BY 4.0) et sont mis à jour avec le rapport mensuel WASDE. La campagne indiquée (2025) est celle qui commence cette année-là (2025/26) ; la plus récente est une prévision que l’USDA révise chaque mois. « Monde » est la somme des pays de la base PSD, l’UE comptant une fois ; ce n’est pas un chiffre publié par l’USDA. Les campagnes diffèrent selon les pays, et exportations et importations sont déclarées séparément : le commerce mondial ne s’équilibre donc pas toujours. Chiffres en milliers de tonnes (viande en équivalent carcasse). Sans donnée PSD, rien n’est tracé.'] },
        { h: 'Dehesa Index : l’indice composite', id: 'indice', p: ['Un indice mensuel en base 100 en octobre 2024, pour le seul marché de l’UE. Chaque série vérifiée est convertie en moyenne mensuelle et rebasée à 100 ; chaque groupe est la moyenne simple de ses séries ; l’indice est la moyenne pondérée des groupes : Céréales 25 %, Élevage 25 %, Produits laitiers 15 %, Aliments 15 %, Engrais 10 %, Énergie 10 %.', 'Chaque série étant rebasée dans sa propre unité, l’indice mesure une évolution, n’est pas un prix et ne mélange pas les devises. Si une série manque un mois à la source, le mois précédent est reporté et déclaré dans le fichier de données. Les États-Unis et le Royaume-Uni seront ajoutés avec au moins 24 mois d’historique. Le panneau « Créez votre indice » permet de modifier les poids et de les comparer à l’indice officiel.'] },
        { h: 'Limites', ul: [
          { t: 'Ce ne sont pas des prix en temps réel : la fréquence dépend de chaque source (hebdomadaire, mensuelle ou trimestrielle).' },
          { t: 'Les prix américains (NASS) sont départ ferme et ceux de l’UE sont des prix de marché ; même affichés dans la même devise, ce n’est pas toujours le même concept.' },
          { t: 'Les sources peuvent réviser leurs données ou changer leurs définitions ; nous affichons la dernière version publiée.' },
          { t: 'Rien ici ne constitue un conseil financier ou d’investissement.' }
        ] },
        { h: 'Données ouvertes et corrections', p: ['Les fichiers à partir desquels le tableau de bord est construit sont publiés dans le dossier de données du site (JSON et CSV), avec la source et la méthodologie de chaque série. Si vous repérez une erreur ou une définition perfectible, écrivez à hola@dehesaindex.com.'] }
      ],
      links: [{ href: 'clima.html', t: 'Climat agricole' }, { href: 'data/', t: 'Données ouvertes' }, { href: 'legal.html', t: 'Mentions légales et confidentialité' }, { href: 'informacion.html', t: 'Informations' }]
    },
    it: {
      title: 'Metodologia',
      sub: 'Come i dati vengono verificati, datati e convertiti, e come si calcola l’indice composito.',
      sections: [
        { h: 'Principio: solo dati verificabili', p: ['Ogni cifra del pannello proviene da una fonte ufficiale o aperta, con la sua data e un link per verificarla. Se non c’è una serie tracciabile, non viene mostrato alcun valore: non riempiamo i vuoti con stime né con dati campione.'] },
        { h: 'Cosa significano le etichette', id: 'etichette', ul: [
          { b: 'REALE.', t: 'Dato verificato alla fonte ufficiale, con data di osservazione e di pubblicazione.' },
          { b: 'NON COMPARABILE.', t: 'Il dato è reale, ma la sua definizione non equivale a quella dell’altro mercato. Esempi: i prezzi USA di suini, bovini e pollo sono a peso vivo, contro il peso della carcassa nell’UE; i fertilizzanti UE sono indici aggregati di nutrienti. Viene mostrato con l’etichetta ed escluso dai confronti diretti.' },
          { b: 'IN ATTESA.', t: 'Non esiste ancora una fonte verificabile e con licenza adeguata. La scheda non mostra alcuna cifra finché non c’è.' }
        ] },
        { h: 'Fonti e frequenza', ul: [
          { b: 'USA — USDA NASS (Quick Stats).', t: 'Prezzo ricevuto dall’agricoltore, mensile e nazionale: grano, mais, riso, latte, uova, suini, bovini e pollo. NASS pubblica una volta al mese; controlliamo ogni settimana per non perdere nessuna pubblicazione.' },
          { b: 'UE — Commissione europea, Agri-food Data Portal.', t: 'Prezzi di mercato settimanali con la Spagna come riferimento (maiale, manzo, agnello, pollo, uova, cereali, olio d’oliva, zucchero, latte, farina di soia, fertilizzanti). I coefficienti per paese sono calcolati con dati reali della stessa settimana.' },
          { b: 'Regno Unito — Defra (Open Government Licence v3.0).', t: 'Latte e indici dei prezzi agricoli, mensili. I prezzi settimanali britannici di cereali e bestiame sono pubblicati da AHDB con condizioni che vietano l’uso automatico; queste schede restano quindi in attesa.' },
          { b: 'Eurostat.', t: 'Indici dei prezzi agricoli dell’UE, trimestrali.' },
          { b: 'Energia e fertilizzanti.', t: 'Gasolio USA (EIA, settimanale) e UE (Oil Bulletin, settimanale); urea (Banca mondiale, mensile).' },
          { b: 'Clima — NASA POWER.', t: 'Pioggia e temperatura mensili (rianalisi MERRA-2) in 12 punti rappresentativi di regioni produttrici, confrontate con la media 2001-2020 dello stesso mese, con storico mensile dal 2000. I mesi più recenti sono calcolati dalla NASA con un diverso flusso di elaborazione (GEOS-IT) che potrebbe essere rivisto. È contesto climatico (una cella di circa 50 km, non una stazione né l’intera regione); non prevede raccolti né prezzi.' },
          { b: 'Offerta e domanda — USDA PSD.', t: 'Bilanci per paese e campagna di cereali, semi oleosi, carne, latte e zucchero (licenza CC BY 4.0), mensili con il WASDE.' },
          { b: 'Farina di soia degli Stati Uniti — USDA AMS.', t: 'Prezzo settimanale della farina di soia (Iowa, FOB, 46,5-48 % di proteine) dal rapporto 3511 di USDA AMS Market News, per tonnellata corta. È un mercato regionale, non un future; il confronto con l’Europa è indicativo.' },
          { b: 'Tassi di cambio.', t: 'Tassi di riferimento della Banca centrale europea, ogni giorno lavorativo.' }
        ] },
        { h: 'Date: osservazione e pubblicazione', p: ['Ogni dato ha due date: l’osservazione (il periodo a cui si riferisce) e la pubblicazione (quando la fonte l’ha diffuso). Alcune fonti non indicano la data di pubblicazione; in tal caso registriamo il giorno in cui abbiamo raccolto il dato la prima volta e lo annotiamo nella scheda.'] },
        { h: 'Valute e unità', p: ['I dati sono conservati nella valuta e nell’unità della fonte. Per confrontarli, il pannello li converte con il tasso di riferimento della BCE dell’ultimo giorno lavorativo e con fattori di unità fissi e visibili (ad esempio, 1 dozzina di uova = 0,6804 kg). Una conversione non rende comparabile un dato che non lo è.'] },
        { h: 'Stato delle colture', id: 'cultivos', p: ['Proviene dal rapporto settimanale Crop Progress dell’USDA NASS (API Quick Stats), pubblicato il lunedì pomeriggio, ora USA, circa da aprile a novembre (il grano invernale è valutato anche in autunno). La valutazione è la quota di superficie in ogni categoria — molto scarso, scarso, discreto, buono, eccellente —; “buono + eccellente” è la somma delle ultime due. È data da corrispondenti locali del NASS, quindi è soggettiva e non è una previsione di raccolto né di prezzi. L’avanzamento è la quota di superficie che ha raggiunto ogni fase (seminato, raccolto...). La media 5 anni e il confronto con l’anno scorso sono un calcolo proprio di Dehesa Index: si prende la stessa data nelle campagne precedenti, con interpolazione tra i rapporti settimanali, e solo se almeno 4 delle 5 campagne hanno dati. Una fase completata (100 %) resta al 100 % nelle settimane successive. I valori che il NASS non pubblica non vengono riempiti.'] },
        { h: 'Mercati USDA', id: 'mercados', p: ['Prezzi di mercato USA come pubblicati da USDA AMS Market News (API MARS): mangimi e sottoprodotti, etanolo e coprodotti, cereali, semi oleosi, legumi, riso, pollame, uova, carne e sottoprodotti, suinetti, bestiame in vendita diretta, fieno e latticini. Vengono letti ogni giorno feriale (alcuni rapporti sono settimanali). Ogni serie è una combinazione fissa di prodotto, qualità, luogo e unità del rapporto stesso; se in uno stesso giorno o settimana ci sono due cifre diverse per la stessa serie, quel punto viene scartato invece di essere indovinato. Valute e unità non vengono convertite. Quando un rapporto indica un prezzo medio viene mostrato quello; quando indica solo minimo e massimo viene mostrato il punto medio, segnalato con ≈. I dati sono ufficiali ma non sono un indicatore di Dehesa Index e non sono confrontabili con quelli europei: ogni rapporto ha la propria base di luogo, qualità e consegna.'] },
        { h: 'Esportazioni USA', id: 'exportaciones', p: ['Le vendite all’esportazione settimanali provengono dall’Export Sales Reporting dell’USDA FAS (API aperta della FAS), pubblicato il giovedì, che copre grano, mais, sorgo, orzo, soia e derivati, cotone, riso, manzo e maiale. Le cifre sono tonnellate metriche (cotone in balle) dichiarate dalle imprese all’USDA: «esportato» sono le spedizioni cumulate della campagna, «vendite in sospeso» quelle concluse e non ancora spedite, «impegno totale» la loro somma. I totali sommano le destinazioni pubblicate e l’aggregato UE conta come un’unica destinazione. Il commercio mensile per paese proviene dall’USDA FAS GATS, con dati del Census Bureau: solo il commercio degli Stati Uniti con ciascun paese (non i flussi tra paesi terzi), in dollari correnti e, dove il Census misura in chilogrammi, in tonnellate; sono inclusi i principali partner agricoli, non tutti i paesi. I gruppi di prodotto si basano sui capitoli tariffari (SA) e sono approssimativi. Gli ultimi due mesi possono essere rivisti. Dati pubblici del governo USA; non convertiti né confrontati con i prezzi.'] },
        { h: 'Scheda prodotto', id: 'producto', p: ['La scheda prodotto (grano, mais, soia, riso, bovino, suino, latte e pollo) non crea dati nuovi: riunisce in una pagina ciò che ogni blocco già pubblica, con la sua fonte e unità (prezzi, offerta e domanda, vendite all’esportazione, commercio per paese, coltura o consistenza del bestiame, siccità e costi). I mercati non vengono convertiti né sommati: il prezzo USA di bovino e suino è a peso vivo e non equivale al prezzo in carcassa europeo. La media della siccità ponderata per la produzione è un calcolo di Dehesa sui 5 maggiori Stati produttori ed esprime la quota della superficie dello Stato in siccità moderata o peggiore, non della superficie coltivata. Un blocco senza dati non compare. Per la soia, il prezzo mostrato è quello della farina, non dei semi.'] },
        { h: 'Prezzi UE', id: 'europa', p: ['La pagina Prezzi UE riunisce tutte le serie di prezzi pubblicate dalla Commissione europea nel suo Agri-food Data Portal (API pubblica): cereali, semi oleosi e farine, latticini, bovini, suino, pollo, uova, agnello, riso, latte crudo, olio d’oliva, zucchero, vino e fertilizzanti, paese per paese. Ogni linea è il prezzo pubblicato dal portale, nella sua unità (€/t, €/100 kg, €/hl…), senza conversioni né medie tra mercati; se un paese pubblica più mercati, ciascuno è mostrato separatamente e le righe non in euro vengono scartate. «UE» è un aggregato calcolato dalla Commissione, non da Dehesa Index. Il portale non pubblica la data di rilascio di ogni dato né tutti i paesi ogni settimana, quindi alcuni paesi hanno lacune. Si aggiorna il giovedì; lo storico arriva al 2015 per la maggior parte delle famiglie (2021 per cereali e bovini) e, per zucchero, vino e fertilizzanti, fin dove lo pubblica la fonte.'] },
        { h: 'Monitor della siccità USA', id: 'sequia', p: ['La quota di ogni Stato in siccità proviene dall’U.S. Drought Monitor, elaborato dal National Drought Mitigation Center (Università del Nebraska-Lincoln) con USDA e NOAA. Viene pubblicato il giovedì con la mappa valida il martedì precedente. Le categorie D0–D4 sono mostrate come pubblicate dall’API (cumulative: D1 include D2, D3 e D4); le variazioni sono calcolate sottraendo le percentuali (punti percentuali) rispetto alla settimana precedente e a 52 settimane prima. È una valutazione, non una previsione.'] },
        { h: 'Zootecnia e latte negli USA', id: 'ganaderia', p: ['Gli inventari di suini e bovini, la produzione di latte per Stato e le scorte in frigo provengono dall’USDA NASS (Quick Stats: Hogs and Pigs, Cattle, Milk Production e Cold Storage) e sono mostrati come pubblicati, nella loro unità originale. Le indagini sui suini sono trimestrali, quelle sui bovini semestrali, latte e scorte in frigo mensili. I dati per Stato sono mostrati solo se NASS li pubblica per lo stesso periodo. Le variazioni sono semplici variazioni percentuali tra due dati pubblicati.'] },
        { h: 'Costi degli input agricoli negli USA', id: 'insumos', p: ['Gli indici dei prezzi pagati dagli agricoltori (fertilizzanti, carburanti, mangimi, agrochimici, sementi, macchinari, servizi, salari, affitti e interessi) provengono dall’USDA NASS, Agricultural Prices (Quick Stats), base 2011 = 100. NASS non pubblica più prezzi assoluti di fertilizzanti né carburanti, quindi si mostrano gli indici ufficiali, senza stimare prezzi per tonnellata o per litro. Le variazioni sono variazioni percentuali tra indici pubblicati.'] },
        { h: 'Prezzi alimentari, costi e reddito agricolo USA', id: 'costes', p: ['I prezzi alimentari (previsioni IPC e IPP), i costi e ricavi per coltura e allevamento, le previsioni dei costi e il reddito agricolo provengono dai file ufficiali dell’USDA Economic Research Service (Food Price Outlook, Commodity Costs and Returns, Cost of Production Forecasts e Farm Income and Wealth Statistics). Sono mostrati come pubblicati; l’ultimo anno di reddito agricolo e le previsioni di prezzi e costi sono previsioni dell’ERS. Il punto di pareggio per unità è calcolato da Dehesa (costo totale per acro diviso per la resa per acro) ed è indicato come tale nella pagina.'] },
        { h: 'Rese e superfici per Stato USA', id: 'rendimientos', p: ['La resa per acro, le superfici seminate e raccolte e la produzione per Stato provengono dall’USDA NASS (Quick Stats, indagini Crop Production e Acreage), nelle unità originali (acri, bushel, libbre). I dati per contea non sono ancora inclusi. L’ultimo anno può essere una stima o previsione NASS finché la campagna non è chiusa; gli Stati senza dato pubblicato non vengono completati.'] },
        { h: 'Offerta e domanda', id: 'oferta-demanda', p: ['I bilanci di produzione, consumo, commercio e scorte provengono dall’USDA Foreign Agricultural Service (PSD Online, licenza CC BY 4.0) e sono aggiornati con il rapporto mensile WASDE. La campagna indicata (2025) è quella che inizia quell’anno (2025/26); la più recente è una previsione che l’USDA rivede ogni mese. “Mondo” è la somma dei paesi della base PSD, con la UE contata una volta; non è una cifra pubblicata dall’USDA. Le campagne differiscono tra paesi, ed esportazioni e importazioni sono dichiarate separatamente: il commercio mondiale non sempre quadra. Cifre in migliaia di tonnellate (carne in equivalente carcassa). Senza dati PSD, non si disegna nulla.'] },
        { h: 'Dehesa Index: l’indice composito', id: 'indice', p: ['Un indice mensile con base 100 a ottobre 2024, solo per il mercato UE. Ogni serie verificata viene convertita in media mensile e ribasata a 100; ogni gruppo è la media semplice delle sue serie; l’indice è la media ponderata dei gruppi: Cereali 25 %, Zootecnia 25 %, Latticini 15 %, Mangimi 15 %, Fertilizzanti 10 %, Energia 10 %.', 'Poiché ogni serie è ribasata nella propria unità, l’indice misura un andamento, non è un prezzo e non mescola le valute. Se una serie ha un mese mancante alla fonte, si riporta il mese precedente e lo si dichiara nel file dei dati. USA e Regno Unito verranno aggiunti quando avranno almeno 24 mesi di storico. Il pannello «Crea il tuo indice» permette di cambiare i pesi e confrontarli con l’indice ufficiale.'] },
        { h: 'Limiti', ul: [
          { t: 'Non sono prezzi in tempo reale: la frequenza dipende da ciascuna fonte (settimanale, mensile o trimestrale).' },
          { t: 'I prezzi USA (NASS) sono alla produzione e quelli UE sono prezzi di mercato; anche se mostrati nella stessa valuta, non sono sempre lo stesso concetto.' },
          { t: 'Le fonti possono rivedere i dati o cambiare le definizioni; mostriamo l’ultima versione pubblicata.' },
          { t: 'Nulla qui costituisce consulenza finanziaria o di investimento.' }
        ] },
        { h: 'Dati aperti e correzioni', p: ['I file con cui è costruito il pannello sono pubblicati nella cartella dei dati del sito (JSON e CSV), con la fonte e la metodologia di ogni serie. Se noti un errore o una definizione migliorabile, scrivi a hola@dehesaindex.com.'] }
      ],
      links: [{ href: 'clima.html', t: 'Clima agricolo' }, { href: 'data/', t: 'Dati aperti' }, { href: 'legal.html', t: 'Note legali e privacy' }, { href: 'informacion.html', t: 'Informazioni' }]
    }
  };
  window.DehesaTextPage(STRINGS, 'informacion');
})();
