/* Nombres de estados de EE. UU., provincias de Canadá y regiones de España, Francia, Italia, Alemania y Australia, todos en en|es|fr|it. Los usan region.js, paises.js y los generadores de páginas. */
(function () {
  var US = { AL: 'Alabama|Alabama|Alabama|Alabama', AK: 'Alaska|Alaska|Alaska|Alaska', AZ: 'Arizona|Arizona|Arizona|Arizona', AR: 'Arkansas|Arkansas|Arkansas|Arkansas', CA: 'California|California|Californie|California', CO: 'Colorado|Colorado|Colorado|Colorado', CT: 'Connecticut|Connecticut|Connecticut|Connecticut', DE: 'Delaware|Delaware|Delaware|Delaware', DC: 'District of Columbia|Distrito de Columbia|District de Columbia|Distretto di Columbia', FL: 'Florida|Florida|Floride|Florida', GA: 'Georgia|Georgia|Géorgie|Georgia', HI: 'Hawaii|Hawái|Hawaï|Hawaii', ID: 'Idaho|Idaho|Idaho|Idaho', IL: 'Illinois|Illinois|Illinois|Illinois', IN: 'Indiana|Indiana|Indiana|Indiana', IA: 'Iowa|Iowa|Iowa|Iowa', KS: 'Kansas|Kansas|Kansas|Kansas', KY: 'Kentucky|Kentucky|Kentucky|Kentucky', LA: 'Louisiana|Luisiana|Louisiane|Louisiana', ME: 'Maine|Maine|Maine|Maine', MD: 'Maryland|Maryland|Maryland|Maryland', MA: 'Massachusetts|Massachusetts|Massachusetts|Massachusetts', MI: 'Michigan|Míchigan|Michigan|Michigan', MN: 'Minnesota|Minnesota|Minnesota|Minnesota', MS: 'Mississippi|Misisipi|Mississippi|Mississippi', MO: 'Missouri|Misuri|Missouri|Missouri', MT: 'Montana|Montana|Montana|Montana', NE: 'Nebraska|Nebraska|Nebraska|Nebraska', NV: 'Nevada|Nevada|Nevada|Nevada', NH: 'New Hampshire|Nuevo Hampshire|New Hampshire|New Hampshire', NJ: 'New Jersey|Nueva Jersey|New Jersey|New Jersey', NM: 'New Mexico|Nuevo México|Nouveau-Mexique|Nuovo Messico', NY: 'New York|Nueva York|New York|New York', NC: 'North Carolina|Carolina del Norte|Caroline du Nord|Carolina del Nord', ND: 'North Dakota|Dakota del Norte|Dakota du Nord|Dakota del Nord', OH: 'Ohio|Ohio|Ohio|Ohio', OK: 'Oklahoma|Oklahoma|Oklahoma|Oklahoma', OR: 'Oregon|Oregón|Oregon|Oregon', PA: 'Pennsylvania|Pensilvania|Pennsylvanie|Pennsylvania', RI: 'Rhode Island|Rhode Island|Rhode Island|Rhode Island', SC: 'South Carolina|Carolina del Sur|Caroline du Sud|Carolina del Sud', SD: 'South Dakota|Dakota del Sur|Dakota du Sud|Dakota del Sud', TN: 'Tennessee|Tennessee|Tennessee|Tennessee', TX: 'Texas|Texas|Texas|Texas', UT: 'Utah|Utah|Utah|Utah', VT: 'Vermont|Vermont|Vermont|Vermont', VA: 'Virginia|Virginia|Virginie|Virginia', WA: 'Washington|Washington|Washington|Washington', WV: 'West Virginia|Virginia Occidental|Virginie-Occidentale|Virginia Occidentale', WI: 'Wisconsin|Wisconsin|Wisconsin|Wisconsin', WY: 'Wyoming|Wyoming|Wyoming|Wyoming' };
  var CA = { AB: 'Alberta|Alberta|Alberta|Alberta', BC: 'British Columbia|Columbia Británica|Colombie-Britannique|Columbia Britannica', MB: 'Manitoba|Manitoba|Manitoba|Manitoba', NB: 'New Brunswick|Nuevo Brunswick|Nouveau-Brunswick|Nuovo Brunswick', NL: 'Newfoundland and Labrador|Terranova y Labrador|Terre-Neuve-et-Labrador|Terranova e Labrador', NS: 'Nova Scotia|Nueva Escocia|Nouvelle-Écosse|Nuova Scozia', NT: 'Northwest Territories|Territorios del Noroeste|Territoires du Nord-Ouest|Territori del Nord-Ovest', NU: 'Nunavut|Nunavut|Nunavut|Nunavut', ON: 'Ontario|Ontario|Ontario|Ontario', PE: 'Prince Edward Island|Isla del Príncipe Eduardo|Île-du-Prince-Édouard|Isola del Principe Edoardo', QC: 'Quebec|Quebec|Québec|Québec', SK: 'Saskatchewan|Saskatchewan|Saskatchewan|Saskatchewan', YT: 'Yukon|Yukón|Yukon|Yukon' };
  var ES = { AN: 'Andalusia|Andalucía|Andalousie|Andalusia', AR: 'Aragon|Aragón|Aragon|Aragona', AS: 'Asturias|Principado de Asturias|Asturies|Asturie', CN: 'Canary Islands|Canarias|Îles Canaries|Canarie', CB: 'Cantabria|Cantabria|Cantabrie|Cantabria', CL: 'Castile and León|Castilla y León|Castille-et-León|Castiglia e León', CM: 'Castilla-La Mancha|Castilla-La Mancha|Castille-La Manche|Castiglia-La Mancia', CT: 'Catalonia|Cataluña|Catalogne|Catalogna', EX: 'Extremadura|Extremadura|Estrémadure|Estremadura', GA: 'Galicia|Galicia|Galice|Galizia', IB: 'Balearic Islands|Islas Baleares|Îles Baléares|Isole Baleari', RI: 'La Rioja|La Rioja|La Rioja|La Rioja', MD: 'Community of Madrid|Comunidad de Madrid|Communauté de Madrid|Comunità di Madrid', MC: 'Region of Murcia|Región de Murcia|Région de Murcie|Regione di Murcia', NC: 'Navarre|Comunidad Foral de Navarra|Navarre|Navarra', PV: 'Basque Country|País Vasco|Pays basque|Paesi Baschi', VC: 'Valencian Community|Comunidad Valenciana|Communauté valencienne|Comunità Valenciana' };
  var FR = { ARA: 'Auvergne-Rhône-Alpes|Auvernia-Ródano-Alpes|Auvergne-Rhône-Alpes|Alvernia-Rodano-Alpi', BFC: 'Bourgogne-Franche-Comté|Borgoña-Franco Condado|Bourgogne-Franche-Comté|Borgogna-Franca Contea', BRE: 'Brittany|Bretaña|Bretagne|Bretagna', CVL: 'Centre-Val de Loire|Centro-Valle del Loira|Centre-Val de Loire|Centro-Valle della Loira', COR: 'Corsica|Córcega|Corse|Corsica', GES: 'Grand Est|Gran Este|Grand Est|Grand Est', HDF: 'Hauts-de-France|Alta Francia|Hauts-de-France|Alta Francia', IDF: 'Île-de-France|Isla de Francia|Île-de-France|Île-de-France', NOR: 'Normandy|Normandía|Normandie|Normandia', NAQ: 'Nouvelle-Aquitaine|Nueva Aquitania|Nouvelle-Aquitaine|Nuova Aquitania', OCC: 'Occitania|Occitania|Occitanie|Occitania', PDL: 'Pays de la Loire|País del Loira|Pays de la Loire|Paesi della Loira', PAC: 'Provence-Alpes-Côte d’Azur|Provenza-Alpes-Costa Azul|Provence-Alpes-Côte d’Azur|Provenza-Alpi-Costa Azzurra' };
  var IT = { ABR: 'Abruzzo|Abruzos|Abruzzes|Abruzzo', BAS: 'Basilicata|Basilicata|Basilicate|Basilicata', CAL: 'Calabria|Calabria|Calabre|Calabria', CAM: 'Campania|Campania|Campanie|Campania', EMR: 'Emilia-Romagna|Emilia-Romaña|Émilie-Romagne|Emilia-Romagna', FVG: 'Friuli-Venezia Giulia|Friuli-Venecia Julia|Frioul-Vénétie julienne|Friuli-Venezia Giulia', LAZ: 'Lazio|Lacio|Latium|Lazio', LIG: 'Liguria|Liguria|Ligurie|Liguria', LOM: 'Lombardy|Lombardía|Lombardie|Lombardia', MAR: 'Marche|Marcas|Marches|Marche', MOL: 'Molise|Molise|Molise|Molise', PIE: 'Piedmont|Piamonte|Piémont|Piemonte', PUG: 'Apulia|Apulia|Pouilles|Puglia', SAR: 'Sardinia|Cerdeña|Sardaigne|Sardegna', SIC: 'Sicily|Sicilia|Sicile|Sicilia', TOS: 'Tuscany|Toscana|Toscane|Toscana', TAA: 'Trentino-South Tyrol|Trentino-Alto Adigio|Trentin-Haut-Adige|Trentino-Alto Adige', UMB: 'Umbria|Umbría|Ombrie|Umbria', VDA: 'Aosta Valley|Valle de Aosta|Vallée d’Aoste|Valle d’Aosta', VEN: 'Veneto|Véneto|Vénétie|Veneto' };
  var DE = { BW: 'Baden-Württemberg|Baden-Wurtemberg|Bade-Wurtemberg|Baden-Württemberg', BY: 'Bavaria|Baviera|Bavière|Baviera', BE: 'Berlin|Berlín|Berlin|Berlino', BB: 'Brandenburg|Brandeburgo|Brandebourg|Brandeburgo', HB: 'Bremen|Bremen|Brême|Brema', HH: 'Hamburg|Hamburgo|Hambourg|Amburgo', HE: 'Hesse|Hesse|Hesse|Assia', MV: 'Mecklenburg-Western Pomerania|Mecklemburgo-Pomerania Occidental|Mecklembourg-Poméranie-Occidentale|Meclemburgo-Pomerania Anteriore', NI: 'Lower Saxony|Baja Sajonia|Basse-Saxe|Bassa Sassonia', NW: 'North Rhine-Westphalia|Renania del Norte-Westfalia|Rhénanie-du-Nord-Westphalie|Renania Settentrionale-Vestfalia', RP: 'Rhineland-Palatinate|Renania-Palatinado|Rhénanie-Palatinat|Renania-Palatinato', SL: 'Saarland|Sarre|Sarre|Saarland', SN: 'Saxony|Sajonia|Saxe|Sassonia', ST: 'Saxony-Anhalt|Sajonia-Anhalt|Saxe-Anhalt|Sassonia-Anhalt', SH: 'Schleswig-Holstein|Schleswig-Holstein|Schleswig-Holstein|Schleswig-Holstein', TH: 'Thuringia|Turingia|Thuringe|Turingia' };
  var AU = { NSW: 'New South Wales|Nueva Gales del Sur|Nouvelle-Galles du Sud|Nuovo Galles del Sud', VIC: 'Victoria|Victoria|Victoria|Victoria', QLD: 'Queensland|Queensland|Queensland|Queensland', SA: 'South Australia|Australia Meridional|Australie-Méridionale|Australia Meridionale', WA: 'Western Australia|Australia Occidental|Australie-Occidentale|Australia Occidentale', TAS: 'Tasmania|Tasmania|Tasmanie|Tasmania', NT: 'Northern Territory|Territorio del Norte|Territoire du Nord|Territorio del Nord', ACT: 'Australian Capital Territory|Territorio de la Capital Australiana|Territoire de la capitale australienne|Territorio della Capitale Australiana' };
  var NL = { GR: 'Groningen|Groninga|Groningue|Groninga', FR: 'Friesland|Frisia|Frise|Frisia', DR: 'Drenthe|Drente|Drenthe|Drenthe', OV: 'Overijssel|Overijssel|Overijssel|Overijssel', GE: 'Gelderland|Güeldres|Gueldre|Gheldria', FL: 'Flevoland|Flevoland|Flevoland|Flevoland', UT: 'Utrecht|Utrecht|Utrecht|Utrecht', NH: 'North Holland|Holanda Septentrional|Hollande-Septentrionale|Olanda Settentrionale', ZH: 'South Holland|Holanda Meridional|Hollande-Méridionale|Olanda Meridionale', ZE: 'Zeeland|Zelanda|Zélande|Zelanda', NB: 'North Brabant|Brabante Septentrional|Brabant-Septentrional|Brabante Settentrionale', LI: 'Limburg|Limburgo|Limbourg|Limburgo' };
  var AT = { B: 'Burgenland|Burgenland|Burgenland|Burgenland', NO: 'Lower Austria|Baja Austria|Basse-Autriche|Bassa Austria', W: 'Vienna|Viena|Vienne|Vienna', K: 'Carinthia|Carintia|Carinthie|Carinzia', ST: 'Styria|Estiria|Styrie|Stiria', OO: 'Upper Austria|Alta Austria|Haute-Autriche|Alta Austria', S: 'Salzburg|Salzburgo|Salzbourg|Salisburgo', T: 'Tyrol|Tirol|Tyrol|Tirolo', V: 'Vorarlberg|Vorarlberg|Vorarlberg|Vorarlberg' };
  window.DehesaRegionNames = { US: US, CA: CA, ES: ES, FR: FR, IT: IT, DE: DE, AU: AU, NL: NL, AT: AT };

  /* Direcciones de las páginas estáticas por región (las genera scripts/build-region-pages.mjs; mismas reglas de slug) */
  var CS = { US: ['united-states', 'estados-unidos', 'etats-unis', 'stati-uniti'], CA: ['canada', 'canada', 'canada', 'canada'], ES: ['spain', 'espana', 'espagne', 'spagna'], FR: ['france', 'francia', 'france', 'francia'], IT: ['italy', 'italia', 'italie', 'italia'], DE: ['germany', 'alemania', 'allemagne', 'germania'], AU: ['australia', 'australia', 'australie', 'australia'], NL: ['netherlands', 'paises-bajos', 'pays-bas', 'paesi-bassi'], AT: ['austria', 'austria', 'autriche', 'austria'] };
  var ROOT = { en: 'en/regions', es: 'regiones', fr: 'fr/regions', it: 'it/regioni' }, LX = { en: 0, es: 1, fr: 2, it: 3 };
  function slug(t) { return String(t).normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase().replace(/ß/g, 'ss').replace(/['’]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''); }
  function nm(c, r, lg) { var v = window.DehesaRegionNames[c] && window.DehesaRegionNames[c][r]; if (!v) return ''; var a = v.split('|'); return a[LX[lg]] || a[0]; }
  window.DehesaRegionUrls = {
    hub: function (c, lg) { return CS[c] ? '/' + ROOT[lg] + '/' + CS[c][LX[lg]] + '/' : ''; },
    page: function (c, r, lg) { return CS[c] && nm(c, r, lg) ? '/' + ROOT[lg] + '/' + CS[c][LX[lg]] + '/' + slug(nm(c, r, lg)) + '/' : ''; }
  };
})();
