/* Dehesa Index — Rendimientos y superficie por provincia de Canadá (Statistics Canada, tabla 32-10-0359, data/canada-provinces.json).
   Pestaña «Canadá» de rendimientos.html sobre js/ca-explorer.js. Solo muestra lo que publica StatCan; un hueco es un hueco. ES5. */
(function () {
  'use strict';
  var CROPS = { 'wheat-all': ['Trigo (total)', 'Wheat (all)', 'Blé (total)', 'Frumento (totale)'], 'wheat-durum': ['Trigo duro', 'Durum wheat', 'Blé dur', 'Frumento duro'], barley: ['Cebada', 'Barley', 'Orge', 'Orzo'], oats: ['Avena', 'Oats', 'Avoine', 'Avena'], 'rye-all': ['Centeno', 'Rye', 'Seigle', 'Segale'], 'canola-rapeseed': ['Canola (colza)', 'Canola', 'Canola', 'Canola'], 'corn-for-grain': ['Maíz grano', 'Grain corn', 'Maïs-grain', 'Mais da granella'], soybeans: ['Soja', 'Soybeans', 'Soja', 'Soia'], 'peas-dry': ['Guisantes secos', 'Dry peas', 'Pois secs', 'Piselli secchi'], lentils: ['Lentejas', 'Lentils', 'Lentilles', 'Lenticchie'], flaxseed: ['Lino', 'Flaxseed', 'Lin', 'Lino'], 'sunflower-seed': ['Girasol', 'Sunflower seed', 'Tournesol', 'Girasole'], 'mustard-seed': ['Mostaza', 'Mustard seed', 'Moutarde', 'Senape'], 'chick-peas': ['Garbanzos', 'Chickpeas', 'Pois chiches', 'Ceci'], 'canary-seed': ['Alpiste', 'Canary seed', 'Alpiste', 'Scagliola'] };
  var KEY = { yield: 'yield', production: 'prod', harvested: 'harea', planted: 'area' };
  var T = {
    es: { tabUS: 'EE. UU. (por estado)', tabCA: 'Canadá (por provincia)', title: 'Rendimientos y superficie por provincia de Canadá', sub: 'Rendimiento, superficie sembrada y cosechada y producción de los cultivos de campo por provincia. Datos de Statistics Canada (encuestas de cultivos de campo), tal como se publican.',
      item: 'Cultivo', measure: 'Cifra', period: 'Campaña', yield: 'Rendimiento', production: 'Producción', harvested: 'Superficie cosechada', planted: 'Superficie sembrada', ca: 'Canadá', vsPrev: 'frente al año anterior', hist: 'Evolución nacional', prov: 'Por provincia', share: 'Peso en Canadá', value: 'Valor', change: 'Variación', province: 'Provincia', pick: 'Pulsa una provincia (mapa o tabla) para compararla con Canadá.', clear: 'Quitar la provincia', open: 'Perfil de la provincia', noData: 'Sin datos disponibles.', noProv: 'Sin dato publicado para esta cifra y año.', last: 'Último año',
      note: 'Unidades originales de Statistics Canada: superficie en miles de hectáreas, producción en miles de toneladas métricas y rendimiento en kg/ha. El último año suele ser una estimación y Statistics Canada lo revisa. Los territorios no aparecen: Statistics Canada no publica esta tabla para Yukon, Territorios del Noroeste ni Nunavut. Un hueco es un hueco, nunca cero.', src: 'Fuente: Statistics Canada, tabla 32-10-0359-01 (Open Government Licence – Canada).', mapAlt: 'Mapa de provincias de Canadá coloreado por la cifra elegida' },
    en: { tabUS: 'United States (by state)', tabCA: 'Canada (by province)', title: 'Yields and area by Canadian province', sub: 'Yield, seeded and harvested area and production of field crops by province. Statistics Canada data (field crop surveys), as published.',
      item: 'Crop', measure: 'Measure', period: 'Crop year', yield: 'Yield', production: 'Production', harvested: 'Harvested area', planted: 'Seeded area', ca: 'Canada', vsPrev: 'vs. previous year', hist: 'National trend', prov: 'By province', share: 'Share of Canada', value: 'Value', change: 'Change', province: 'Province', pick: 'Select a province (map or table) to compare it with Canada.', clear: 'Remove province', open: 'Province profile', noData: 'No data available.', noProv: 'No published figure for this measure and year.', last: 'Latest year',
      note: 'Original Statistics Canada units: area in thousand hectares, production in thousand metric tonnes and yield in kg/ha. The latest year is usually an estimate and Statistics Canada revises it. Territories are not shown: Statistics Canada does not publish this table for Yukon, the Northwest Territories or Nunavut. A gap is a gap, never zero.', src: 'Source: Statistics Canada, table 32-10-0359-01 (Open Government Licence – Canada).', mapAlt: 'Map of Canadian provinces coloured by the chosen measure' },
    fr: { tabUS: 'États-Unis (par État)', tabCA: 'Canada (par province)', title: 'Rendements et surfaces par province canadienne', sub: 'Rendement, surfaces ensemencées et récoltées et production des grandes cultures par province. Données de Statistique Canada (enquêtes sur les grandes cultures), telles que publiées.',
      item: 'Culture', measure: 'Chiffre', period: 'Campagne', yield: 'Rendement', production: 'Production', harvested: 'Surface récoltée', planted: 'Surface ensemencée', ca: 'Canada', vsPrev: 'par rapport à l’an dernier', hist: 'Évolution nationale', prov: 'Par province', share: 'Part du Canada', value: 'Valeur', change: 'Variation', province: 'Province', pick: 'Sélectionnez une province (carte ou tableau) pour la comparer au Canada.', clear: 'Retirer la province', open: 'Profil de la province', noData: 'Aucune donnée disponible.', noProv: 'Aucun chiffre publié pour cette mesure et cette année.', last: 'Dernière année',
      note: 'Unités d’origine de Statistique Canada : surfaces en milliers d’hectares, production en milliers de tonnes métriques et rendement en kg/ha. La dernière année est généralement une estimation que Statistique Canada révise. Les territoires ne figurent pas : Statistique Canada ne publie pas ce tableau pour le Yukon, les Territoires du Nord-Ouest ni le Nunavut. Un manque est un manque, jamais zéro.', src: 'Source : Statistique Canada, tableau 32-10-0359-01 (Licence du gouvernement ouvert – Canada).', mapAlt: 'Carte des provinces canadiennes colorée selon le chiffre choisi' },
    it: { tabUS: 'Stati Uniti (per Stato)', tabCA: 'Canada (per provincia)', title: 'Rese e superfici per provincia canadese', sub: 'Resa, superficie seminata e raccolta e produzione delle colture di pieno campo per provincia. Dati di Statistics Canada (indagini sulle colture), come pubblicati.',
      item: 'Coltura', measure: 'Dato', period: 'Campagna', yield: 'Resa', production: 'Produzione', harvested: 'Superficie raccolta', planted: 'Superficie seminata', ca: 'Canada', vsPrev: 'rispetto all’anno scorso', hist: 'Andamento nazionale', prov: 'Per provincia', share: 'Peso sul Canada', value: 'Valore', change: 'Variazione', province: 'Provincia', pick: 'Seleziona una provincia (mappa o tabella) per confrontarla con il Canada.', clear: 'Rimuovi la provincia', open: 'Profilo della provincia', noData: 'Nessun dato disponibile.', noProv: 'Nessun dato pubblicato per questo dato e anno.', last: 'Ultimo anno',
      note: 'Unità originali di Statistics Canada: superficie in migliaia di ettari, produzione in migliaia di tonnellate metriche e resa in kg/ha. L’ultimo anno è di solito una stima che Statistics Canada rivede. I territori non compaiono: Statistics Canada non pubblica questa tabella per lo Yukon, i Territori del Nord-Ovest e il Nunavut. Un vuoto è un vuoto, mai zero.', src: 'Fonte: Statistics Canada, tabella 32-10-0359-01 (Open Government Licence – Canada).', mapAlt: 'Mappa delle province canadesi colorata in base al dato scelto' }
  };
  var items = Object.keys(CROPS).map(function (k) { return { id: k, label: CROPS[k] }; });
  function ser(D, prov, crop, m) { var P = D.provinces[prov], c = P && P.crops && P.crops[crop]; return c ? c[KEY[m]] || null : null; }
  var ex = window.CAExplorer.create({
    id: 'rd-ca', usBody: 'rd-body', texts: T, items: items, defaultItem: 'wheat-all', defaultMeasure: 'yield', cite: 'statcan',
    measures: function (D, crop) { return ['yield', 'production', 'harvested', 'planted'].filter(function (m) { return ser(D, 'CA', crop, m); }); },
    series: ser,
    fmt: function (m, v) {
      var d = function (x, n) { try { return x.toLocaleString(window.DehesaShared.getLang(), { minimumFractionDigits: n, maximumFractionDigits: n }); } catch (e) { return x.toFixed(n); } };
      if (m === 'yield') return d(v, 0) + ' kg/ha';
      if (m === 'production') return v >= 1000 ? d(v / 1000, 2) + ' Mt' : d(v, 0) + ' kt';
      return v >= 1000 ? d(v / 1000, 2) + ' M ha' : d(v, 0) + ' kha';
    },
    yTitle: function (m) { return m === 'yield' ? 'kg/ha' : m === 'production' ? 'kt' : 'kha'; },
    shareMeasure: function (m) { return m !== 'yield'; },
    usRender: function () { if (window.__rdUsRender) window.__rdUsRender(); }
  });
  window.RDCanada = ex;
})();
