/* Dehesa Index — Sacrificio de ganado en España: cabezas, peso canal y peso medio por especie y comunidad autónoma (MAPA, Encuesta de sacrificio de ganado; data/spain-slaughter/slaughter.json).
   Pestaña «España (sacrificio)» de ganaderia.html sobre js/ca-explorer.js. Solo muestra lo que publica el MAPA; un mes sin dato es un hueco, nunca cero. El peso medio es un cálculo (toneladas de canal / cabezas), no un dato publicado. ES5. */
(function () {
  'use strict';
  var CODE = { andalucia: 'AN', aragon: 'AR', asturias: 'AS', baleares: 'IB', canarias: 'CN', cantabria: 'CB', clm: 'CM', cyl: 'CL', cataluna: 'CT', extremadura: 'EX', galicia: 'GA', madrid: 'MD', murcia: 'MC', navarra: 'NC', paisvasco: 'PV', larioja: 'RI', valenciana: 'VC' };
  var ITEMS = [['bovino', ['Vacuno', 'Cattle', 'Bovins', 'Bovini']],['ovino', ['Ovino', 'Sheep', 'Ovins', 'Ovini']],['caprino', ['Caprino', 'Goats', 'Caprins', 'Caprini']],['porcino', ['Porcino', 'Pigs', 'Porcins', 'Suini']],['equino', ['Equino', 'Equines', 'Équidés', 'Equini']],['aves', ['Aves', 'Poultry', 'Volailles', 'Pollame']],['conejos', ['Conejos', 'Rabbits', 'Lapins', 'Conigli']]];
  var MEAS = ['heads', 'carcass', 'weight'];
  var T = {
    es: { tabUS: 'EE. UU.', tabCA: 'España (sacrificio)', title: 'Sacrificio de ganado en España: cabezas y peso canal', sub: 'Cabezas sacrificadas y toneladas de peso canal por especie, cada mes, a escala nacional (desde 2022) y por comunidad autónoma (desde 2025). Datos de la Encuesta de sacrificio de ganado del Ministerio de Agricultura, Pesca y Alimentación (MAPA), tal como los publica.',
      item: 'Especie', measure: 'Cifra', period: 'Mes', heads: 'Cabezas sacrificadas', carcass: 'Peso canal (t)', weight: 'Peso canal medio (kg por cabeza)', ca: 'España', vsPrev: 'frente al mismo mes del año anterior', hist: 'Evolución nacional', prov: 'Por comunidad autónoma', share: 'Peso en España', value: 'Valor', change: 'Variación', province: 'Comunidad', pick: 'Pulsa una comunidad (mapa o tabla) para compararla con España.', clear: 'Quitar la comunidad', open: 'Perfil', noData: 'Sin datos disponibles.', noProv: 'Sin dato publicado para esta especie y mes.', last: 'Último mes',
      note: 'Los datos salen de la Encuesta de sacrificio de ganado del MAPA (mataderos). Aves y conejos se publican en miles de cabezas y aquí se muestran en cabezas. El peso canal medio es un cálculo de Dehesa Index (toneladas de canal entre cabezas), no una cifra publicada. El libro del MAPA trae el desglose por comunidad solo desde 2025; antes hay serie nacional y no se rellena por comunidad. Los datos que el MAPA marca como confidenciales (DC) son un hueco, nunca cero, y por eso algunas comunidades no suman el total. En el libro de agosto de 2026 la fila «Total España» de las hojas mensuales no coincide con la serie nacional: se usa la serie nacional y la diferencia queda anotada en el archivo de datos. Las cifras son provisionales y el MAPA puede revisarlas: prevalece el último libro.', src: 'Fuente: Ministerio de Agricultura, Pesca y Alimentación (MAPA), Encuesta de sacrificio de ganado.', mapAlt: 'Mapa de comunidades autónomas de España coloreado por la cifra elegida' },
    en: { tabUS: 'United States', tabCA: 'Spain (slaughter)', title: 'Livestock slaughter in Spain: head and carcass weight', sub: 'Head slaughtered and tonnes of carcass weight by species, every month, nationally (since 2022) and by autonomous community (since 2025). Data from the Livestock Slaughter Survey of the Spanish Ministry of Agriculture, Fisheries and Food (MAPA), as published.',
      item: 'Species', measure: 'Measure', period: 'Month', heads: 'Head slaughtered', carcass: 'Carcass weight (t)', weight: 'Average carcass weight (kg per head)', ca: 'Spain', vsPrev: 'vs. the same month a year earlier', hist: 'National trend', prov: 'By autonomous community', share: 'Share of Spain', value: 'Value', change: 'Change', province: 'Community', pick: 'Select a community (map or table) to compare it with Spain.', clear: 'Remove community', open: 'Profile', noData: 'No data available.', noProv: 'No published figure for this species and month.', last: 'Latest month',
      note: 'The data come from MAPA’s Livestock Slaughter Survey (slaughterhouses). Poultry and rabbits are published in thousands of head and shown here in head. Average carcass weight is a Dehesa Index calculation (tonnes of carcass divided by head), not a published figure. The MAPA workbook breaks figures down by community only from 2025; before that there is a national series and communities are not filled in. Data MAPA marks as confidential (DC) are a gap, never zero, so some communities do not add up to the total. In the August 2026 workbook the “Total España” row of the monthly sheets does not match the national series: the national series is used and the difference is recorded in the data file. Figures are provisional and MAPA may revise them: the latest workbook prevails.', src: 'Source: Ministry of Agriculture, Fisheries and Food (MAPA), Livestock Slaughter Survey.', mapAlt: 'Map of Spanish autonomous communities coloured by the chosen measure' },
    fr: { tabUS: 'États-Unis', tabCA: 'Espagne (abattages)', title: 'Abattages de bétail en Espagne : têtes et poids carcasse', sub: 'Têtes abattues et tonnes de poids carcasse par espèce, chaque mois, au niveau national (depuis 2022) et par communauté autonome (depuis 2025). Données de l’enquête sur les abattages du ministère espagnol de l’Agriculture, de la Pêche et de l’Alimentation (MAPA), telles que publiées.',
      item: 'Espèce', measure: 'Chiffre', period: 'Mois', heads: 'Têtes abattues', carcass: 'Poids carcasse (t)', weight: 'Poids carcasse moyen (kg par tête)', ca: 'Espagne', vsPrev: 'par rapport au même mois un an plus tôt', hist: 'Évolution nationale', prov: 'Par communauté autonome', share: 'Part de l’Espagne', value: 'Valeur', change: 'Variation', province: 'Communauté', pick: 'Sélectionnez une communauté (carte ou tableau) pour la comparer à l’Espagne.', clear: 'Retirer la communauté', open: 'Profil', noData: 'Aucune donnée disponible.', noProv: 'Aucun chiffre publié pour cette espèce et ce mois.', last: 'Dernier mois',
      note: 'Les données proviennent de l’enquête sur les abattages du MAPA (abattoirs). Volailles et lapins sont publiés en milliers de têtes et affichés ici en têtes. Le poids carcasse moyen est un calcul de Dehesa Index (tonnes de carcasse divisées par les têtes), pas un chiffre publié. Le classeur du MAPA ne détaille par communauté qu’à partir de 2025 ; avant, il n’y a que la série nationale et les communautés ne sont pas complétées. Les données que le MAPA déclare confidentielles (DC) sont un manque, jamais zéro, d’où des communautés qui ne totalisent pas le national. Dans le classeur d’août 2026, la ligne « Total España » des feuilles mensuelles ne correspond pas à la série nationale : on utilise la série nationale et l’écart est consigné dans le fichier de données. Les chiffres sont provisoires et le MAPA peut les réviser : le dernier classeur prévaut.', src: 'Source : ministère de l’Agriculture, de la Pêche et de l’Alimentation (MAPA), enquête sur les abattages de bétail.', mapAlt: 'Carte des communautés autonomes d’Espagne colorée selon le chiffre choisi' },
    it: { tabUS: 'Stati Uniti', tabCA: 'Spagna (macellazioni)', title: 'Macellazioni di bestiame in Spagna: capi e peso carcassa', sub: 'Capi macellati e tonnellate di peso carcassa per specie, ogni mese, a livello nazionale (dal 2022) e per comunità autonoma (dal 2025). Dati dell’indagine sulle macellazioni del ministero spagnolo dell’Agricoltura, della Pesca e dell’Alimentazione (MAPA), come pubblicati.',
      item: 'Specie', measure: 'Dato', period: 'Mese', heads: 'Capi macellati', carcass: 'Peso carcassa (t)', weight: 'Peso medio carcassa (kg per capo)', ca: 'Spagna', vsPrev: 'rispetto allo stesso mese dell’anno prima', hist: 'Andamento nazionale', prov: 'Per comunità autonoma', share: 'Peso sulla Spagna', value: 'Valore', change: 'Variazione', province: 'Comunità', pick: 'Seleziona una comunità (mappa o tabella) per confrontarla con la Spagna.', clear: 'Rimuovi la comunità', open: 'Profilo', noData: 'Nessun dato disponibile.', noProv: 'Nessun dato pubblicato per questa specie e questo mese.', last: 'Ultimo mese',
      note: 'I dati provengono dall’indagine sulle macellazioni del MAPA (macelli). Pollame e conigli sono pubblicati in migliaia di capi e qui mostrati in capi. Il peso medio della carcassa è un calcolo di Dehesa Index (tonnellate di carcassa diviso capi), non un dato pubblicato. La cartella del MAPA ripartisce per comunità solo dal 2025; prima c’è la serie nazionale e le comunità non sono compilate. I dati che il MAPA segna come riservati (DC) sono un vuoto, mai zero, per cui alcune comunità non sommano il totale. Nella cartella di agosto 2026 la riga «Total España» dei fogli mensili non coincide con la serie nazionale: si usa la serie nazionale e la differenza è annotata nel file dei dati. I dati sono provvisori e il MAPA può rivederli: prevale l’ultima cartella.', src: 'Fonte: Ministero dell’Agricoltura, della Pesca e dell’Alimentazione (MAPA), indagine sulle macellazioni di bestiame.', mapAlt: 'Mappa delle comunità autonome spagnole colorata in base al dato scelto' }
  };
  var items = ITEMS.map(function (i) { return { id: i[0], label: i[1] }; });
  var K = { aves: 1000, conejos: 1000 };
  function pairs(a, per, k) { var o = []; for (var i = 0; i < a.length; i++) if (a[i] !== null && a[i] !== undefined) o.push([per[i], a[i] * (k || 1)]); return o.length ? o : null; }
  function get(D, prov, id) { return prov === 'ES' ? D.doc.national[id] : (D.slug[prov] && D.doc.ccaa[D.slug[prov]] ? D.doc.ccaa[D.slug[prov]][id] : null); }
  function series(D, prov, id, m) {
    var d = D.doc, per = d.periods, s = get(D, prov, id); if (!s) return null;
    if (m === 'heads') return pairs(s.heads, per, K[id]);
    if (m === 'carcass') return pairs(s.carcass, per);
    var o = []; for (var i = 0; i < per.length; i++) { var h = s.heads[i], t = s.carcass[i]; if (h && t !== null && t !== undefined) o.push([per[i], t * 1000 / (h * (K[id] || 1))]); }
    return o.length ? o : null;
  }
  function nf(l, x, n) { try { return x.toLocaleString(l, { minimumFractionDigits: n, maximumFractionDigits: n }); } catch (e) { return x.toFixed(n); } }
  window.GNSlaughter = window.CAExplorer.create({
    id: 'gn-ess', tabsHost: 'gn-ca-tabs', usBody: 'gn-body', usExtra: '#cof, #nd, #nl', country: 'ES', tabKey: 'ES-SACRIFICIO', nat: 'ES', map: 'DEHESA_ES_CCAA', noRegionLink: true, texts: T, items: items, defaultItem: 'bovino', defaultMeasure: 'heads', cite: 'mapa_es',
    load: function () {
      return fetch('data/spain-slaughter/slaughter.json').then(function (r) { return r.ok ? r.json() : null; }).catch(function () { return null; }).then(function (d) {
        if (!d || !d.periods) return null;
        var D = { doc: d, provinces: { ES: 1 }, slug: {} }; Object.keys(d.ccaa).forEach(function (s) { if (CODE[s]) { D.provinces[CODE[s]] = 1; D.slug[CODE[s]] = s; } }); return D;
      });
    },
    pname: function (id, i) { var N = window.DehesaRegionNames && window.DehesaRegionNames.ES, v = N && N[id]; if (!v) return id; var p = v.split('|'), L = { 0: 1, 1: 0, 2: 2, 3: 3 }[i]; return p[L] || p[0]; },
    measures: function (D, id) { return series(D, 'ES', id, 'heads') ? MEAS : []; },
    series: series,
    fmt: function (m, v) {
      var l = window.DehesaShared.getLang();
      if (m === 'weight') return nf(l, v, 1) + ' kg';
      if (m === 'carcass') return v >= 1000 ? nf(l, v / 1000, 1) + ' kt' : nf(l, v, 0) + ' t';
      return v >= 1e6 ? nf(l, v / 1e6, 2) + ' M' : v >= 1e4 ? nf(l, v / 1000, 1) + ' k' : nf(l, v, 0);
    },
    chartX: function (x) { var d = new Date(x); try { return d.toLocaleDateString(window.DehesaShared.getLang(), { month: 'short', year: '2-digit', timeZone: 'UTC' }); } catch (e) { return String(d.getUTCFullYear()); } },
    chartV: function (m, v) { return nf(window.DehesaShared.getLang(), v, m === 'weight' ? 1 : 0); },
    yTitle: function (m) { return m === 'weight' ? 'kg' : m === 'carcass' ? 't' : ''; },
    shareMeasure: function (m) { return m !== 'weight'; }
  });
})();
