import os, urllib.request, re
os.makedirs('data/probe', exist_ok=True)
C = """https://landbrugsavisen.dk/rss.xml
https://landbrugsavisen.dk/feed
https://www.landbrugsavisen.dk/rss
https://effektivtlandbrug.landbrugsavisen.dk/rss.xml
https://www.bondebladet.dk/rss
https://www.bondebladet.dk/feed
https://lf.dk/rss
https://lf.dk/nyheder/rss
https://www.seges.dk/rss
https://www.landbrugsinfo.dk/rss
https://www.agriwatch.dk/feed
https://agriwatch.dk/rss
https://www.dr.dk/nyheder/service/feeds/penge
https://www.agrarheute.com/rss
https://www.agrarheute.com/rss/alle-artikel
https://www.topagrar.com/rss
https://www.topagrar.com/rss.xml
https://www.bauernverband.de/rss.xml
https://www.proplanta.de/rss/agrar-nachrichten.xml
https://www.agrarmarkt.de/feed
https://www.ble.de/SiteGlobals/Functions/RSSFeed/DE/RSSNewsfeed/RSSNewsfeed.xml
https://www.bmleh.de/SiteGlobals/Functions/RSSFeed/DE/RSSNewsfeed/RSSNewsfeed.xml
https://www.landwirt.com/rss/news.xml
https://www.bauernzeitung.at/feed
https://www.bauernzeitung.at/rss
https://www.lko.at/rss
https://www.ama.at/rss
https://www.boerenbond.be/rss
https://www.vilt.be/nl/rss
https://www.landbouwleven.be/rss
https://www.landbouwleven.be/feed
https://www.sillonbelge.be/feed
https://www.sillonbelge.be/rss
https://www.filagri.be/feed
https://www.boerderij.nl/rss
https://www.boerderij.nl/rss/nieuws
https://www.nieuweoogst.nl/rss
https://www.nieuweoogst.nl/feed
https://www.agd.nl/rss
https://www.foodagribusiness.nl/feed
https://www.wur.nl/nl/rss-nieuws.htm
https://www.nu.nl/rss/Economie
https://www.agroportal.pt/feed
https://www.agroportal.pt/feed/
https://vozdocampo.pt/feed
https://www.vidarural.pt/feed
https://www.agriculturaemar.com/feed
https://www.cap.pt/feed
https://www.gpp.pt/index.php/rss
https://www.confagri.pt/feed
https://www.publico.pt/rss
https://www.reussir.fr/rss
https://www.reussir.fr/rss.xml
https://www.agra.fr/rss
https://www.pleinchamp.com/rss
https://www.pleinchamp.com/rss.xml
https://www.franceagrimer.fr/rss
https://agreste.agriculture.gouv.fr/agreste-web/rss
https://www.fnsea.fr/feed
https://www.laterre.ca/feed
https://www.lebulletin.com/feed
https://www.topcropmanager.com/feed
https://www.farmersforum.com/feed
https://www.canolacouncil.org/feed
https://www.canadabeef.ca/feed
https://www.farmweekly.com.au/rss.xml
https://www.queenslandcountrylife.com.au/rss.xml
https://www.stockandland.com.au/rss.xml
https://www.sheepcentral.com/feed/
https://www.dairynewsaustralia.com.au/feed/
https://www.weeklytimesnow.com.au/rss
https://www.grdc.com.au/feed
https://www.graingrowers.com.au/feed
https://www.abares.gov.au/rss
https://www.mla.com.au/news-and-events/rss
https://www.brusselstimes.com/feed
https://www.dutchnews.nl/feed/
https://www.thelocal.de/feed/
https://www.thelocal.dk/feed/
https://www.portugalresident.com/feed/
https://www.euractiv.com/sections/agriculture-food/feed/
https://www.euractiv.fr/section/agriculture-alimentation/feed/
https://www.euractiv.de/section/landwirtschaft/feed/
https://www.agriculture.com/rss""".split()
out=[]
for u in C:
    try:
        r=urllib.request.urlopen(urllib.request.Request(u,headers={'User-Agent':'DehesaIndex-NewsBot/1.0 (+https://dehesaindex.com)','Accept':'application/rss+xml, application/atom+xml, text/xml, */*'}),timeout=20)
        d=r.read(400000).decode('utf8','replace')
        n=len(re.findall(r'<item[ >]|<entry[ >]',d)); dates=re.findall(r'<(?:pubDate|updated|published|dc:date)>([^<]+)<',d)[:1]
        out.append('%s | %s | %s items | %s | %s'%(r.status,u,n,dates,r.headers.get('Content-Type','')[:30]))
    except Exception as e: out.append('ERR | %s | %s'%(u,str(e)[:50]))
open('data/probe/news1.txt','w').write('\n'.join(out))
