#!/usr/bin/env python3
"""Pruebas negativas de los contratos: parte de datos REALES, los corrompe de una forma concreta y exige que validate-data los rechace.
Garantiza que los esquemas y tests semanticos 'muerden' (un validador que siempre dice OK es peor que ninguno). Uso: python3 scripts/test-contracts.py"""
import copy, fnmatch, importlib.util, json, sys, tempfile
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]; D = ROOT / "data"
spec = importlib.util.spec_from_file_location("vd", ROOT / "scripts" / "validate-data.py")
src = (ROOT / "scripts" / "validate-data.py").read_text().rsplit("\nmain()", 1)[0]
vd = type(sys)("vd"); vd.__file__ = str(ROOT / "scripts" / "validate-data.py"); exec(compile(src, "validate-data.py", "exec"), vd.__dict__)
def run(rel, mutate):
    doc = json.loads((D / rel).read_text()); mutate(doc)
    sch, tests = vd.REG["files"].get(rel) or next(v for pat, v in vd.REG["globs"].items() if fnmatch.fnmatchcase(rel, pat))
    with tempfile.TemporaryDirectory() as t:
        p = Path(t) / "x.json"; p.write_text(json.dumps(doc))
        return vd.validate_contract(p, rel, sch, tests)
def first(doc, key="observations"): return doc[key][0]
def _lw(d): return d["weeks"][sorted(d["weeks"])[-1]]
def _ls(d, m="Winnipeg"): return d["sales"][m][sorted(d["sales"][m])[-1]]
def _lh(d): return d["weeks"][sorted(d["weeks"])[-1]]
def _sc(d): return d["campaigns"]["2024"]["crops"]
def _scp(d):
    x = _sc(d)[0]; return x, next(iter(x["v"]))
def _sl(d): return d["v"]
def _sbv(d, y="2025"): return d["campaigns"][y]["v"]
def _sov(d, y="2025"): return d["campaigns"][y]["v"]
def _smk(d): return d["ccaa"]["galicia"]
def _swm(d): return d["national"]
def _swn(d): return d["national"]
def _ssl(d): return d["national"]["bovino"]
CASES = [
 ("blog/weekly/2026-W40.json", "totales por region que no suman", lambda d: d["totals"]["byRegion"].__setitem__("eu", d["totals"]["byRegion"]["eu"] + 1)),
 ("blog/weekly/2026-W40.json", "titular fuera de la cobertura", lambda d: d["top"][0].__setitem__("date", "2026-09-20")),
 ("blog/weekly/2026-W40.json", "mas de dos titulares del mismo medio", lambda d: [d["top"][i].__setitem__("source", "Mismo medio") for i in range(3)]),
 ("blog/weekly/2026-W40.json", "enlace que no es http", lambda d: d["top"][0].__setitem__("url", "ftp://x")),
 ("blog/weekly/2026-W40.json", "cobertura de solo 2 dias", lambda d: d["coverage"].__setitem__("days", 2)),
 ("blog/weekly/2026-W40.json", "pocas noticias", lambda d: d["totals"].__setitem__("items", 10)),
 ("blog/weekly/2026-W40.json", "fechas que no son lunes-domingo", lambda d: d.__setitem__("from", "2026-09-29")),
 ("news-archive/2026-W40.json", "noticia fuera de la semana", lambda d: d["items"][0].__setitem__("date", "2026-01-01")),
 ("news-archive/2026-W40.json", "id repetido entre completo y ligero", lambda d: d["rest"].append([d["items"][0]["id"], d["items"][0]["date"], "eu", "", [], "X"])),
 ("news-archive/2026-W40.json", "cobertura fuera de la semana", lambda d: d["coverage"].__setitem__("from", "2026-10-20")),
 ("news-archive/2026-W40.json", "registro ligero malformado", lambda d: d["rest"].__setitem__(0, ["x", "2026-09-30", "eu", "", "no-lista", "M"])),
 ("blog/weekly/index.json", "semanas repetidas", lambda d: d["weeks"].append(dict(d["weeks"][0]))),
 ("blog/weekly/index.json", "cobertura fuera de la semana", lambda d: d["weeks"][0].__setitem__("coverageFrom", "2026-01-01")),

 ("spain-milk/infolac.json", "comunidades que no suman las entregas", lambda d: _smk(d)["production"].__setitem__(-1, _smk(d)["production"][-1] + 5000)),
 ("spain-milk/infolac.json", "precio imposible", lambda d: d["national"]["price"].__setitem__(-1, 5.0)),
 ("spain-milk/infolac.json", "entregas negativas", lambda d: d["national"]["deliveries"].__setitem__(-1, -1)),
 ("spain-milk/infolac.json", "grasa fuera de rango", lambda d: _smk(d)["fat"].__setitem__(-1, 30)),
 ("spain-milk/infolac.json", "leche ecologica mayor que las entregas", lambda d: d["national"]["organic"].__setitem__(-1, 9999999)),
 ("spain-milk/infolac.json", "comunidad que falta", lambda d: d["ccaa"].pop("galicia")),
 ("spain-milk/infolac.json", "serie mas corta que los periodos", lambda d: d["national"]["farmers"].pop()),
 ("spain-milk/infolac.json", "informe que no es el ultimo periodo", lambda d: d["report"].__setitem__("month", "2025-01")),
 ("spain-slaughter/slaughter.json", "cabezas negativas", lambda d: _ssl(d)["heads"].__setitem__(-1, -1)),
 ("spain-slaughter/slaughter.json", "peso canal imposible", lambda d: d["national"]["porcino"]["carcass"].__setitem__(-1, 9e6)),
 ("spain-slaughter/slaughter.json", "comunidades que superan el nacional", lambda d: d["ccaa"]["galicia"]["bovino"]["heads"].__setitem__(-1, 9e7)),
 ("spain-slaughter/slaughter.json", "comunidad que falta", lambda d: d["ccaa"].pop("galicia")),
 ("spain-slaughter/slaughter.json", "serie mas corta que los periodos", lambda d: d["national"]["ovino"]["heads"].pop()),
 ("spain-slaughter/slaughter.json", "libro que no es el ultimo periodo", lambda d: d["report"].__setitem__("last", "2025-01")),
 ("spain-slaughter/slaughter.json", "periodos desordenados", lambda d: d["periods"].reverse()),
 ("spain-slaughter/census.json", "cabezas negativas", lambda d: d["v"]["15"]["bovino"]["heads"].__setitem__(-1, -1)),
 ("spain-slaughter/census.json", "aves en miles en vez de cabezas", lambda d: d["v"]["ES"]["aves"]["heads"].__setitem__(-1, 892656.69)),
 ("spain-slaughter/census.json", "comunidades que no suman el total", lambda d: d["provTotal"]["porcino"]["heads"].__setitem__(0, d["provTotal"]["porcino"]["heads"][0] + 900000)),
 ("spain-slaughter/census.json", "provincias que superan a su comunidad sin anotar", lambda d: d["v"]["22"]["porcino"]["heads"].__setitem__(-1, d["v"]["22"]["porcino"]["heads"][-1] + 800000)),
 ("spain-slaughter/census.json", "dato confidencial con cifra", lambda d: d["v"]["42"]["bovino"]["heads"].__setitem__(-1, 1234)),
 ("spain-slaughter/census.json", "provincia que falta", lambda d: d["v"].pop("15")),
 ("spain-slaughter/census.json", "serie mas corta que los años", lambda d: d["v"]["ES"]["ovino"]["meat"].pop()),
 ("spain-slaughter/census.json", "años desordenados", lambda d: d["years"].reverse()),
 ("spain-slaughter/census.json", "España distinta de total + otros", lambda d: d["v"]["ES"]["ovino"]["heads"].__setitem__(0, d["v"]["ES"]["ovino"]["heads"][0] + 3000000)),
 ("spain-wine/infovi.json", "vino negativo", lambda d: _swn(d)["wine"].__setitem__(-1, -1)),
 ("spain-wine/infovi.json", "comunidades que no suman el total", lambda d: d["ccaa"]["clm"]["wine"].__setitem__(-1, d["ccaa"]["clm"]["wine"][-1] + 900000)),
 ("spain-wine/infovi.json", "tinto+blanco distinto del vino", lambda d: _swn(d)["red"].__setitem__(-1, _swn(d)["red"][-1] + 900000)),
 ("spain-wine/infovi.json", "salidas distintas de exportaciones + interiores", lambda d: _swn(d)["exports"].__setitem__(-1, _swn(d)["exports"][-1] + 900000)),
 ("spain-wine/infovi.json", "rendimiento uva-vino imposible", lambda d: _swn(d)["grape"].__setitem__(-1, 1.0)),
 ("spain-wine/infovi.json", "comunidad que falta", lambda d: d["ccaa"].pop("galicia")),
 ("spain-wine/infovi.json", "serie mas corta que las campañas", lambda d: _swn(d)["exits"].pop()),
 ("spain-wine/infovi.json", "campaña sin fuente", lambda d: d["sources"].pop(d["campaigns"][-1])),
 ("spain-wine/infovi.json", "campañas desordenadas", lambda d: d["campaigns"].reverse()),
 ("spain-wine/balance-historic.json", "existencias negativas", lambda d: d["v"]["7"]["total"]["all"].__setitem__(0, -1)),
 ("spain-wine/balance-historic.json", "recursos que no cuadran", lambda d: d["v"]["4"]["total"]["all"].__setitem__(2, d["v"]["4"]["total"]["all"][2] + 900)),
 ("spain-wine/balance-historic.json", "categorias que no suman el total", lambda d: d["v"]["5"]["dop"]["all"].__setitem__(1, d["v"]["5"]["dop"]["all"][1] + 800)),
 ("spain-wine/balance-historic.json", "existencias que no encadenan", lambda d: d["v"]["1"]["total"]["all"].__setitem__(3, d["v"]["1"]["total"]["all"][3] + 500)),
 ("spain-wine/balance-historic.json", "blanco mayor que el total sin anotar", lambda d: (d["v"]["7.1"]["igp"]["white"].__setitem__(0, d["v"]["7.1"]["igp"]["all"][0] + 50))),
 ("spain-wine/balance-historic.json", "epigrafe que falta", lambda d: d["v"].pop("6.4")),
 ("spain-wine/balance-historic.json", "campañas desordenadas", lambda d: d["campaigns"].reverse()),
 ("spain-wine/balance-historic.json", "serie mas corta que las campañas", lambda d: d["v"]["3"]["total"]["all"].pop()),
 ("spain-wine/monthly.json", "existencias negativas", lambda d: _swm(d)["stockEnd"].__setitem__(-1, -1)),
 ("spain-wine/monthly.json", "comunidades que no suman el total", lambda d: d["ccaa"]["clm"]["stockEnd"].__setitem__(-1, d["ccaa"]["clm"]["stockEnd"][-1] + 900000)),
 ("spain-wine/monthly.json", "salidas distintas de interiores + exteriores", lambda d: _swm(d)["exitsTotal"].__setitem__(-1, _swm(d)["exitsTotal"][-1] + 900000)),
 ("spain-wine/monthly.json", "identidad de existencias rota", lambda d: _swm(d)["stockEnd"].__setitem__(-1, _swm(d)["stockEnd"][-1] * 3)),
 ("spain-wine/monthly.json", "comunidad que falta", lambda d: d["ccaa"].pop("galicia")),
 ("spain-wine/monthly.json", "serie mas corta que los meses", lambda d: _swm(d)["production"].pop()),
 ("spain-wine/monthly.json", "mes sin fuente", lambda d: d["sources"].pop(d["months"][-1])),
 ("spain-wine/monthly.json", "meses desordenados", lambda d: d["months"].reverse()),
 ("spain-balances/olive.json", "produccion que rompe el total de origen", lambda d: _sov(d)["oil"].__setitem__("production", _sov(d)["oil"]["production"] + 300)),
 ("spain-balances/olive.json", "existencias finales que no cuadran", lambda d: _sov(d)["oil"].__setitem__("endingStocks", _sov(d)["oil"]["endingStocks"] + 80)),
 ("spain-balances/olive.json", "exportaciones UE + extra UE que no suman", lambda d: _sov(d, "2024")["oil"].__setitem__("exportsEU", _sov(d, "2024")["oil"]["exportsEU"] + 50)),
 ("spain-balances/olive.json", "importacion negativa", lambda d: _sov(d)["pomace"].__setitem__("imports", -5)),
 ("spain-balances/olive.json", "estado inventado", lambda d: d["campaigns"]["2024"].__setitem__("status", "oficial")),
 ("spain-balances/olive.json", "aforo que no suma el total", lambda d: d["aforo"]["ccaa"][0].__setitem__("estimate", d["aforo"]["ccaa"][0]["estimate"] + 90000)),
 ("spain-balances/olive.json", "aforo de una campaña ya cerrada", lambda d: d["aforo"].__setitem__("campaign", 2024)),
 ("spain-balances/cereals.json", "produccion que rompe las disponibilidades de un cereal", lambda d: _sbv(d)["barley"].__setitem__("production", _sbv(d)["barley"]["production"] + 5000)),
 ("spain-balances/cereals.json", "existencias finales que no cuadran", lambda d: _sbv(d)["maize"].__setitem__("endingStocks", _sbv(d)["maize"]["endingStocks"] + 900)),
 ("spain-balances/cereals.json", "exportacion negativa", lambda d: _sbv(d)["oats"].__setitem__("exports", -3)),
 ("spain-balances/cereals.json", "discrepancia del total escondida (nota borrada)", lambda d: d["campaigns"]["2019"]["notes"].clear()),
 ("spain-balances/cereals.json", "discrepancia del total inventada (nota sin base)", lambda d: d["campaigns"]["2024"]["notes"].append({"item": "production", "printed": 1, "computed": 2, "rule": "x"})),
 ("spain-balances/cereals.json", "etiqueta de campaña que no es la clave", lambda d: d["campaigns"]["2025"].__setitem__("label", "2024/25")),
 ("spain-balances/cereals.json", "cereal que falta", lambda d: _sbv(d).pop("rye")),
 ("spain-livestock/livestock-bovino.json", "provincia que no suma el total nacional", lambda d: _sl(d)["ES"]["01"].__setitem__(-1, _sl(d)["ES"]["01"][-1] + 50000)),
 ("spain-livestock/livestock-bovino.json", "valor negativo", lambda d: _sl(d)["28"]["01"].__setitem__(-1, -5)),
 ("spain-livestock/livestock-bovino.json", "total nacional que no suma sus componentes", lambda d: (_sl(d)["ES"]["01"].__setitem__(-1, _sl(d)["ES"]["01"][-1] + 90000), [_sl(d)["28"]["01"].__setitem__(-1, _sl(d)["28"]["01"][-1] + 90000)])),
 ("spain-livestock/livestock-bovino.json", "provincia inexistente", lambda d: _sl(d).__setitem__("77", dict(_sl(d)["28"]))),
 ("spain-livestock/livestock-bovino.json", "serie de longitud distinta", lambda d: _sl(d)["28"]["01"].pop()),
 ("spain-livestock/livestock-porcino.json", "periodos desordenados", lambda d: d["periods"].reverse()),
 ("spain-livestock/index.json", "fichero que no es el de la especie", lambda d: d["species"]["bovino"].__setitem__("file", "livestock-ovino.json")),
 ("latest.json", "valor no numerico", lambda d: first(d).__setitem__("value", "n/a")),
 ("latest.json", "region desconocida", lambda d: first(d).__setitem__("region", "mars")),
 ("latest.json", "id repetido", lambda d: d["observations"].append(copy.deepcopy(d["observations"][0]))),
 ("latest.json", "fecha futura", lambda d: first(d).__setitem__("observationDate", "2099-01-01")),
 ("latest.json", "indice con moneda", lambda d: [o.__setitem__("currency", "EUR") for o in d["observations"] if o["currency"] == "INDEX"][:1]),
 ("history.json", "id sin fecha", lambda d: first(d).__setitem__("id", "di_x")),
 ("quality.json", "stale incoherente", lambda d: d["observations"][0].__setitem__("stale", not d["observations"][0]["stale"])),
 ("quality.json", "scope incoherente", lambda d: d["scope"].__setitem__("stale", 999)),
 ("cross-market.json", "correlacion > 1", lambda d: d["relationships"][0].__setitem__("correlationReturns", 1.7)),
 ("relationships.json", "r fuera de [-1,1]", lambda d: d["relationships"][0]["stat"].__setitem__("correlation", 1.4)),
 ("relationships.json", "status inventado", lambda d: next(r for r in d["relationships"] if r["status"] == "WEAK_OR_UNSTABLE").__setitem__("status", "OBSERVED_RELATIONSHIP")),
 ("relationships.json", "confianza inflada", lambda d: next(r for r in d["relationships"] if r["confidence"] == "LOW").__setitem__("confidence", "HIGH")),
 ("relationships.json", "rezago no probado", lambda d: d["relationships"][0]["stat"].__setitem__("lag", 77)),
 ("relationships.json", "n alterado (recalculo)", lambda d: d["relationships"][0]["stat"].__setitem__("n", d["relationships"][0]["stat"]["n"] + 5)),
 ("relationships.json", "explicacion sin descargo", lambda d: d["relationships"][0]["explanation"].__setitem__("es", "Este insumo hace subir el precio.")),
 ("relationships.json", "clima tratado como cambio", lambda d: next(r for r in d["relationships"] if r["input"]["key"].startswith("C/"))["stat"].__setitem__("inputTransform", "change")),
 ("relationships.json", "existencias alteradas (recalculo)", lambda d: next(r for r in d["relationships"] if r["family"] == "stocks_to_price")["stat"].__setitem__("n", 40)),
 ("relationships.json", "id repetido", lambda d: d["relationships"].append(copy.deepcopy(d["relationships"][0]))),
 ("observatory.json", "movimiento alterado", lambda d: next(o for o in d["observations"] if o["moves"]["d30"])["moves"]["d30"].__setitem__("pct", 99.9)),
 ("observatory.json", "ventana incumplida", lambda d: next(o for o in d["observations"] if o["moves"]["d7"])["moves"]["d7"].__setitem__("days", 40)),
 ("observatory.json", "isNew incoherente", lambda d: d["observations"][0].__setitem__("isNew", not d["observations"][0]["isNew"])),
 ("observatory.json", "claves repetidas", lambda d: d["observations"].append(copy.deepcopy(d["observations"][0]))),
 ("observatory.json", "pipelines sin cuadrar", lambda d: d["pipelines"]["summary"].__setitem__("ok", d["pipelines"]["summary"]["ok"] + 1)),
 ("observatory.json", "frescura sin cuadrar", lambda d: d["freshness"]["catalog"]["byState"].__setitem__("LIVE", 1)),
 ("observatory.json", "cambio de cobertura inventado", lambda d: d["coverage"]["changes"].append({"scope": "country", "key": "XX", "from": 1, "to": 2})),
 ("source-candidates.json", "sourceId repetido", lambda d: d["candidates"].append(copy.deepcopy(d["candidates"][0]))),
 ("source-candidates.json", "licencia inventada sin registro", lambda d: next(c for c in d["candidates"] if c["sourceId"] == "ibge_sidra").__setitem__("commercialReuse", "yes")),
 ("source-candidates.json", "READY sin registro", lambda d: next(c for c in d["candidates"] if c["sourceId"] == "ibge_sidra").__setitem__("ingestionStatus", "READY")),
 ("source-candidates.json", "fuente RESTRICTED marcada ACTIVE", lambda d: next(c for c in d["candidates"] if c["sourceId"] == "conab").__setitem__("ingestionStatus", "ACTIVE")),
 ("source-candidates.json", "ingesta sin gate READY", lambda d: next(c for c in d["candidates"] if c["sourceId"] == "sima_gpp").__setitem__("ingestionStatus", "INGESTING")),
 ("source-candidates.json", "gate alterado", lambda d: next(c for c in d["candidates"] if c["sourceId"] == "abares")["gate"].__setitem__("result", "READY")),
 ("source-candidates.json", "canStart con bloqueo tecnico", lambda d: next(c for c in d["candidates"] if c["sourceId"] == "de_genesis_api").__setitem__("canStart", True)),
 ("source-candidates.json", "licenseStatus alterado", lambda d: next(c for c in d["candidates"] if c["sourceId"] == "mla").__setitem__("licenseStatus", "VERIFIED")),
 ("source-candidates.json", "fuente integrada desaparecida", lambda d: d["candidates"].remove(next(c for c in d["candidates"] if c["ingestionStatus"] == "ACTIVE"))),
 ("source-candidates.json", "resumen sin cuadrar", lambda d: d["summary"]["byStatus"].__setitem__("READY", 9)),
 ("premium-tracker.json", "diferencial que no cuadra con las medianas", lambda d: next(c for c in d["cells"] if c["premium"] is not None).__setitem__("premium", 99.0)),
 ("premium-tracker.json", "porcentaje inventado", lambda d: next(c for c in d["cells"] if c["premium"] is not None).__setitem__("premiumPct", 500.0)),
 ("premium-tracker.json", "muestra convencional insuficiente", lambda d: next(c for c in d["cells"] if c["premium"] is not None)["conventional"].__setitem__("n", 2)),
 ("premium-tracker.json", "premium sin parte convencional", lambda d: next(c for c in d["cells"] if c["premium"] is not None).__setitem__("conventional", None)),
 ("premium-tracker.json", "celda vacia sin motivo", lambda d: next(c for c in d["cells"] if c["premium"] is None).__setitem__("reason", None)),
 ("home-tape.json", "valor distinto del original", lambda d: d["rows"][0].__setitem__("value", d["rows"][0]["value"] + 1)),
 ("home-tape.json", "fila duplicada", lambda d: d["rows"].append(dict(d["rows"][0]))),
 ("home-tape.json", "moneda cambiada", lambda d: d["rows"][0].__setitem__("currency", "XXX")),
 ("home-explore.json", "porcentaje de sequia cambiado", lambda d: next(f for f in d["facts"] if f["id"] == "drought").__setitem__("pctD1", 1.0)),
 ("home-explore.json", "hecho duplicado", lambda d: d["facts"].append(dict(d["facts"][0]))),
 ("home-explore.json", "inventario cambiado", lambda d: next(f for f in d["facts"] if f["id"] == "cattle").__setitem__("onFeedKhead", 1)),
 ("home-explore.json", "origen inexistente", lambda d: d["facts"][0].__setitem__("file", "no-existe.json")),
 ("worldbank-agri.json", "licencia distinta de CC BY", lambda d: next(iter(d["indicators"].values())).__setitem__("license", "CC BY-NC-4.0")),
 ("worldbank-agri.json", "porcentaje superior a 100", lambda d: d["countries"]["ES"]["agriLandPct"]["v"].__setitem__(-1, 140.0)),
 ("worldbank-agri.json", "produccion que no cuadra con rendimiento x superficie", lambda d: d["countries"]["FR"]["cerealProd"]["v"].__setitem__(-1, d["countries"]["FR"]["cerealProd"]["v"][-1] * 2)),
 ("worldbank-agri.json", "tipo de cambio de zona euro anterior a 1999", lambda d: d["countries"]["ES"]["fxUsd"].__setitem__("y0", 1990)),
 ("worldbank-agri.json", "serie que acaba sin dato", lambda d: d["countries"]["DE"]["cpi"]["v"].append(None)),
 ("germany-agri.json", "alquiler absurdo", lambda d: d["rent"]["nat"]["lf"].__setitem__(-1, [2023, 99999.0])),
 ("germany-agri.json", "Land inexistente", lambda d: d["landPrice"]["land"].__setitem__("XX", d["landPrice"]["land"]["BY"])),
 ("germany-agri.json", "años que no crecen", lambda d: d["production"]["nat"]["wheat"]["area"].append([1960, 1000.0])),
 ("germany-agri.json", "produccion que no cuadra con rendimiento x superficie", lambda d: d["production"]["land"]["wheat"]["BY"]["prod"].__setitem__(-2, [d["production"]["land"]["wheat"]["BY"]["prod"][-2][0], d["production"]["land"]["wheat"]["BY"]["prod"][-2][1] * 3])),
 ("germany-agri.json", "precio de la tierra negativo", lambda d: d["landPrice"]["nat"]["lf"]["p"].__setitem__(0, [2021, -5.0])),
 ("spain-crops/crops-cereales.json", "total nacional que no es la suma de provincias", lambda d: _sc(d)[0]["t"].__setitem__(4, _sc(d)[0]["t"][4] + 5000)),
 ("spain-crops/crops-cereales.json", "secano + regadio distinto del total", lambda d: (lambda x, p: x["v"][p].__setitem__(1, (x["v"][p][0] or 0) + 500))(*_scp(d))),
 ("spain-crops/crops-cereales.json", "superficie cosechada nacional mayor que la total", lambda d: _sc(d)[0]["t"].__setitem__(3, _sc(d)[0]["t"][0] * 2 + 10)),
 ("spain-crops/crops-cereales.json", "provincia que no existe en el diccionario", lambda d: _sc(d)[0]["v"].__setitem__("99", [1, 1, 0, 1, 1])),
 ("spain-crops/crops-cereales.json", "produccion negativa", lambda d: (lambda x, p: x["v"][p].__setitem__(4, -3))(*_scp(d))),
 ("spain-crops/crops-cereales.json", "estado de campana inventado", lambda d: d["campaigns"]["2024"].__setitem__("status", "oficial")),
 ("spain-crops/crops-cereales.json", "campana en el futuro", lambda d: d["campaigns"].__setitem__("2099", d["campaigns"]["2024"])),
 ("spain-crops/crops-cereales.json", "cultivo repetido", lambda d: _sc(d).append(copy.deepcopy(_sc(d)[0]))),
 ("spain-crops/crops-cereales.json", "fuente que no es el MAPA", lambda d: d["source"].__setitem__("id", "otra")),
 ("spain-crops/crops-cereales.json", "unidad de produccion cambiada", lambda d: d["units"].__setitem__("production", "kg")),
 ("spain-crops/index.json", "grupo que apunta a otro fichero", lambda d: next(iter(d["groups"].values())).__setitem__("file", "otro.json")),
 ("spain-crops/index.json", "campana sin libro que la respalde", lambda d: next(iter(d["groups"].values()))["campaigns"].append(2031)),
 ("mb-markets/cattle.json", "cabezas que no suman el total", lambda d: _lw(d)["head"].__setitem__("Ashern", _lw(d)["head"]["Ashern"] + 7)),
 ("mb-markets/cattle.json", "media por encima del maximo", lambda d: _lw(d)["summary"][0].__setitem__(2, _lw(d)["summary"][0][1] + 20)),
 ("mb-markets/cattle.json", "precio absurdo", lambda d: _lw(d)["summary"][3].__setitem__(2, 9.5)),
 ("mb-markets/cattle.json", "subasta inexistente", lambda d: _lw(d)["marts"].__setitem__("Atlantis", _lw(d)["marts"].pop("Ashern"))),
 ("mb-markets/cattle.json", "venta fuera de la semana del informe", lambda d: next(m for m in _lw(d)["marts"].values() if m["date"]).__setitem__("date", "2020-01-01")),
 ("mb-markets/cattle.json", "sin venta pero con precios", lambda d: next(m for m in _lw(d)["marts"].values() if m["date"]).__setitem__("date", None)),
 ("mb-markets/cattle.json", "semanas desordenadas", lambda d: d.__setitem__("weeks", dict(reversed(list(d["weeks"].items()))))),
 ("mb-markets/cattle.json", "resumen con una clase menos", lambda d: _lw(d)["summary"].pop()),
 ("mb-markets/sheep-goat.json", "media por encima del maximo", lambda d: _ls(d).__setitem__(0, [_ls(d)[0][0], _ls(d)[0][1], _ls(d)[0][1] + 20])),
 ("mb-markets/sheep-goat.json", "precio de cabra por cabeza colado como C$/cwt (absurdo)", lambda d: _ls(d).__setitem__(7, [5.0, 9.0, 7.0])),
 ("mb-markets/sheep-goat.json", "venta en domingo", lambda d: d["sales"]["Winnipeg"].__setitem__("2026-09-20", d["sales"]["Winnipeg"].pop(sorted(d["sales"]["Winnipeg"])[-1]))),
 ("mb-markets/sheep-goat.json", "ventas desordenadas", lambda d: d["sales"].__setitem__("Winnipeg", dict(reversed(list(d["sales"]["Winnipeg"].items()))))),
 ("mb-markets/sheep-goat.json", "una clase menos", lambda d: _ls(d).pop()),
 ("mb-markets/sheep-goat.json", "subasta inexistente", lambda d: d["sales"].__setitem__("Atlantis", d["sales"].pop("Grunthal"))),
 ("mb-markets/sheep-goat.json", "celda en disputa con valor", lambda d: d["disputed"].append("Winnipeg|%s|1" % sorted(d["sales"]["Winnipeg"])[-1])),
 ("mb-markets/sheep-goat.json", "fuente distinta", lambda d: d["source"].__setitem__("id", "canfax")),
 ("mb-markets/hogs.json", "all-in absurdo", lambda d: _lh(d).__setitem__(0, 24.0)),
 ("mb-markets/hogs.json", "all-in y Index 100 incoherentes", lambda d: _lh(d).__setitem__(1, _lh(d)[0] * 2)),
 ("mb-markets/hogs.json", "semana que no acaba en viernes", lambda d: d["weeks"].__setitem__("2026-09-26", d["weeks"].pop(sorted(d["weeks"])[-1]))),
 ("mb-markets/hogs.json", "peso de canal de 12 kg", lambda d: _lh(d).__setitem__(3, 12.0)),
 ("mb-markets/hogs.json", "salto semanal del 60 %", lambda d: _lh(d).__setitem__(0, _lh(d)[0] * 1.8) or _lh(d).__setitem__(1, _lh(d)[1] * 1.8)),
 ("mb-markets/hogs.json", "semanas desordenadas", lambda d: d.__setitem__("weeks", dict(reversed(list(d["weeks"].items()))))),
 ("mb-markets/cattle.json", "unidad cambiada", lambda d: d.__setitem__("unit", "US$/cwt")),
 ("mb-markets/cattle.json", "fuente distinta", lambda d: d["source"].__setitem__("id", "canfax")),
 ("germany-agri.json", "licencia cambiada", lambda d: d["source"].__setitem__("license", "CC0")),
 ("us-local/cattle-KS.json", "informe distinto del registro", lambda d: d["source"].__setitem__("reportId", 1234)),
 ("us-local/cattle-KS.json", "fecha en el futuro", lambda d: d["latest"].__setitem__("date", "2031-01-01")),
 ("us-local/cattle-KS.json", "cabezas a cero", lambda d: d["latest"]["rows"][0].__setitem__(8, 0)),
 ("us-local/cattle-KS.json", "precio medio fuera del minimo y el maximo", lambda d: d["latest"]["rows"][0].__setitem__(12, d["latest"]["rows"][0][11] + 50)),
 ("us-local/cattle-KS.json", "precio por cwt absurdo (unidad equivocada)", lambda d: [d["latest"]["rows"][0].__setitem__(i, v) for i, v in ((10, 40000), (11, 40000), (12, 40000))]),
 ("us-local/cattle-KS.json", "novillo con peso medio de 25 lb (solo cabras, ovejas y corderos pueden pesar tan poco)", lambda d: next(r for r in d["latest"]["rows"] if r[0] == "Feeder Cattle").__setitem__(9, 25)),
 ("us-local/cattle-KS.json", "tramo de peso invertido", lambda d: next(r for r in d["latest"]["rows"] if r[6] is not None).__setitem__(7, 100)),
 ("us-local/cattle-KS.json", "historial que no coincide con las filas de la ultima semana", lambda d: d["history"]["Steers|500"].__setitem__(-1, [d["history"]["Steers|500"][-1][0], 999.0, d["history"]["Steers|500"][-1][2], d["history"]["Steers|500"][-1][3]])),
 ("us-local/cattle-KS.json", "fechas del historial que no crecen", lambda d: d["history"]["Steers|500"].append(["2020-01-01", 300.0, 5, 500.0])),
 ("us-local/cattle-KS.json", "clave de serie desconocida", lambda d: d["history"].__setitem__("Cows|500", d["history"]["Steers|500"])),
 ("us-local/cattle-KS.json", "recibos negativos", lambda d: d["receipts"].__setitem__(-1, [d["receipts"][-1][0], -5])),
 ("us-local/hay-KS.json", "unidad desconocida", lambda d: d["latest"]["rows"][0].__setitem__(3, "Per Chicken")),
 ("us-local/hay-KS.json", "precio minimo mayor que el maximo", lambda d: d["latest"]["rows"][0].__setitem__(12, d["latest"]["rows"][0][13] + 10)),
 ("us-local/hay-KS.json", "media fuera del rango", lambda d: d["latest"]["rows"][0].__setitem__(14, d["latest"]["rows"][0][13] + 100)),
 ("us-local/hay-KS.json", "tonelada de heno a 5 dolares (unidad equivocada)", lambda d: [d["latest"]["rows"][0].__setitem__(i, 5) for i in (12, 13, 14)]),
 ("us-local/hay-KS.json", "serie del historial que no tiene la ultima semana", lambda d: d["history"].pop("|".join(d["latest"]["rows"][0][:11]))),
 ("us-local/hay-KS.json", "informe de otro estado", lambda d: d.__setitem__("state", "TX")),
 ("us-local/status.json", "informe repetido", lambda d: d["reports"].append(dict(d["reports"][0]))),
 ("us-local/status.json", "informe fuera del registro", lambda d: d["reports"][0].__setitem__("reportId", 1)),
 ("us-local/status.json", "faltan informes del registro", lambda d: d["reports"].pop()),
 ("germany-livestock.json", "licencia cambiada", lambda d: d["source"].__setitem__("license", "CC0")),
 ("germany-livestock.json", "peso de canal de cerdo absurdo", lambda d: d["slaughter"]["nat"]["pigs"]["tonnes"]["dom"].__setitem__(-1, [d["slaughter"]["nat"]["pigs"]["tonnes"]["dom"][-1][0], d["slaughter"]["nat"]["pigs"]["tonnes"]["dom"][-1][1] * 5])),
 ("germany-livestock.json", "suma de Länder que no cuadra con el total", lambda d: d["slaughter"]["land"]["pigs"]["NI"]["heads"]["dom"].__setitem__(-1, [d["slaughter"]["land"]["pigs"]["NI"]["heads"]["dom"][-1][0], d["slaughter"]["land"]["pigs"]["NI"]["heads"]["dom"][-1][1] * 2])),
 ("germany-livestock.json", "los 12 meses no suman el año", lambda d: d["slaughter"]["month"]["cattle"]["heads"]["dom"].__setitem__(-14, [d["slaughter"]["month"]["cattle"]["heads"]["dom"][-14][0], d["slaughter"]["month"]["cattle"]["heads"]["dom"][-14][1] * 2])),
 ("germany-livestock.json", "huevos que no cuadran con gallinas", lambda d: d["eggs"]["nat"]["eggs"].__setitem__(-1, [d["eggs"]["nat"]["eggs"][-1][0], d["eggs"]["nat"]["eggs"][-1][1] * 2])),
 ("germany-livestock.json", "periodos que no crecen", lambda d: d["herd"]["cattle"]["total"].append(["2010-05", 1.0])),
 ("germany-livestock.json", "Land inexistente", lambda d: d["eggs"]["land"].__setitem__("XX", d["eggs"]["land"]["BY"])),
 ("germany-livestock.json", "vacas lecheras mas nodrizas por encima del total", lambda d: d["herd"]["cattle"]["dairy"].__setitem__(-1, [d["herd"]["cattle"]["dairy"][-1][0], d["herd"]["cattle"]["total"][-1][1]])),
 ("germany-livestock.json", "aves por encima del total", lambda d: d["poultry"]["broilers"]["tonnes"].__setitem__(-1, [d["poultry"]["broilers"]["tonnes"][-1][0], d["poultry"]["total"]["tonnes"][-1][1] * 3])),
 ("germany-livestock.json", "rendimiento de fruta absurdo", lambda d: d["fruit"]["apples"]["prod"].__setitem__(-2, [d["fruit"]["apples"]["prod"][-2][0], d["fruit"]["apples"]["prod"][-2][1] * 20])),
 ("germany-livestock.json", "valor negativo", lambda d: d["herd"]["pigs"]["sows"].__setitem__(-1, [d["herd"]["pigs"]["sows"][-1][0], -4])),
 ("denmark-depth.json", "fuente cambiada", lambda d: d["source"].__setitem__("id", "dst_dk2")),
 ("denmark-depth.json", "region inexistente en la cosecha", lambda d: d["harvest"]["data"]["wheat_winter"].__setitem__("999", d["harvest"]["data"]["wheat_winter"]["000"])),
 ("denmark-depth.json", "rendimiento nacional que no cuadra", lambda d: [d["harvest"]["data"]["wheat_winter"]["000"]["yield"].__setitem__(i, [p[0], p[1] * 3]) for i, p in enumerate(d["harvest"]["data"]["wheat_winter"]["000"]["yield"])]),
 ("denmark-depth.json", "mes invalido en sacrificios", lambda d: d["slaughter"]["pigs"]["pigs"]["heads"].append(["2026-13", 1.0])),
 ("netherlands-farm.json", "fuente cambiada", lambda d: d["source"].__setitem__("id", "cbs")),
 ("netherlands-farm.json", "vacas lecheras por encima del total de bovino", lambda d: d["farms"]["data"]["dairy_cows"]["NL01"].__setitem__(-1, [d["farms"]["data"]["dairy_cows"]["NL01"][-1][0], d["farms"]["data"]["cattle"]["NL01"][-1][1] * 2])),
 ("netherlands-farm.json", "indice de precios absurdo", lambda d: d["priceIndex"]["data"]["pigs"].__setitem__(-1, [d["priceIndex"]["data"]["pigs"][-1][0], 9000])),
 ("netherlands-farm.json", "region inexistente", lambda d: d["farms"]["data"]["pigs"].__setitem__("XX00", d["farms"]["data"]["pigs"]["NL01"])),
 ("netherlands-markets.json", "fuente cambiada", lambda d: d["source"].__setitem__("id", "x")),
 ("netherlands-markets.json", "precio del cerdo absurdo", lambda d: d["pigPrice"]["pigs"].__setitem__(-1, [d["pigPrice"]["pigs"][-1][0], 12.0])),
 ("netherlands-markets.json", "semanas que no crecen", lambda d: d["pigPrice"]["pigs"].append(["2000-W01", 100.0])),
 ("netherlands-markets.json", "clases SEUROP que no suman 100", lambda d: d["pigSlaughter"]["grade_E"].__setitem__(-1, [d["pigSlaughter"]["grade_E"][-1][0], 5.0])),
 ("france-vigieau.json", "nivel desconocido", lambda d: d["departments"][0].__setitem__("level", "rojo")),
 ("france-vigieau.json", "recuento que no cuadra con los departamentos", lambda d: d["counts"].__setitem__("crise", d["counts"]["crise"] + 3)),
 ("france-vigieau.json", "reparto de riego que supera las zonas", lambda d: d["farm"]["departments"][next(iter(d["farm"]["departments"]))].__setitem__("irr", [99, 0, 0])),
 ("france-vigieau.json", "zonas de un departamento que no existe", lambda d: d["farm"]["departments"].__setitem__("99X", {"z": 1, "irr": [0, 0, 0], "wat": [0, 0, 0]})),
 ("france-vigieau.json", "historial con fechas que no crecen", lambda d: d["history"].append(dict(d["history"][-1]))),
 ("france-cereobs.json", "porcentaje por encima de 100", lambda d: d["national"][-1].__setitem__(1, 140)),
 ("france-cereobs.json", "clases de estado que no suman 100", lambda d: d["national"][-1].__setitem__(-1, 60)),
 ("france-cereobs.json", "region vacia", lambda d: d["regions"].__setitem__("Bretagne", [])),
 ("coverage-gaps.json", "NOT_APPLICABLE sin entrada en overrides", lambda d: d["matrix"]["ES"]["wheat"]["production"].__setitem__("state", "NOT_APPLICABLE")),
 ("coverage-gaps.json", "INDEX_ONLY sin indice", lambda d: d["matrix"]["AT"]["cheese"]["price"].update(state="INDEX_ONLY", basis=None) or d["matrix"]["AT"]["cheese"]["price"].pop("basis")),
 ("cap/eu/allocations.json", "total EU-27 que no cuadra", lambda d: d["ruralDevelopment"]["totalEU27"].__setitem__(0, 1)),
 ("cap/eu/allocations.json", "importe negativo", lambda d: d["directPayments"]["countries"]["ES"].__setitem__(0, -5)),
 ("cap/dk/amounts.json", "importe negativo", lambda d: d["schemes"][0]["items"][0].__setitem__("amount", -3)),
 ("cap/dk/amounts.json", "decreto no vigente", lambda d: d["documents"][0].__setitem__("status", "Repealed")),
 ("cap/index.json", "componente ingerido sin fichero", lambda d: d["countries"][0]["components"]["rules"].__setitem__("file", "es/no-existe.json")),
 ("cap/index.json", "no ingerido sin razon", lambda d: d["countries"][3]["components"]["amounts"].pop("reason")),
 ("cap/index.json", "evento NEW_RULE emitido", lambda d: d["watch"]["events"].append({"type": "NEW_RULE", "cc": "ES", "detail": "x", "detectedAt": "2026-10-01", "officialUrl": "https://www.boe.es/"})),
 ("cap/index.json", "plazo anterior a asOf", lambda d: d["watch"]["deadlines"][0].__setitem__("date", "2000-01-01")),
 ("cap/index.json", "pais con datos sin acto legal", lambda d: d["countries"][1].__setitem__("legalAct", None)),
 ("blog/editions/2026-W40.json", "DRAFT con revisor", lambda d: d["editorial"].__setitem__("reviewedBy", "x")),
 ("blog/editions/2026-W40.json", "aprobada sin revisor", lambda d: d.__setitem__("status", "APPROVED")),
 ("blog/editions/2026-W40.json", "Substack publicado en borrador", lambda d: d["distribution"]["substack"].__setitem__("state", "PUBLISHED")),
 ("blog/editions/2026-W40.json", "canonica fuera de dehesaindex.com", lambda d: d.__setitem__("canonicalUrl", "https://dehesaindex.substack.com/p/x")),
 ("blog/editions/2026-W40.json", "fuente que no es un titular", lambda d: d["sources"][0].__setitem__("url", "https://example.com/x")),
 ("blog/editions/2026-W40.json", "newsletter mas larga que el articulo", lambda d: d["languages"]["es"].__setitem__("newsletterMarkdown", d["languages"]["es"]["markdown"] * 2)),
 ("cap/dk/watch.json", "cambio oculto en reviewNeeded", lambda d: d["current"]["sections"]["basic"].__setitem__("sha256", "0" * 64)),
 ("ers-cost-reference.json", "partidas que no suman el total publicado", lambda d: d["crops"]["maiz"]["costs"].__setitem__("fert", 999.0)),
 ("ers-cost-reference.json", "partida negativa", lambda d: d["crops"]["maiz"]["costs"].__setitem__("seed", -5.0)),
 ("ers-cost-reference.json", "costes imputados mayores que el total", lambda d: d["crops"]["soja"].__setitem__("imputed", 5000.0)),
 ("ers-cost-reference.json", "rendimiento inventado a cero", lambda d: d["crops"]["trigo"].__setitem__("yieldBuPerAcre", 0)),
 ("coverage-gaps.json", "celda AVAILABLE degradada sin cambiar series", lambda d: next(c for r in d["matrix"].values() for ms in r.values() for c in ms.values() if c["state"] == "AVAILABLE").__setitem__("state", "MISSING")),
 ("coverage-gaps.json", "series de una celda alteradas", lambda d: next(c for r in d["matrix"].values() for ms in r.values() for c in ms.values() if c["state"] == "AVAILABLE").__setitem__("series", 999)),
 ("coverage-gaps.json", "fuera del catalogo sin evidencia", lambda d: next(c for r in d["matrix"].values() for ms in r.values() for c in ms.values() if c["state"] == "MISSING").__setitem__("state", "AVAILABLE_OUTSIDE_CATALOG")),
 ("coverage-gaps.json", "candidata en revision presentada como lista para ingerir", lambda d: next(c for r in d["matrix"].values() for ms in r.values() for c in ms.values() if c["state"] == "LICENSE_PENDING").__setitem__("state", "SOURCE_AVAILABLE_NOT_INGESTED")),
 ("coverage-gaps.json", "resumen por estado sin cuadrar", lambda d: d["summary"]["byState"].__setitem__("MISSING", 1)),
 ("coverage-gaps.json", "hueco MISSING promovido a high sin evidencia", lambda d: next(c for r in d["matrix"].values() for ms in r.values() for c in ms.values() if c["state"] == "MISSING" and c["confidence"] != "high").__setitem__("confidence", "high")),
 ("coverage-gaps.json", "evidencia de confianza inventada", lambda d: next(c for r in d["matrix"].values() for ms in r.values() for c in ms.values() if c["state"] == "MISSING")["basis"].__setitem__("peers", 99)),
 ("coverage-gaps.json", "celda sin confidence", lambda d: next(c for r in d["matrix"].values() for ms in r.values() for c in ms.values()).pop("confidence")),
 ("coverage-gaps.json", "fuente atrasada inventada", lambda d: d["ranking"]["staleSources"].append({"sourceId": "inventada", "staleSeries": 1, "staleCells": 1, "countries": ["ES"]})),
 ("fx-history.json", "tipo implausible", lambda d: d["currencies"]["USD"].__setitem__(5, [d["currencies"]["USD"][5][0], 99.0])),
 ("fx-history.json", "meses desordenados", lambda d: d["currencies"]["USD"].reverse()),
 ("cpi.json", "valor anual no positivo", lambda d: d["countries"]["ES"]["a"]["v"].__setitem__(-1, -5)),
 ("cpi.json", "serie anual que acaba sin dato", lambda d: d["countries"]["DE"]["a"]["v"].append(None)),
 ("product-compare.json", "punto negativo", lambda d: d["products"]["trigo"]["series"][0]["points"].__setitem__(0, [d["products"]["trigo"]["series"][0]["points"][0][0], -1])),
 ("product-compare.json", "pais repetido", lambda d: d["products"]["trigo"]["series"].append(copy.deepcopy(d["products"]["trigo"]["series"][0]))),
 ("watch-index.json", "entrada mal formada", lambda d: d["series"].__setitem__("ES/x", ["a"])),
 ("pipeline-status.json", "resumen incoherente", lambda d: d["summary"].__setitem__("ok", 0)),
 ("pipeline-status.json", "workflow inexistente", lambda d: d["pipelines"][0].__setitem__("workflow", "no-existe.yml")),
 ("daily-brief.json", "recuento incoherente", lambda d: d["counts"].__setitem__("upcoming", 99)),
 ("instrument-identity.json", "instrumento sin identidad", lambda d: d["instruments"].pop("di_pienso_harina_soja_us")),
 ("instrument-identity.json", "etapa desconocida", lambda d: d["instruments"]["di_pienso_harina_soja_eu"].__setitem__("stage", "inventada")),
 ("instrument-identity.json", "soja UE y EE. UU. identicas", lambda d: d["instruments"]["di_pienso_harina_soja_us"].update({"grade": d["instruments"]["di_pienso_harina_soja_eu"]["grade"], "stage": d["instruments"]["di_pienso_harina_soja_eu"]["stage"], "form": "grain"}) or d["instruments"]["di_cereales_soja_grano_ca"].update({"grade": d["instruments"]["di_pienso_harina_soja_eu"]["grade"], "stage": d["instruments"]["di_pienso_harina_soja_eu"]["stage"], "form": "grain", "product": d["instruments"]["di_pienso_harina_soja_eu"]["product"]})),
 ("series-registry.json", "colision canonica no declarada", lambda d: d["series"][1].__setitem__("canonicalSeriesId", d["series"][0]["canonicalSeriesId"])),
 ("series-registry.json", "colision declarada solo en un sentido", lambda d: (d["series"][1].__setitem__("canonicalSeriesId", d["series"][0]["canonicalSeriesId"]), d["series"][1].__setitem__("file", "otro.json"), d["series"][0].__setitem__("alternates", [d["series"][1]["id"]]))),
 ("series-registry.json", "serie repetida", lambda d: d["series"].append(copy.deepcopy(d["series"][0]))),
 ("search-index.json", "URL externa", lambda d: d["entries"][0].__setitem__("u", "https://evil.example/")),
 ("drought.json", "D0..D4 creciente", lambda d: d["us"]["conus"][-1].__setitem__(5, 99.0)),
 ("drought.json", "porcentaje > 100", lambda d: d["us"]["conus"][-1].__setitem__(1, 140.0)),
 ("crop-progress.json", "condicion no suma 100", lambda d: d["crops"][0]["seasons"][next(iter(d["crops"][0]["seasons"]))]["condition"][0].__setitem__(1, 60)),
 ("cattle-on-feed.json", "balance de existencias roto", lambda d: d["reports"][0]["national"]["current"].__setitem__("placed", 9999)),
 ("cattle-on-feed.json", "total por estado distinto", lambda d: d["reports"][0]["states"][-1].__setitem__("current", 5)),
 ("cattle-on-feed.json", "suma de estados rota", lambda d: d["reports"][0]["states"][0].__setitem__("current", 9000)),
 ("cattle-on-feed.json", "publicado antes del inventario", lambda d: d["reports"][0].__setitem__("release", "2000-01-01")),
 ("eu-farm-economics.json", "produccion - consumo intermedio no es el valor anadido", lambda d: d["geos"]["ES"]["gva"].__setitem__(-1, 99999.0)),
 ("eu-farm-economics.json", "partidas superan el consumo intermedio", lambda d: d["geos"]["FR"]["feed"].__setitem__(-1, 9e9)),
 ("eu-farm-economics.json", "suma de los 27 distinta del agregado", lambda d: d["geos"]["EU27_2020"]["output"].__setitem__(-1, 1.0)),
 ("eu-farm-economics.json", "anos desordenados", lambda d: d["years"].reverse()),
 ("eu-farm-economics.json", "falta un indicador", lambda d: d["geos"]["DE"].pop("indA")),
 ("eu-regions-es.json", "regiones que no suman el total nacional", lambda d: d["regions"]["AN"]["eaa"]["AM200000"].__setitem__(-1, [d["regions"]["AN"]["eaa"]["AM200000"][-1][0], 99999.0])),
 ("eu-regions-fr.json", "falta una region", lambda d: d["regions"].pop("BRE")),
 ("eu-regions-nl.json", "falta una provincia", lambda d: d["regions"].pop("UT")),
 ("eu-regions-at.json", "falta un Land", lambda d: d["regions"].pop("W")),
 ("eu-regions-be.json", "falta una provincia", lambda d: d["regions"].pop("WLX")),
 ("eu-regions-dk.json", "falta una region", lambda d: d["regions"].pop("NJY")),
 ("eu-regions-de.json", "vacas mas que vacuno total", lambda d: d["regions"]["NI"]["animals"]["A2300F"].__setitem__(-1, [d["regions"]["NI"]["animals"]["A2300F"][-1][0], 99999.0])),
 ("eu-regions-it.json", "rendimiento no plausible", lambda d: d["regions"]["LOM"]["crops"]["C1500"]["prod"].__setitem__(-1, [d["regions"]["LOM"]["crops"]["C1500"]["prod"][-1][0], 9999999.0])),
 ("eu-regions-es.json", "anios desordenados", lambda d: d["regions"]["CL"]["eaa"]["AM160000"].reverse()),
 ("eu-regions-fr.json", "explotaciones por tipo distintas del total", lambda d: d["regions"]["OCC"]["farms"]["TOTAL"]["2023"].__setitem__("HLD", 1.0)),
 ("au-states.json", "estados que no suman el total nacional", lambda d: d["states"]["NSW"]["agrifood"].__setitem__(-1, [d["states"]["NSW"]["agrifood"][-1][0], 99999.0])),
 ("au-states.json", "falta un estado", lambda d: d["states"].pop("QLD")),
 ("au-states.json", "valor negativo", lambda d: d["states"]["VIC"]["beef"].__setitem__(-1, [d["states"]["VIC"]["beef"][-1][0], -5.0])),
 ("crop-insurance.json", "estados que no suman el total nacional", lambda d: d["states"]["IA"]["2024"].__setitem__(0, d["states"]["IA"]["2024"][0] + 10**9)),
 ("crop-insurance.json", "cultivos que no suman el total nacional", lambda d: d["crops"]["Corn"]["2024"].__setitem__(3, d["crops"]["Corn"]["2024"][3] + 10**9)),
 ("crop-insurance.json", "subvencion mayor que la prima", lambda d: d["national"]["2024"].__setitem__(2, d["national"]["2024"][1] + 1)),
 ("crop-insurance.json", "capital asegurado a cero", lambda d: d["national"]["2024"].__setitem__(0, 0)),
 ("crop-insurance.json", "falta un año", lambda d: d["national"].pop("2020")),
 ("crop-insurance.json", "causa que no suma con sus estados", lambda d: d["causeIndemnity"]["Drought"].__setitem__("2024", d["causeIndemnity"]["Drought"]["2024"] + 10**9)),
 ("crop-insurance.json", "causa por estado inexistente", lambda d: d["causeStateIndemnity"].__setitem__("Nope", d["causeStateIndemnity"]["Drought"])),
 ("crop-insurance.json", "indemnizacion negativa enorme", lambda d: d["causeIndemnity"]["Drought"].__setitem__("2024", -10**9)),
 ("crop-insurance.json", "comprobacion SOB distinta de la nacional", lambda d: d["causeCheck"]["2024"].__setitem__(1, d["causeCheck"]["2024"][1] + 5)),
 ("crop-insurance.json", "estado con nombre invalido", lambda d: d["states"].__setitem__("Iowa", d["states"].pop("IA"))),
 ("crop-insurance-ca.json", "provincias que no suman Canada", lambda d: d["data"]["SK"]["indemnities"].__setitem__(-1, d["data"]["SK"]["indemnities"][-1] + 10**6)),
 ("crop-insurance-ca.json", "gasto en primas de Canada con hueco", lambda d: d["data"]["CA"]["farmPremiums"].__setitem__(-1, None)),
 ("crop-insurance-ca.json", "serie mas corta que los años", lambda d: d["data"]["AB"]["indemnities"].pop()),
 ("crop-insurance-ca.json", "valor negativo", lambda d: d["data"]["MB"]["farmPremiums"].__setitem__(-1, -5)),
 ("crop-insurance-ca.json", "valor decimal", lambda d: d["data"]["ON"]["indemnities"].__setitem__(-1, 1.5)),
 ("crop-insurance-ca.json", "territorio de mas", lambda d: d["data"].__setitem__("YT", d["data"]["BC"])),
 ("crop-insurance-ca.json", "latestYear distinto del ultimo año", lambda d: d.__setitem__("latestYear", d["latestYear"] - 1)),
 ("crop-insurance-ca.json", "año repetido", lambda d: d["years"].__setitem__(-1, d["years"][-2])),
 ("crop-insurance-ca.json", "unidad distinta", lambda d: d.__setitem__("unit", "CAD million")),
 ("insurance-es.json", "verificacion invalida", lambda d: d.__setitem__("verification", "OK")),
 ("insurance-es.json", "subvencion mayor que 100 %", lambda d: d["stats"].__setitem__("publicSubsidyPctOfPremium", 150)),
 ("canada-provinces.json", "produccion negativa", lambda d: d["provinces"]["SK"]["crops"]["wheat-all"]["prod"].__setitem__(-1, [d["provinces"]["SK"]["crops"]["wheat-all"]["prod"][-1][0], -5.0])),
 ("canada-provinces.json", "superficie cosechada mayor que sembrada", lambda d: d["provinces"]["AB"]["crops"]["barley"]["harea"].__setitem__(-1, [d["provinces"]["AB"]["crops"]["barley"]["harea"][-1][0], 99999.0])),
 ("canada-provinces.json", "provincias que no suman Canada", lambda d: d["provinces"]["SK"]["crops"]["canola-rapeseed"]["prod"].__setitem__(-1, [d["provinces"]["SK"]["crops"]["canola-rapeseed"]["prod"][-1][0], 1.0])),
 ("canada-provinces.json", "periodos desordenados", lambda d: d["provinces"]["ON"]["income"]["net-income-total"]["pts"].reverse()),
 ("canada-provinces.json", "falta una provincia clave", lambda d: d["provinces"].pop("QC")),
 ("canada-provinces.json", "mas vacas que vacuno total", lambda d: d["provinces"]["MB"]["cattle"]["beef-cows"]["pts"].__setitem__(-1, [d["provinces"]["MB"]["cattle"]["beef-cows"]["pts"][-1][0], 99999.0])),
 ("canada-drought.json", "porcentaje superior a 100", lambda d: d["provinces"]["SK"]["v"][-1].__setitem__(0, 140.0)),
 ("canada-drought.json", "clases no acumulativas", lambda d: d["provinces"]["AB"]["v"][-1].__setitem__(4, 100.0) or d["provinces"]["AB"]["v"][-1].__setitem__(3, 1.0)),
 ("canada-drought.json", "periodo que no es fin de mes", lambda d: d["periods"].__setitem__(-1, "2026-08-30")),
 ("canada-drought.json", "falta una provincia clave", lambda d: d["provinces"].pop("SK")),
 ("canada-drought.json", "filas distintas de meses", lambda d: d["provinces"]["MB"]["v"].pop()),
 ("eu-drought.json", "porcentaje superior a 100", lambda d: d["countries"]["ES"]["v"][-1].__setitem__(0, 140.0)),
 ("eu-drought.json", "clases que suman mas de 100", lambda d: d["countries"]["FR"]["v"][-1].__setitem__(1, 99.0)),
 ("eu-drought.json", "decada que no empieza en 1, 11 o 21", lambda d: d["periods"].__setitem__(-1, "2026-09-12")),
 ("eu-drought.json", "falta un pais clave", lambda d: d["countries"].pop("DE")),
 ("eu-drought.json", "filas distintas de decadas", lambda d: d["countries"]["IT"]["v"].pop()),
 ("us-dairy.json", "precio fuera de rango", lambda d: d["products"][0]["series"][-1].__setitem__(1, 99.0)),
 ("us-dairy.json", "semana que no acaba en sabado", lambda d: d["products"][0]["series"][-1].__setitem__(0, "2026-09-25")),
 ("us-dairy.json", "semanas desordenadas", lambda d: d["products"][1]["series"].reverse()),
 ("us-dairy.json", "falta un producto", lambda d: d["products"].pop()),
 ("eu-vat.json", "tipo general fuera de rango", lambda d: d["countries"]["ES"].__setitem__("standard", 90.0)),
 ("eu-vat.json", "falta un pais", lambda d: d["countries"].pop("FR")),
 ("eu-vat.json", "tipo reducido mayor que el general", lambda d: d["countries"]["DE"]["reduced"][0].__setitem__("rate", 30.0)),
 ("eu-vat.json", "tipo de cultivo mayor que el general", lambda d: d["countries"]["ES"]["crops"].__setitem__("soja", 30.0)),
 ("other-tax.json", "tipo estatal absurdo", lambda d: d["us"]["states"]["TX"].__setitem__("rate", 60.0)),
 ("other-tax.json", "falta un estado", lambda d: d["us"]["states"].pop("OH")),
 ("other-tax.json", "estado sin impuesto con tipo", lambda d: d["us"]["states"]["OR"].__setitem__("rate", 5.0)),
 ("other-tax.json", "reducido del Reino Unido mayor que el general", lambda d: d["gb"].__setitem__("reduced", 25.0)),
 ("canada-grain.json", "semanas desordenadas", lambda d: d["weeks"].reverse()),
 ("canada-grain.json", "exportacion negativa", lambda d: d["grains"][0]["exports"].__setitem__(-1, -5.0)),
 ("canada-grain.json", "columna de otra longitud", lambda d: d["grains"][1]["stocks"].pop()),
 ("canada-grain.json", "acumulado que cae", lambda d: d["grains"][0]["cumExports"].__setitem__(-1, 1.0)),
 ("canada-grain.json", "semana que no acaba en domingo", lambda d: d["weeks"].__setitem__(-1, "2026-09-25")),
 ("us-lamb.json", "precio fuera de rango", lambda d: d["rows"][-1].__setitem__(1, 5000.0)),
 ("us-lamb.json", "neto mayor que bruto", lambda d: d["rows"][-1].__setitem__(2, d["rows"][-1][1] + 10)),
 ("us-lamb.json", "dias desordenados", lambda d: d["rows"].reverse()),
 ("us-lamb.json", "delantero y trasero incoherentes", lambda d: d["rows"][-1].__setitem__(3, 1400.0)),
 ("us-fertilizers.json", "precio fuera de rango", lambda d: d["products"][0]["states"][0].__setitem__("avg", 90000)),
 ("us-fertilizers.json", "promedio fuera de min-max", lambda d: d["products"][0]["states"][0].update({"min": 1, "max": 2})),
 ("us-fertilizers.json", "historico no termina en el ultimo", lambda d: d["products"][0]["states"][0]["hist"].pop()),
 ("us-fertilizers.json", "fila repetida", lambda d: d["products"][0]["states"].append(copy.deepcopy(d["products"][0]["states"][0]))),
 ("usda-calendar.json", "publicacion en fin de semana", lambda d: d["releases"][0].__setitem__("date", "2026-10-03")),
 ("usda-calendar.json", "publicacion repetida", lambda d: d["releases"].insert(1, copy.deepcopy(d["releases"][0]))),
 ("usda-calendar.json", "agencia desconocida", lambda d: d["releases"][0].__setitem__("agency", "XYZ")),
 ("climate.json", "temperatura imposible", lambda d: d["locations"][0]["months"][0].__setitem__("tempC", 90)),
 ("recan.json", "indice fuera de rango", lambda d: d["rows"][0].__setitem__(1, 99)),
 ("revisions.json", "revision sin fecha", lambda d: d["revisions"].append({"file": "a", "series": "x", "period": "2020", "old": 1, "new": 2})),
 ("catalog/manifest.json", "total incoherente", lambda d: d.__setitem__("seriesTotal", d["seriesTotal"] + 5)),
 ("catalog/series-index.json", "fila sin serie en catalogo (total)", lambda d: d["rows"].pop()),
 ("catalog/series-index.json", "indice fuera del diccionario", lambda d: d["rows"][0].__setitem__(2, 9999)),
 ("catalog/series-index.json", "serie repetida", lambda d: d["rows"].__setitem__(1, list(d["rows"][0]))),
 ("catalog/series-index.json", "estado invalido", lambda d: d["dict"]["fs"].__setitem__(0, "MAYBE")),
 ("export-sales.json", "semana desordenada", lambda d: d["commodities"][0]["weekly"].reverse()),
 ("gats.json", "mes futuro", lambda d: d["months"].append("209901")),
 ("freshness.json", "recuento incoherente", lambda d: d["catalog"]["byState"].__setitem__("LIVE", d["catalog"]["byState"]["LIVE"] + 1)),
 ("freshness.json", "estado inventado", lambda d: d["latest"]["observations"][0].__setitem__("state", "MAYBE")),
 ("product-metadata.json", "serie UE inexistente", lambda d: d["products"]["trigo"]["compare"].__setitem__("eu", ["cereales", "no-existe"])),
 ("product-metadata.json", "sin nombre en un idioma", lambda d: d["products"]["trigo"]["name"].pop("it")),
 ("product-metadata.json", "instrumento inexistente", lambda d: d["products"]["trigo"]["instruments"].append({"region": "us", "product": "no-existe"})),
 ("product-metadata.json", "relacion inventada", lambda d: d["products"]["trigo"]["related"].append({"product": "no-existe", "relation": "input", "why": "energy"})),
 ("products/trigo.json", "cuota que no es valor/mundo", lambda d: d["trade"]["exports"]["top"][0].__setitem__("share", 55.5)),
 ("products/trigo.json", "producto desconocido", lambda d: d.__setitem__("product", "no-existe")),
 ("products/trigo.json", "stock-to-use inventado", lambda d: d["supplyDemand"]["entities"]["US"][str(d["supplyDemand"]["marketYear"])].__setitem__("stockToUse", 5.0)),
 ("products/trigo.json", "campana fuera de ventana", lambda d: d["supplyDemand"]["entities"]["EU"].__setitem__("2010", {"production": 1})),
 ("products/trigo.json", "top desordenado", lambda d: d["trade"]["exports"]["top"].reverse()),
 ("freshness-policy.json", "rezago sin evidencia", lambda d: d["sources"]["statcan"].__setitem__("evidence", "x")),
 ("freshness-policy.json", "rezago absurdo", lambda d: d["sources"]["statcan"]["lagDays"].__setitem__("monthly", 9999)),
 ("quality.json", "freshness incoherente", lambda d: d["observations"][0].__setitem__("freshness", "STALE")),
 ("data-anomalies.json", "KNOWN sin evidencia", lambda d: (d["anomalies"][0].__setitem__("status", "KNOWN_VERIFIED_ANOMALY"), d["anomalies"][0].pop("evidence", None))),
 ("data-anomalies.json", "serie inexistente", lambda d: d["anomalies"][0].__setitem__("series", "AT/no-existe")),
 ("daily-brief.json", "byKind incoherente", lambda d: d["byKind"]["PRICE"].__setitem__("datasets", 99)),
 ("daily-brief.json", "pipeline sin clasificar", lambda d: d["pipelinesCovered"].__setitem__("total", d["pipelinesCovered"]["total"] + 1)),
 ("product-compare.json", "sin aggregation", lambda d: d["products"]["trigo"]["series"][0].pop("aggregation")),
 ("product-compare.json", "estado de frescura inventado", lambda d: d["products"]["trigo"]["series"][0].__setitem__("fs", "OK")),
 ("views/home-summary.json", "mover con historico", lambda d: d["movers"][0].__setitem__("history", [1, 2])),
 ("views/home-summary.json", "markets.total incoherente", lambda d: d["markets"].__setitem__("total", d["markets"]["total"] + 1)),
 ("views/news-index.json", "clave fuera de rango", lambda d: d["keys"].__setitem__("trigo", [10 ** 6])),
 ("views/news-index.json", "enlace no http", lambda d: d["stories"][0].__setitem__("url", "javascript:alert(1)")),
 ("views/news-feed.json", "noticia repetida", lambda d: d["items"].append(copy.deepcopy(d["items"][0]))),
 ("views/news-feed.json", "fecha invalida", lambda d: d["items"][0].__setitem__("d", "ayer")),
 ("prices/manifest.json", "total incoherente", lambda d: d["totals"].__setitem__("observations", 1)),
 ("prices/manifest.json", "producto sin historico", lambda d: next(iter(d["regions"].values()))["products"].append("no-existe")),
 ("prices/latest/us.json", "historico dentro de latest", lambda d: first(d).__setitem__("history", [1])),
 ("prices/latest/us.json", "region cruzada", lambda d: first(d).__setitem__("region", "eu")),
 ("prices/latest/us.json", "spark no numerico", lambda d: first(d).__setitem__("spark", ["x"])),
 ("prices/history/us/trigo.json", "historico desordenado", lambda d: d["history"].reverse()),
 ("prices/history/us/trigo.json", "valor no numerico", lambda d: d["history"][3].__setitem__("value", "n/a")),
 ("prices/intelligence/uk.json", "puntos desordenados", lambda d: next(iter(d["series"].values()))["points"].reverse()),
 ("prices/intelligence/uk.json", "serie no comparable", lambda d: next(iter(d["series"].values())).__setitem__("comparability", "not_comparable")),
 ("daily-brief.json", "cashBids: rango incoherente", lambda d: d["cashBids"]["groups"][0].__setitem__("min", d["cashBids"]["groups"][0]["max"] + 1)),
 ("daily-brief.json", "cashBids: mercados de mas", lambda d: d["cashBids"].__setitem__("marketsUpdated", 0)),
 ("us-cash-bids/IA/corn.json", "precio negativo", lambda d: d["series"][0]["pts"][-1].__setitem__(1, -4.1)),
 ("us-cash-bids/IA/corn.json", "minimo > maximo", lambda d: d["series"][0]["pts"][-1].__setitem__(2, 99.0)),
 ("us-cash-bids/IA/corn.json", "ultima obs distinta del ultimo punto", lambda d: d["series"][0].__setitem__("avg", d["series"][0]["avg"] + 0.5)),
 ("us-cash-bids/IA/corn.json", "id de otro informe", lambda d: d["series"][0].__setitem__("id", "us-cb:1:" + d["series"][0]["id"].split(":")[2])),
 ("us-cash-bids/IA/corn.json", "serie en shard equivocado", lambda d: d["series"][0].__setitem__("commodity", "wheat")),
 ("us-cash-bids/IA/corn.json", "cambio alterado", lambda d: d["series"][0].__setitem__("changePct", 25.0)),
 ("us-cash-bids/IA/corn.json", "priceKind inventado", lambda d: d["series"][0].__setitem__("priceKind", "EXACT")),
 ("us-cash-bids/IA/corn.json", "locationType inventado", lambda d: d["series"][0].__setitem__("locationType", "LOCAL_ELEVATOR")),
 ("us-cash-bids/IA/corn.json", "ELEVATOR sin instalacion", lambda d: d["series"][0].update({"locationType": "ELEVATOR", "locationName": None})),
 ("us-cash-bids/IA/corn.json", "puntos desordenados", lambda d: d["series"][0]["pts"].reverse()),
 ("us-cash-bids/IA/corn.json", "credencial en el fichero", lambda d: d.__setitem__("note", "Authorization: Basic QUJDREVGR0hJSktMTU5PUA==")),
 ("us-cash-bids/IA/corn.json", "frescura inventada", lambda d: d["series"][0].__setitem__("freshness", "SUPER_FRESH")),
 ("us-cash-bids/history/IA/corn.json", "historico desordenado", lambda d: next(iter(d["series"].values()))["pts"].reverse()),
 ("us-cash-bids/history/IA/corn.json", "historico con precio cero", lambda d: next(iter(d["series"].values()))["pts"][0].__setitem__(1, 0)),
 ("us-cash-bids/manifest.json", "totales alterados", lambda d: d["totals"].__setitem__("series", d["totals"]["series"] + 1)),
 ("us-cash-bids/manifest.json", "licencia distinta del registro", lambda d: d["license"].__setitem__("status", "PENDING")),
 ("us-cash-bids/manifest.json", "shard inexistente", lambda d: d["states"]["IA"]["commodities"]["corn"].__setitem__("shard", "IA/nada.json")),
 ("us-cash-bids/zip-state.json", "estado inventado", lambda d: d["prefix"].__setitem__("500", "ZZ")),
 ("us-cash-bids/zip-state.json", "ZIP de Iowa en otro estado", lambda d: d["prefix"].__setitem__("500", "KS")),
 ("us-cash-bids/zip-state.json", "tabla recortada", lambda d: [d["prefix"].pop(k) for k in list(d["prefix"])[:200]]),
 ("us-cash-bids/reports.json", "informe repetido", lambda d: d["reports"].append(copy.deepcopy(d["reports"][0]))),
 ("us-cash-bids/reports.json", "active distinto del registro", lambda d: d["reports"][0].__setitem__("active", not d["reports"][0]["active"])),
 ("us-cash-bids/reports.json", "estado de ingesta inventado", lambda d: d["reports"][0].__setitem__("ingestionStatus", "PERFECT")),

 ("cap/es/amounts.json", "ayuda basica: planificado mayor que maximo", lambda d: d["regions"]["5"]["abrs"]["planned"].__setitem__(2, d["regions"]["5"]["abrs"]["max"][2] + 1)),
 ("cap/es/amounts.json", "ayuda basica: minimo mayor que planificado", lambda d: d["regions"]["3"]["abrs"]["min"].__setitem__(0, d["regions"]["3"]["abrs"]["planned"][0] + 1)),
 ("cap/es/amounts.json", "total del Anexo VII que no cuadra", lambda d: d["allocations"]["abrs"].__setitem__(1, d["allocations"]["abrs"][1] + 5000)),
 ("cap/es/amounts.json", "asignacion de una region alterada", lambda d: d["regions"]["9"]["allocation"]["young"].__setitem__(3, d["regions"]["9"]["allocation"]["young"][3] * 2)),
 ("cap/es/amounts.json", "region que falta", lambda d: d["regions"].pop("7")),
 ("cap/es/amounts.json", "mujeres jovenes que no empareja", lambda d: d["regions"]["2"]["youngWomen"]["planned"].__setitem__(0, d["regions"]["2"]["youngWomen"]["planned"][0] + 3)),
 ("cap/es/amounts.json", "tramos de hectareas solapados", lambda d: d["regions"]["4"]["redistributiveTiers"][1].__setitem__("fromHa", 1)),
 ("cap/es/amounts.json", "Anexo VIII muy distinto del IX", lambda d: d["regions"]["6"]["redistributiveTiers"][0].__setitem__("annexVIIIAmount", 99)),
 ("cap/es/amounts.json", "discrepancias VIII/IX inventadas", lambda d: d["discrepancies"].append({"region": 1, "tier": 1, "annexVIII": 1, "annexIX2026Planned": 2})),
 ("cap/es/amounts.json", "ecorregimen con planificado bajo el minimo", lambda d: d["ecoschemes"][3]["planned"].__setitem__(3, d["ecoschemes"][3]["min"][3] - 1)),
 ("cap/es/amounts.json", "ecorregimen con maximo bajo el planificado", lambda d: d["ecoschemes"][10]["max"].__setitem__(0, 1)),
 ("cap/es/amounts.json", "ecorregimen repetido", lambda d: d["ecoschemes"].append(copy.deepcopy(d["ecoschemes"][0]))),
 ("cap/es/amounts.json", "importe negativo", lambda d: d["ecoschemes"][5]["min"].__setitem__(0, -3)),
 ("cap/es/amounts.json", "importe con texto", lambda d: d["ecoschemes"][5]["planned"].__setitem__(1, "n/d")),
 ("cap/es/amounts.json", "superficie sin umbral de degresividad", lambda d: d["degressivity"][2].__setitem__("surfaceType", "otra")),
 ("cap/es/amounts.json", "dotacion de un ecorregimen a cero", lambda d: d["ecoschemeBudget"][4]["amount"].__setitem__(2, 0)),
 ("cap/es/amounts.json", "ayuda asociada: minimo mayor que maximo", lambda d: d["associatedAid"][0]["min"].__setitem__(1, d["associatedAid"][0]["max"][1] + 1)),
 ("cap/es/amounts.json", "ayuda asociada: unidad incoherente", lambda d: d["associatedAid"][0].__setitem__("unit", "EUR/animal")),
 ("cap/es/amounts.json", "fuente que no es el BOE", lambda d: d["source"].__setitem__("id", "fega_es")),
 ("cap/es/amounts.json", "campañas distintas", lambda d: d.__setitem__("campaigns", [2024, 2025, 2026, 2027, 2028])),
 ("cap/es/amounts.json", "verificado en el futuro", lambda d: d.__setitem__("verifiedAt", "2099-01-01")),
 ("cap/es/amounts.json", "registro de cambios desordenado", lambda d: d["changes"].extend([{"detectedAt": "2026-10-05", "summary": "cambio de prueba"}, {"detectedAt": "2026-10-01", "summary": "cambio de prueba"}])),
 ("cap/es/amounts.json", "tipo de importe inventado", lambda d: d.__setitem__("kind", "FEGA_FINAL")),
 ("cap/es/watch.json", "cambio del BOE ocultado", lambda d: d["current"]["articles"]["13"].__setitem__("sha256", "0" * 64)),
 ("cap/es/watch.json", "revision pedida sin cambio", lambda d: d["reviewNeeded"].append("Articulo 99")),
 ("cap/es/watch.json", "norma modificadora nueva ocultada", lambda d: d["current"]["legal"]["amendments"].append({"id": "BOE-A-2099-1", "relation": "SE MODIFICA", "text": "prueba"})),
 ("cap/es/watch.json", "comprobacion en el futuro", lambda d: d.__setitem__("checkedAt", "2099-01-01")),
 ("cap/es/watch.json", "huella invalida", lambda d: d["baseline"]["annexes"]["X"].__setitem__("sha256", "abc")),
 ("cap/es/rules.json", "tramos de reduccion no contiguos", lambda d: next(r for r in d["rules"] if r["id"] == "abrs-reduction")["values"]["tiers"][1].__setitem__("fromEur", 76000)),
 ("cap/es/rules.json", "ultimo tramo sin el 100 %", lambda d: next(r for r in d["rules"] if r["id"] == "abrs-reduction")["values"]["tiers"][-1].__setitem__("reduction", 0.9)),
 ("cap/es/rules.json", "excepcion de un hito que no existe", lambda d: d["campaignOverrides"][0].__setitem__("calendarId", "no-existe")),
 ("cap/es/rules.json", "fecha de excepcion fuera de campaña", lambda d: d["campaignOverrides"][0].__setitem__("date", "2031-06-15")),
 ("cap/es/rules.json", "fecha del calendario imposible", lambda d: d["calendar"][0]["when"].update({"month": 2, "day": 31})),
 ("cap/es/rules.json", "hito que termina antes de empezar", lambda d: next(x for x in d["calendar"] if x["id"] == "advance")["until"].update({"month": 9, "day": 1})),
 ("cap/es/rules.json", "regla repetida", lambda d: d["rules"].append(copy.deepcopy(d["rules"][0]))),
 ("cap/es/rules.json", "ecorregimen repetido en las reglas", lambda d: d["ecoschemes"][1].__setitem__("code", "a")),
 ("cap/es/rules.json", "umbral minimo incoherente", lambda d: next(r for r in d["rules"] if r["id"] == "min-payment")["values"].__setitem__("maxRaisedEur", 100)),
 ("cap/es/rules.json", "jovenes con 0 hectareas", lambda d: next(r for r in d["rules"] if r["id"] == "young-farmers")["values"].__setitem__("maxHa", 0)),
 ("cap/es/rules.json", "fuente que no es el BOE", lambda d: d["source"].__setitem__("id", "mapa_es")),
 ("cap/es/rules.json", "regla sin base legal", lambda d: d["rules"][2].__setitem__("legalBasis", "")),
]
bad = 0
for rel, name, fn in CASES:
    try: r = run(rel, fn)
    except Exception as e: print("ROTO   %-24s %-26s %r" % (rel, name, e)); bad += 1; continue
    ok = r["status"] == "error"
    if not ok: bad += 1
    print("%-6s %-24s %-26s %s" % ("OK" if ok else "FALLA", rel, name, "" if ok else "el validador NO lo detecto"))
# datos reales intactos
for rel in ("latest.json", "fx-history.json", "product-compare.json", "cap/es/amounts.json", "cap/es/watch.json", "cap/es/rules.json"):
    r = run(rel, lambda d: None)
    if r["status"] == "error": print("FALLA datos reales %s: %s" % (rel, r["errors"][:2])); bad += 1
print("%d casos, %d fallos" % (len(CASES), bad)); sys.exit(1 if bad else 0)
