#!/usr/bin/env python3
"""Pruebas negativas de los contratos: parte de datos REALES, los corrompe de una forma concreta y exige que validate-data los rechace.
Garantiza que los esquemas y tests semanticos 'muerden' (un validador que siempre dice OK es peor que ninguno). Uso: python3 scripts/test-contracts.py"""
import copy, fnmatch, importlib.util, json, sys, tempfile
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]; D = ROOT / "data"
spec = importlib.util.spec_from_file_location("vd", ROOT / "scripts" / "validate-data.py")
src = (ROOT / "scripts" / "validate-data.py").read_text().rsplit("\nmain()", 1)[0]
vd = type(sys)("vd"); vd.__file__ = str(ROOT / "scripts" / "validate-data.py"); exec(compile(src, "validate-data.py", "exec"), vd.__dict__)
def run(rel, mutate):
    doc = json.loads((D / rel).read_text()); mutate(doc)
    sch, tests = vd.REG["files"].get(rel) or next(v for pat, v in vd.REG["globs"].items() if fnmatch.fnmatchcase(rel, pat))
    with tempfile.TemporaryDirectory() as t:
        p = Path(t) / "x.json"; p.write_text(json.dumps(doc))
        return vd.validate_contract(p, rel, sch, tests)
def first(doc, key="observations"): return doc[key][0]
CASES = [
 ("latest.json", "valor no numerico", lambda d: first(d).__setitem__("value", "n/a")),
 ("latest.json", "region desconocida", lambda d: first(d).__setitem__("region", "mars")),
 ("latest.json", "id repetido", lambda d: d["observations"].append(copy.deepcopy(d["observations"][0]))),
 ("latest.json", "fecha futura", lambda d: first(d).__setitem__("observationDate", "2099-01-01")),
 ("latest.json", "indice con moneda", lambda d: [o.__setitem__("currency", "EUR") for o in d["observations"] if o["currency"] == "INDEX"][:1]),
 ("history.json", "id sin fecha", lambda d: first(d).__setitem__("id", "di_x")),
 ("quality.json", "stale incoherente", lambda d: d["observations"][0].__setitem__("stale", not d["observations"][0]["stale"])),
 ("quality.json", "scope incoherente", lambda d: d["scope"].__setitem__("stale", 999)),
 ("cross-market.json", "correlacion > 1", lambda d: d["relationships"][0].__setitem__("correlationReturns", 1.7)),
 ("relationships.json", "r fuera de [-1,1]", lambda d: d["relationships"][0]["stat"].__setitem__("correlation", 1.4)),
 ("relationships.json", "status inventado", lambda d: next(r for r in d["relationships"] if r["status"] == "WEAK_OR_UNSTABLE").__setitem__("status", "OBSERVED_RELATIONSHIP")),
 ("relationships.json", "confianza inflada", lambda d: next(r for r in d["relationships"] if r["confidence"] == "LOW").__setitem__("confidence", "HIGH")),
 ("relationships.json", "rezago no probado", lambda d: d["relationships"][0]["stat"].__setitem__("lag", 77)),
 ("relationships.json", "n alterado (recalculo)", lambda d: d["relationships"][0]["stat"].__setitem__("n", d["relationships"][0]["stat"]["n"] + 5)),
 ("relationships.json", "explicacion sin descargo", lambda d: d["relationships"][0]["explanation"].__setitem__("es", "Este insumo hace subir el precio.")),
 ("relationships.json", "id repetido", lambda d: d["relationships"].append(copy.deepcopy(d["relationships"][0]))),
 ("observatory.json", "movimiento alterado", lambda d: next(o for o in d["observations"] if o["moves"]["d30"])["moves"]["d30"].__setitem__("pct", 99.9)),
 ("observatory.json", "ventana incumplida", lambda d: next(o for o in d["observations"] if o["moves"]["d7"])["moves"]["d7"].__setitem__("days", 40)),
 ("observatory.json", "isNew incoherente", lambda d: d["observations"][0].__setitem__("isNew", not d["observations"][0]["isNew"])),
 ("observatory.json", "claves repetidas", lambda d: d["observations"].append(copy.deepcopy(d["observations"][0]))),
 ("observatory.json", "pipelines sin cuadrar", lambda d: d["pipelines"]["summary"].__setitem__("ok", d["pipelines"]["summary"]["ok"] + 1)),
 ("observatory.json", "frescura sin cuadrar", lambda d: d["freshness"]["catalog"]["byState"].__setitem__("LIVE", 1)),
 ("observatory.json", "cambio de cobertura inventado", lambda d: d["coverage"]["changes"].append({"scope": "country", "key": "XX", "from": 1, "to": 2})),
 ("source-candidates.json", "sourceId repetido", lambda d: d["candidates"].append(copy.deepcopy(d["candidates"][0]))),
 ("source-candidates.json", "licencia inventada sin registro", lambda d: next(c for c in d["candidates"] if c["sourceId"] == "ibge_sidra").__setitem__("commercialReuse", "yes")),
 ("source-candidates.json", "READY sin registro", lambda d: next(c for c in d["candidates"] if c["sourceId"] == "ibge_sidra").__setitem__("ingestionStatus", "READY")),
 ("source-candidates.json", "fuente RESTRICTED marcada ACTIVE", lambda d: next(c for c in d["candidates"] if c["sourceId"] == "conab").__setitem__("ingestionStatus", "ACTIVE")),
 ("source-candidates.json", "ingesta sin gate READY", lambda d: next(c for c in d["candidates"] if c["sourceId"] == "sima_gpp").__setitem__("ingestionStatus", "INGESTING")),
 ("source-candidates.json", "gate alterado", lambda d: next(c for c in d["candidates"] if c["sourceId"] == "abares")["gate"].__setitem__("result", "READY")),
 ("source-candidates.json", "canStart con bloqueo tecnico", lambda d: next(c for c in d["candidates"] if c["sourceId"] == "de_genesis_api").__setitem__("canStart", True)),
 ("source-candidates.json", "licenseStatus alterado", lambda d: next(c for c in d["candidates"] if c["sourceId"] == "mla").__setitem__("licenseStatus", "VERIFIED")),
 ("source-candidates.json", "fuente integrada desaparecida", lambda d: d["candidates"].remove(next(c for c in d["candidates"] if c["ingestionStatus"] == "ACTIVE"))),
 ("source-candidates.json", "resumen sin cuadrar", lambda d: d["summary"]["byStatus"].__setitem__("READY", 9)),
 ("premium-tracker.json", "diferencial que no cuadra con las medianas", lambda d: next(c for c in d["cells"] if c["premium"] is not None).__setitem__("premium", 99.0)),
 ("premium-tracker.json", "porcentaje inventado", lambda d: next(c for c in d["cells"] if c["premium"] is not None).__setitem__("premiumPct", 500.0)),
 ("premium-tracker.json", "muestra convencional insuficiente", lambda d: next(c for c in d["cells"] if c["premium"] is not None)["conventional"].__setitem__("n", 2)),
 ("premium-tracker.json", "premium sin parte convencional", lambda d: next(c for c in d["cells"] if c["premium"] is not None).__setitem__("conventional", None)),
 ("premium-tracker.json", "celda vacia sin motivo", lambda d: next(c for c in d["cells"] if c["premium"] is None).__setitem__("reason", None)),
 ("home-tape.json", "valor distinto del original", lambda d: d["rows"][0].__setitem__("value", d["rows"][0]["value"] + 1)),
 ("home-tape.json", "fila duplicada", lambda d: d["rows"].append(dict(d["rows"][0]))),
 ("home-tape.json", "moneda cambiada", lambda d: d["rows"][0].__setitem__("currency", "XXX")),
 ("home-explore.json", "porcentaje de sequia cambiado", lambda d: next(f for f in d["facts"] if f["id"] == "drought").__setitem__("pctD1", 1.0)),
 ("home-explore.json", "hecho duplicado", lambda d: d["facts"].append(dict(d["facts"][0]))),
 ("home-explore.json", "inventario cambiado", lambda d: next(f for f in d["facts"] if f["id"] == "cattle").__setitem__("onFeedKhead", 1)),
 ("home-explore.json", "origen inexistente", lambda d: d["facts"][0].__setitem__("file", "no-existe.json")),
 ("worldbank-agri.json", "licencia distinta de CC BY", lambda d: next(iter(d["indicators"].values())).__setitem__("license", "CC BY-NC-4.0")),
 ("worldbank-agri.json", "porcentaje superior a 100", lambda d: d["countries"]["ES"]["agriLandPct"]["v"].__setitem__(-1, 140.0)),
 ("worldbank-agri.json", "produccion que no cuadra con rendimiento x superficie", lambda d: d["countries"]["FR"]["cerealProd"]["v"].__setitem__(-1, d["countries"]["FR"]["cerealProd"]["v"][-1] * 2)),
 ("worldbank-agri.json", "tipo de cambio de zona euro anterior a 1999", lambda d: d["countries"]["ES"]["fxUsd"].__setitem__("y0", 1990)),
 ("worldbank-agri.json", "serie que acaba sin dato", lambda d: d["countries"]["DE"]["cpi"]["v"].append(None)),
 ("germany-agri.json", "alquiler absurdo", lambda d: d["rent"]["nat"]["lf"].__setitem__(-1, [2023, 99999.0])),
 ("germany-agri.json", "Land inexistente", lambda d: d["landPrice"]["land"].__setitem__("XX", d["landPrice"]["land"]["BY"])),
 ("germany-agri.json", "años que no crecen", lambda d: d["production"]["nat"]["wheat"]["area"].append([1960, 1000.0])),
 ("germany-agri.json", "produccion que no cuadra con rendimiento x superficie", lambda d: d["production"]["land"]["wheat"]["BY"]["prod"].__setitem__(-2, [d["production"]["land"]["wheat"]["BY"]["prod"][-2][0], d["production"]["land"]["wheat"]["BY"]["prod"][-2][1] * 3])),
 ("germany-agri.json", "precio de la tierra negativo", lambda d: d["landPrice"]["nat"]["lf"]["p"].__setitem__(0, [2021, -5.0])),
 ("germany-agri.json", "licencia cambiada", lambda d: d["source"].__setitem__("license", "CC0")),
 ("ers-cost-reference.json", "partidas que no suman el total publicado", lambda d: d["crops"]["maiz"]["costs"].__setitem__("fert", 999.0)),
 ("ers-cost-reference.json", "partida negativa", lambda d: d["crops"]["maiz"]["costs"].__setitem__("seed", -5.0)),
 ("ers-cost-reference.json", "costes imputados mayores que el total", lambda d: d["crops"]["soja"].__setitem__("imputed", 5000.0)),
 ("ers-cost-reference.json", "rendimiento inventado a cero", lambda d: d["crops"]["trigo"].__setitem__("yieldBuPerAcre", 0)),
 ("coverage-gaps.json", "celda AVAILABLE degradada sin cambiar series", lambda d: next(c for r in d["matrix"].values() for ms in r.values() for c in ms.values() if c["state"] == "AVAILABLE").__setitem__("state", "MISSING")),
 ("coverage-gaps.json", "series de una celda alteradas", lambda d: next(c for r in d["matrix"].values() for ms in r.values() for c in ms.values() if c["state"] == "AVAILABLE").__setitem__("series", 999)),
 ("coverage-gaps.json", "fuera del catalogo sin evidencia", lambda d: next(c for r in d["matrix"].values() for ms in r.values() for c in ms.values() if c["state"] == "MISSING").__setitem__("state", "AVAILABLE_OUTSIDE_CATALOG")),
 ("coverage-gaps.json", "candidata en revision presentada como lista para ingerir", lambda d: next(c for r in d["matrix"].values() for ms in r.values() for c in ms.values() if c["state"] == "LICENSE_PENDING").__setitem__("state", "SOURCE_AVAILABLE_NOT_INGESTED")),
 ("coverage-gaps.json", "resumen por estado sin cuadrar", lambda d: d["summary"]["byState"].__setitem__("MISSING", 1)),
 ("coverage-gaps.json", "hueco MISSING promovido a high sin evidencia", lambda d: next(c for r in d["matrix"].values() for ms in r.values() for c in ms.values() if c["state"] == "MISSING" and c["confidence"] != "high").__setitem__("confidence", "high")),
 ("coverage-gaps.json", "evidencia de confianza inventada", lambda d: next(c for r in d["matrix"].values() for ms in r.values() for c in ms.values() if c["state"] == "MISSING")["basis"].__setitem__("peers", 99)),
 ("coverage-gaps.json", "celda sin confidence", lambda d: next(c for r in d["matrix"].values() for ms in r.values() for c in ms.values()).pop("confidence")),
 ("coverage-gaps.json", "fuente atrasada inventada", lambda d: d["ranking"]["staleSources"].append({"sourceId": "inventada", "staleSeries": 1, "staleCells": 1, "countries": ["ES"]})),
 ("fx-history.json", "tipo implausible", lambda d: d["currencies"]["USD"].__setitem__(5, [d["currencies"]["USD"][5][0], 99.0])),
 ("fx-history.json", "meses desordenados", lambda d: d["currencies"]["USD"].reverse()),
 ("product-compare.json", "punto negativo", lambda d: d["products"]["trigo"]["series"][0]["points"].__setitem__(0, [d["products"]["trigo"]["series"][0]["points"][0][0], -1])),
 ("product-compare.json", "pais repetido", lambda d: d["products"]["trigo"]["series"].append(copy.deepcopy(d["products"]["trigo"]["series"][0]))),
 ("watch-index.json", "entrada mal formada", lambda d: d["series"].__setitem__("ES/x", ["a"])),
 ("pipeline-status.json", "resumen incoherente", lambda d: d["summary"].__setitem__("ok", 0)),
 ("pipeline-status.json", "workflow inexistente", lambda d: d["pipelines"][0].__setitem__("workflow", "no-existe.yml")),
 ("daily-brief.json", "recuento incoherente", lambda d: d["counts"].__setitem__("upcoming", 99)),
 ("instrument-identity.json", "instrumento sin identidad", lambda d: d["instruments"].pop("di_pienso_harina_soja_us")),
 ("instrument-identity.json", "etapa desconocida", lambda d: d["instruments"]["di_pienso_harina_soja_eu"].__setitem__("stage", "inventada")),
 ("instrument-identity.json", "soja UE y EE. UU. identicas", lambda d: d["instruments"]["di_pienso_harina_soja_us"].update({"grade": d["instruments"]["di_pienso_harina_soja_eu"]["grade"], "stage": d["instruments"]["di_pienso_harina_soja_eu"]["stage"], "form": "grain"}) or d["instruments"]["di_cereales_soja_grano_ca"].update({"grade": d["instruments"]["di_pienso_harina_soja_eu"]["grade"], "stage": d["instruments"]["di_pienso_harina_soja_eu"]["stage"], "form": "grain", "product": d["instruments"]["di_pienso_harina_soja_eu"]["product"]})),
 ("series-registry.json", "colision canonica no declarada", lambda d: d["series"][1].__setitem__("canonicalSeriesId", d["series"][0]["canonicalSeriesId"])),
 ("series-registry.json", "colision declarada solo en un sentido", lambda d: (d["series"][1].__setitem__("canonicalSeriesId", d["series"][0]["canonicalSeriesId"]), d["series"][1].__setitem__("file", "otro.json"), d["series"][0].__setitem__("alternates", [d["series"][1]["id"]]))),
 ("series-registry.json", "serie repetida", lambda d: d["series"].append(copy.deepcopy(d["series"][0]))),
 ("search-index.json", "URL externa", lambda d: d["entries"][0].__setitem__("u", "https://evil.example/")),
 ("drought.json", "D0..D4 creciente", lambda d: d["us"]["conus"][-1].__setitem__(5, 99.0)),
 ("drought.json", "porcentaje > 100", lambda d: d["us"]["conus"][-1].__setitem__(1, 140.0)),
 ("crop-progress.json", "condicion no suma 100", lambda d: d["crops"][0]["seasons"][next(iter(d["crops"][0]["seasons"]))]["condition"][0].__setitem__(1, 60)),
 ("cattle-on-feed.json", "balance de existencias roto", lambda d: d["reports"][0]["national"]["current"].__setitem__("placed", 9999)),
 ("cattle-on-feed.json", "total por estado distinto", lambda d: d["reports"][0]["states"][-1].__setitem__("current", 5)),
 ("cattle-on-feed.json", "suma de estados rota", lambda d: d["reports"][0]["states"][0].__setitem__("current", 9000)),
 ("cattle-on-feed.json", "publicado antes del inventario", lambda d: d["reports"][0].__setitem__("release", "2000-01-01")),
 ("eu-farm-economics.json", "produccion - consumo intermedio no es el valor anadido", lambda d: d["geos"]["ES"]["gva"].__setitem__(-1, 99999.0)),
 ("eu-farm-economics.json", "partidas superan el consumo intermedio", lambda d: d["geos"]["FR"]["feed"].__setitem__(-1, 9e9)),
 ("eu-farm-economics.json", "suma de los 27 distinta del agregado", lambda d: d["geos"]["EU27_2020"]["output"].__setitem__(-1, 1.0)),
 ("eu-farm-economics.json", "anos desordenados", lambda d: d["years"].reverse()),
 ("eu-farm-economics.json", "falta un indicador", lambda d: d["geos"]["DE"].pop("indA")),
 ("eu-regions-es.json", "regiones que no suman el total nacional", lambda d: d["regions"]["AN"]["eaa"]["AM200000"].__setitem__(-1, [d["regions"]["AN"]["eaa"]["AM200000"][-1][0], 99999.0])),
 ("eu-regions-fr.json", "falta una region", lambda d: d["regions"].pop("BRE")),
 ("eu-regions-nl.json", "falta una provincia", lambda d: d["regions"].pop("UT")),
 ("eu-regions-at.json", "falta un Land", lambda d: d["regions"].pop("W")),
 ("eu-regions-de.json", "vacas mas que vacuno total", lambda d: d["regions"]["NI"]["animals"]["A2300F"].__setitem__(-1, [d["regions"]["NI"]["animals"]["A2300F"][-1][0], 99999.0])),
 ("eu-regions-it.json", "rendimiento no plausible", lambda d: d["regions"]["LOM"]["crops"]["C1500"]["prod"].__setitem__(-1, [d["regions"]["LOM"]["crops"]["C1500"]["prod"][-1][0], 9999999.0])),
 ("eu-regions-es.json", "anios desordenados", lambda d: d["regions"]["CL"]["eaa"]["AM160000"].reverse()),
 ("eu-regions-fr.json", "explotaciones por tipo distintas del total", lambda d: d["regions"]["OCC"]["farms"]["TOTAL"]["2023"].__setitem__("HLD", 1.0)),
 ("au-states.json", "estados que no suman el total nacional", lambda d: d["states"]["NSW"]["agrifood"].__setitem__(-1, [d["states"]["NSW"]["agrifood"][-1][0], 99999.0])),
 ("au-states.json", "falta un estado", lambda d: d["states"].pop("QLD")),
 ("au-states.json", "valor negativo", lambda d: d["states"]["VIC"]["beef"].__setitem__(-1, [d["states"]["VIC"]["beef"][-1][0], -5.0])),
 ("canada-provinces.json", "produccion negativa", lambda d: d["provinces"]["SK"]["crops"]["wheat-all"]["prod"].__setitem__(-1, [d["provinces"]["SK"]["crops"]["wheat-all"]["prod"][-1][0], -5.0])),
 ("canada-provinces.json", "superficie cosechada mayor que sembrada", lambda d: d["provinces"]["AB"]["crops"]["barley"]["harea"].__setitem__(-1, [d["provinces"]["AB"]["crops"]["barley"]["harea"][-1][0], 99999.0])),
 ("canada-provinces.json", "provincias que no suman Canada", lambda d: d["provinces"]["SK"]["crops"]["canola-rapeseed"]["prod"].__setitem__(-1, [d["provinces"]["SK"]["crops"]["canola-rapeseed"]["prod"][-1][0], 1.0])),
 ("canada-provinces.json", "periodos desordenados", lambda d: d["provinces"]["ON"]["income"]["net-income-total"]["pts"].reverse()),
 ("canada-provinces.json", "falta una provincia clave", lambda d: d["provinces"].pop("QC")),
 ("canada-provinces.json", "mas vacas que vacuno total", lambda d: d["provinces"]["MB"]["cattle"]["beef-cows"]["pts"].__setitem__(-1, [d["provinces"]["MB"]["cattle"]["beef-cows"]["pts"][-1][0], 99999.0])),
 ("canada-drought.json", "porcentaje superior a 100", lambda d: d["provinces"]["SK"]["v"][-1].__setitem__(0, 140.0)),
 ("canada-drought.json", "clases no acumulativas", lambda d: d["provinces"]["AB"]["v"][-1].__setitem__(4, 100.0) or d["provinces"]["AB"]["v"][-1].__setitem__(3, 1.0)),
 ("canada-drought.json", "periodo que no es fin de mes", lambda d: d["periods"].__setitem__(-1, "2026-08-30")),
 ("canada-drought.json", "falta una provincia clave", lambda d: d["provinces"].pop("SK")),
 ("canada-drought.json", "filas distintas de meses", lambda d: d["provinces"]["MB"]["v"].pop()),
 ("eu-drought.json", "porcentaje superior a 100", lambda d: d["countries"]["ES"]["v"][-1].__setitem__(0, 140.0)),
 ("eu-drought.json", "clases que suman mas de 100", lambda d: d["countries"]["FR"]["v"][-1].__setitem__(1, 99.0)),
 ("eu-drought.json", "decada que no empieza en 1, 11 o 21", lambda d: d["periods"].__setitem__(-1, "2026-09-12")),
 ("eu-drought.json", "falta un pais clave", lambda d: d["countries"].pop("DE")),
 ("eu-drought.json", "filas distintas de decadas", lambda d: d["countries"]["IT"]["v"].pop()),
 ("us-dairy.json", "precio fuera de rango", lambda d: d["products"][0]["series"][-1].__setitem__(1, 99.0)),
 ("us-dairy.json", "semana que no acaba en sabado", lambda d: d["products"][0]["series"][-1].__setitem__(0, "2026-09-25")),
 ("us-dairy.json", "semanas desordenadas", lambda d: d["products"][1]["series"].reverse()),
 ("us-dairy.json", "falta un producto", lambda d: d["products"].pop()),
 ("eu-vat.json", "tipo general fuera de rango", lambda d: d["countries"]["ES"].__setitem__("standard", 90.0)),
 ("eu-vat.json", "falta un pais", lambda d: d["countries"].pop("FR")),
 ("eu-vat.json", "tipo reducido mayor que el general", lambda d: d["countries"]["DE"]["reduced"][0].__setitem__("rate", 30.0)),
 ("eu-vat.json", "tipo de cultivo mayor que el general", lambda d: d["countries"]["ES"]["crops"].__setitem__("soja", 30.0)),
 ("other-tax.json", "tipo estatal absurdo", lambda d: d["us"]["states"]["TX"].__setitem__("rate", 60.0)),
 ("other-tax.json", "falta un estado", lambda d: d["us"]["states"].pop("OH")),
 ("other-tax.json", "estado sin impuesto con tipo", lambda d: d["us"]["states"]["OR"].__setitem__("rate", 5.0)),
 ("other-tax.json", "reducido del Reino Unido mayor que el general", lambda d: d["gb"].__setitem__("reduced", 25.0)),
 ("canada-grain.json", "semanas desordenadas", lambda d: d["weeks"].reverse()),
 ("canada-grain.json", "exportacion negativa", lambda d: d["grains"][0]["exports"].__setitem__(-1, -5.0)),
 ("canada-grain.json", "columna de otra longitud", lambda d: d["grains"][1]["stocks"].pop()),
 ("canada-grain.json", "acumulado que cae", lambda d: d["grains"][0]["cumExports"].__setitem__(-1, 1.0)),
 ("canada-grain.json", "semana que no acaba en domingo", lambda d: d["weeks"].__setitem__(-1, "2026-09-25")),
 ("us-lamb.json", "precio fuera de rango", lambda d: d["rows"][-1].__setitem__(1, 5000.0)),
 ("us-lamb.json", "neto mayor que bruto", lambda d: d["rows"][-1].__setitem__(2, d["rows"][-1][1] + 10)),
 ("us-lamb.json", "dias desordenados", lambda d: d["rows"].reverse()),
 ("us-lamb.json", "delantero y trasero incoherentes", lambda d: d["rows"][-1].__setitem__(3, 1400.0)),
 ("us-fertilizers.json", "precio fuera de rango", lambda d: d["products"][0]["states"][0].__setitem__("avg", 90000)),
 ("us-fertilizers.json", "promedio fuera de min-max", lambda d: d["products"][0]["states"][0].update({"min": 1, "max": 2})),
 ("us-fertilizers.json", "historico no termina en el ultimo", lambda d: d["products"][0]["states"][0]["hist"].pop()),
 ("us-fertilizers.json", "fila repetida", lambda d: d["products"][0]["states"].append(copy.deepcopy(d["products"][0]["states"][0]))),
 ("usda-calendar.json", "publicacion en fin de semana", lambda d: d["releases"][0].__setitem__("date", "2026-10-03")),
 ("usda-calendar.json", "publicacion repetida", lambda d: d["releases"].insert(1, copy.deepcopy(d["releases"][0]))),
 ("usda-calendar.json", "agencia desconocida", lambda d: d["releases"][0].__setitem__("agency", "XYZ")),
 ("climate.json", "temperatura imposible", lambda d: d["locations"][0]["months"][0].__setitem__("tempC", 90)),
 ("recan.json", "indice fuera de rango", lambda d: d["rows"][0].__setitem__(1, 99)),
 ("revisions.json", "revision sin fecha", lambda d: d["revisions"].append({"file": "a", "series": "x", "period": "2020", "old": 1, "new": 2})),
 ("catalog/manifest.json", "total incoherente", lambda d: d.__setitem__("seriesTotal", d["seriesTotal"] + 5)),
 ("catalog/series-index.json", "fila sin serie en catalogo (total)", lambda d: d["rows"].pop()),
 ("catalog/series-index.json", "indice fuera del diccionario", lambda d: d["rows"][0].__setitem__(2, 9999)),
 ("catalog/series-index.json", "serie repetida", lambda d: d["rows"].__setitem__(1, list(d["rows"][0]))),
 ("catalog/series-index.json", "estado invalido", lambda d: d["dict"]["fs"].__setitem__(0, "MAYBE")),
 ("export-sales.json", "semana desordenada", lambda d: d["commodities"][0]["weekly"].reverse()),
 ("gats.json", "mes futuro", lambda d: d["months"].append("209901")),
 ("freshness.json", "recuento incoherente", lambda d: d["catalog"]["byState"].__setitem__("LIVE", d["catalog"]["byState"]["LIVE"] + 1)),
 ("freshness.json", "estado inventado", lambda d: d["latest"]["observations"][0].__setitem__("state", "MAYBE")),
 ("product-metadata.json", "serie UE inexistente", lambda d: d["products"]["trigo"]["compare"].__setitem__("eu", ["cereales", "no-existe"])),
 ("product-metadata.json", "sin nombre en un idioma", lambda d: d["products"]["trigo"]["name"].pop("it")),
 ("product-metadata.json", "instrumento inexistente", lambda d: d["products"]["trigo"]["instruments"].append({"region": "us", "product": "no-existe"})),
 ("product-metadata.json", "relacion inventada", lambda d: d["products"]["trigo"]["related"].append({"product": "no-existe", "relation": "input", "why": "energy"})),
 ("products/trigo.json", "cuota que no es valor/mundo", lambda d: d["trade"]["exports"]["top"][0].__setitem__("share", 55.5)),
 ("products/trigo.json", "producto desconocido", lambda d: d.__setitem__("product", "no-existe")),
 ("products/trigo.json", "stock-to-use inventado", lambda d: d["supplyDemand"]["entities"]["US"][str(d["supplyDemand"]["marketYear"])].__setitem__("stockToUse", 5.0)),
 ("products/trigo.json", "campana fuera de ventana", lambda d: d["supplyDemand"]["entities"]["EU"].__setitem__("2010", {"production": 1})),
 ("products/trigo.json", "top desordenado", lambda d: d["trade"]["exports"]["top"].reverse()),
 ("freshness-policy.json", "rezago sin evidencia", lambda d: d["sources"]["statcan"].__setitem__("evidence", "x")),
 ("freshness-policy.json", "rezago absurdo", lambda d: d["sources"]["statcan"]["lagDays"].__setitem__("monthly", 9999)),
 ("quality.json", "freshness incoherente", lambda d: d["observations"][0].__setitem__("freshness", "STALE")),
 ("data-anomalies.json", "KNOWN sin evidencia", lambda d: d["anomalies"][0].__setitem__("status", "KNOWN_VERIFIED_ANOMALY")),
 ("data-anomalies.json", "serie inexistente", lambda d: d["anomalies"][0].__setitem__("series", "AT/no-existe")),
 ("daily-brief.json", "byKind incoherente", lambda d: d["byKind"]["PRICE"].__setitem__("datasets", 99)),
 ("daily-brief.json", "pipeline sin clasificar", lambda d: d["pipelinesCovered"].__setitem__("total", d["pipelinesCovered"]["total"] + 1)),
 ("product-compare.json", "sin aggregation", lambda d: d["products"]["trigo"]["series"][0].pop("aggregation")),
 ("product-compare.json", "estado de frescura inventado", lambda d: d["products"]["trigo"]["series"][0].__setitem__("fs", "OK")),
 ("views/home-summary.json", "mover con historico", lambda d: d["movers"][0].__setitem__("history", [1, 2])),
 ("views/home-summary.json", "markets.total incoherente", lambda d: d["markets"].__setitem__("total", d["markets"]["total"] + 1)),
 ("views/news-index.json", "clave fuera de rango", lambda d: d["keys"].__setitem__("trigo", [10 ** 6])),
 ("views/news-index.json", "enlace no http", lambda d: d["stories"][0].__setitem__("url", "javascript:alert(1)")),
 ("views/news-feed.json", "noticia repetida", lambda d: d["items"].append(copy.deepcopy(d["items"][0]))),
 ("views/news-feed.json", "fecha invalida", lambda d: d["items"][0].__setitem__("d", "ayer")),
 ("prices/manifest.json", "total incoherente", lambda d: d["totals"].__setitem__("observations", 1)),
 ("prices/manifest.json", "producto sin historico", lambda d: next(iter(d["regions"].values()))["products"].append("no-existe")),
 ("prices/latest/us.json", "historico dentro de latest", lambda d: first(d).__setitem__("history", [1])),
 ("prices/latest/us.json", "region cruzada", lambda d: first(d).__setitem__("region", "eu")),
 ("prices/latest/us.json", "spark no numerico", lambda d: first(d).__setitem__("spark", ["x"])),
 ("prices/history/us/trigo.json", "historico desordenado", lambda d: d["history"].reverse()),
 ("prices/history/us/trigo.json", "valor no numerico", lambda d: d["history"][3].__setitem__("value", "n/a")),
 ("prices/intelligence/uk.json", "puntos desordenados", lambda d: next(iter(d["series"].values()))["points"].reverse()),
 ("prices/intelligence/uk.json", "serie no comparable", lambda d: next(iter(d["series"].values())).__setitem__("comparability", "not_comparable")),
 ("daily-brief.json", "cashBids: rango incoherente", lambda d: d["cashBids"]["groups"][0].__setitem__("min", d["cashBids"]["groups"][0]["max"] + 1)),
 ("daily-brief.json", "cashBids: mercados de mas", lambda d: d["cashBids"].__setitem__("marketsUpdated", 0)),
 ("us-cash-bids/IA/corn.json", "precio negativo", lambda d: d["series"][0]["pts"][-1].__setitem__(1, -4.1)),
 ("us-cash-bids/IA/corn.json", "minimo > maximo", lambda d: d["series"][0]["pts"][-1].__setitem__(2, 99.0)),
 ("us-cash-bids/IA/corn.json", "ultima obs distinta del ultimo punto", lambda d: d["series"][0].__setitem__("avg", d["series"][0]["avg"] + 0.5)),
 ("us-cash-bids/IA/corn.json", "id de otro informe", lambda d: d["series"][0].__setitem__("id", "us-cb:1:" + d["series"][0]["id"].split(":")[2])),
 ("us-cash-bids/IA/corn.json", "serie en shard equivocado", lambda d: d["series"][0].__setitem__("commodity", "wheat")),
 ("us-cash-bids/IA/corn.json", "cambio alterado", lambda d: d["series"][0].__setitem__("changePct", 25.0)),
 ("us-cash-bids/IA/corn.json", "priceKind inventado", lambda d: d["series"][0].__setitem__("priceKind", "EXACT")),
 ("us-cash-bids/IA/corn.json", "locationType inventado", lambda d: d["series"][0].__setitem__("locationType", "LOCAL_ELEVATOR")),
 ("us-cash-bids/IA/corn.json", "ELEVATOR sin instalacion", lambda d: d["series"][0].update({"locationType": "ELEVATOR", "locationName": None})),
 ("us-cash-bids/IA/corn.json", "puntos desordenados", lambda d: d["series"][0]["pts"].reverse()),
 ("us-cash-bids/IA/corn.json", "credencial en el fichero", lambda d: d.__setitem__("note", "Authorization: Basic QUJDREVGR0hJSktMTU5PUA==")),
 ("us-cash-bids/IA/corn.json", "frescura inventada", lambda d: d["series"][0].__setitem__("freshness", "SUPER_FRESH")),
 ("us-cash-bids/history/IA/corn.json", "historico desordenado", lambda d: next(iter(d["series"].values()))["pts"].reverse()),
 ("us-cash-bids/history/IA/corn.json", "historico con precio cero", lambda d: next(iter(d["series"].values()))["pts"][0].__setitem__(1, 0)),
 ("us-cash-bids/manifest.json", "totales alterados", lambda d: d["totals"].__setitem__("series", d["totals"]["series"] + 1)),
 ("us-cash-bids/manifest.json", "licencia distinta del registro", lambda d: d["license"].__setitem__("status", "PENDING")),
 ("us-cash-bids/manifest.json", "shard inexistente", lambda d: d["states"]["IA"]["commodities"]["corn"].__setitem__("shard", "IA/nada.json")),
 ("us-cash-bids/zip-state.json", "estado inventado", lambda d: d["prefix"].__setitem__("500", "ZZ")),
 ("us-cash-bids/zip-state.json", "ZIP de Iowa en otro estado", lambda d: d["prefix"].__setitem__("500", "KS")),
 ("us-cash-bids/zip-state.json", "tabla recortada", lambda d: [d["prefix"].pop(k) for k in list(d["prefix"])[:200]]),
 ("us-cash-bids/reports.json", "informe repetido", lambda d: d["reports"].append(copy.deepcopy(d["reports"][0]))),
 ("us-cash-bids/reports.json", "active distinto del registro", lambda d: d["reports"][0].__setitem__("active", not d["reports"][0]["active"])),
 ("us-cash-bids/reports.json", "estado de ingesta inventado", lambda d: d["reports"][0].__setitem__("ingestionStatus", "PERFECT")),
]
bad = 0
for rel, name, fn in CASES:
    try: r = run(rel, fn)
    except Exception as e: print("ROTO   %-24s %-26s %r" % (rel, name, e)); bad += 1; continue
    ok = r["status"] == "error"
    if not ok: bad += 1
    print("%-6s %-24s %-26s %s" % ("OK" if ok else "FALLA", rel, name, "" if ok else "el validador NO lo detecto"))
# datos reales intactos
for rel in ("latest.json", "fx-history.json", "product-compare.json"):
    r = run(rel, lambda d: None)
    if r["status"] == "error": print("FALLA datos reales %s: %s" % (rel, r["errors"][:2])); bad += 1
print("%d casos, %d fallos" % (len(CASES), bad)); sys.exit(1 if bad else 0)
